### ISSUE TITLE
"illuminate/support": "5.*"

### ISSUE THREAD

**Issue by inouticu** [amocrm/amocrm-api-php#1]
Добрый день.

Из-за "устаревшей" зависимости не удается установить библиотеку в рамках Laravel 6.

`"illuminate/support": "5.*"`

Может имеет смысл проверить совместимость с более актуальными версиями "illuminate/support" и поправить composer.json?

`illuminate/support": "^5.0 || ^6.0` или `"illuminate/support": "^5.0 || ^6.0 || ^7.0"`

Заранее спасибо.

**Comment by bessudnov** [comment]
Спасибо за фидбек, в ближайшее время проверим

**Comment by bessudnov** [comment]
Обновление доступно в версии 0.1.1
