### ISSUE TITLE
Получаю ошибку

### ISSUE THREAD

**Issue by BagrovAnatoli** [amocrm/amocrm-api-php#104]
Здравствуйте, установил библиотеку. Пробую использовать.
подключаю файл в скрипт:
require _ROOT.'/oAuth/vendor/autoload.php';
use AmoCRM\Exceptions\AmoCRMApiException;
use AmoCRM\Models\AccountModel;
use League\OAuth2\Client\Token\AccessTokenInterface;

команда $apiClient = new \AmoCRM\Client\AmoCRMApiClient($clientId, $clientSecret, $redirectUri);
приводит к ошибке: Parse error: syntax error, unexpected ':', expecting '{' in /home/c/co90833/scripts/public_html/oAuth/vendor/symfony/polyfill-php80/bootstrap.php on line 23

Мой скрипт выполняется на php 5.4. Может от этого зависит?

**Comment by BagrovAnatoli** [comment]
Токен получаю

**Comment by bessudnov** [comment]
Библиотека работает только с PHP 7.1 и выше
