### ISSUE TITLE
Problem with oauth

### ISSUE THREAD

**Issue by SergheiDinu** [amocrm/amocrm-api-php#105]
I did copy the code from "examples" and did put the integrationID, secret... and everything is needed into env and end.dist file. 
But when I'm trying to run "get_token" into browser i gut the error. 
![image](https://user-images.githubusercontent.com/60985084/89197660-bb371400-d5b4-11ea-9f4b-7426a7d7a75b.png)

Someone told me that is a problem with index.php, but I can not find this file into your repository.  Who could help me with this issue?

Thanks

**Comment by bessudnov** [comment]
You need to set redirect_uri in amoCRM integration, that looks like https://xxxx.xxxx/examples/get_token.php

**Comment by SergheiDinu** [comment]
I actually did it. 
If you mean this one...
![image](https://user-images.githubusercontent.com/60985084/89205588-a1033300-d5c0-11ea-83ec-04ed24ea9a3b.png)

**Comment by bessudnov** [comment]
In your screenshot Redirect address is not correct, to use examples it should finish with /examples/get_token.php

**Comment by andreybolonin** [comment]
Добрый день, вот такая ошибка

`AmoCRM\Exceptions\AmoCRMoAuthApiException: AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный клиент: Авторизация клиента не прошла in /var/www/hbadmin/vendor/amocrm/oauth2-amocrm/src/AmoCRMException.php:24`

**Comment by andreybolonin** [comment]
`curl https://salepartners.amocrm.ru/oauth2/access_token -d \
'{"client_id":"a2798b1b-86b9-4886-a7fe-5e84cb467d3a","client_secret":"bOqbQrqyg834UjEgaCUtrAJx19wDHU8mQuUR1v0sHd1LQZ9hUzJrDh1gjsb9dmph","grant_type":"authorization_code","code":"def502009c659637da0a76d9c929492547677507f3fa2661afd0529decb37bf79d2260df6f59b52bdcd2493ead70f7f837b6fceb471ed53e889b9ba5a0bb01d1333f27e530e49e4bcc44e51aa287d6d72cf0f7f5fff1ea19bde28da407079686362ae49046c195fc3acb01e620f67bd2c9f2f6889f326f599dc79b38330cb4e542bea0782a1acb75995706490be3f008ce1a9ea06a8531754b4e7e1c86cd71044fb99f986d4d7b6063a9b73e391c8c65b686d2e6caac57ee2fe9b9fedeb9698008cbaeb15ca0237d41e5300a46efbcff27c5b6dad0275db49a0757bc2ef06d0bb738e64e56e448b9d47c236550140cfe4d2c37bda3d857e4a070b16c7e65f6a11083734375e57dad58323bfd53840523eedeffc14de1aa1b90ee1ea5ee56aa9d914dac78a0253dca86aaa5ea7f56f3196fe7f96150d3de4f8c5c61113a79eb271f491b2201f4da5b289047ef61bf479ffc3876cc991cd3bba5a4765f30c86c472a0a6e10330dbabc14436cb63c0a9822fbb1ab37b8ba38bcebe1d4efb51fcb41d221953572f6d61641560dc31686afe74d1634fcd44ab84ae84a8def02aa8e0295ca7d4746457a23d500877c97fce8cf5ade570efc22e16d0bbf36d6e6e3404f2de2ef411f9dda","redirect_uri":"https://hb.andreybolonin.com/"}' \
-H 'Content-Type:application/json' \
-X POST`

{"title":"Некорректный клиент","type":"https://developers.amocrm.ru/v3/errors/OAuthProblemJson","status":401,"detail":"Авторизация клиента не прошла"}

**Comment by bessudnov** [comment]
Закрываю из-за неактивности, откройте повторно, если вопрос еще актуален
