### ISSUE TITLE
Fatal error. amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php on line 444. Uncaught AmoCRM\Exceptions\AmoCRMApiNoContentException

### ISSUE THREAD

**Issue by Kariamba** [amocrm/amocrm-api-php#110]
При поиске клиента по номеру телефона использую такую конструкцию:
$filter = new AmoCRM\Filters\ContactsFilter();
$filter->setQuery('+7 999 0000000');
$contacts = $apiClient->contacts()->get($filter);

Если в базе есть такой номер, то приходит нормальный ответ. Если нет, то возвращается не пустая коллекция как ожидается, а вылетает fatal error:  Uncaught AmoCRM\Exceptions\AmoCRMApiNoContentException: No content in...

**Comment by Kariamba** [comment]
Сразу предвосхищу один ваш вопрос. Код обернут в try catch:
try {
	$filter = new AmoCRM\Filters\ContactsFilter();
	$filter->setQuery('+79991234567');
	$contacts = $apiClient->contacts()->get($filter);
} catch (AmoCRMApiException $e) {
	echo 'Error:<br/>'; /* эта строка не выводится, значит сюда не заходим! */
	printError($e);
	die;
}

**Comment by Kariamba** [comment]
А вас не смущает, что она вываливается в обертке try-catch? Причем если посмотреть исходники, то сыпится она как раз на throw.
Я конечно могу начать править библиотеку, но тогда возникает резонный вопрос - на кой тогда вообще использовать этого монстра?

**Comment by bessudnov** [comment]
Выдержка из README

AmoCRM\Exceptions\AmoCRMApiNoContentException | Сервер вернул код 204 без результата, ничего страшного не произошло, просто нет данных на ваш запрос

Вам необходимо просто обернуть вызов метод в try-catch и поймать ошибку, что данных не найдено

**Comment by Kariamba** [comment]
Так у меня есть обертка, вот кусок кода:
try {
	$filter = new AmoCRM\Filters\ContactsFilter();
	$filter->setQuery('+79991234567');
	$contacts = $apiClient->contacts()->get($filter);
} catch (AmoCRMApiException $e) {
	echo 'Error:<br/>'; /* эта строка не выводится, значит сюда не заходим! */
	printError($e);
	die;
}

**Comment by bessudnov** [comment]
Странно, данный код должен перехватить ошибку, да
а есть в начале файла `use AmoCRM\Exceptions\AmoCRMApiException;`?

**Comment by Kariamba** [comment]
Действительно пропустил неймспейс.
Получается пустой ответ надо обрабатывать в ветке catch?

**Comment by bessudnov** [comment]
> Действительно пропустил неймспейс.
> Получается пустой ответ надо обрабатывать в ветке catch?

Да, всё верно
