### ISSUE TITLE
token_actions.php

### ISSUE THREAD

**Issue by i4j5** [amocrm/amocrm-api-php#114]
$accessToken = $apiClient->getOAuthClient()->getAccessTokenByCode($_GET['code']);

AmoCRM\Exceptions\AmoCRMoAuthApiException
AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны

В чём проблема?

**Comment by bessudnov** [comment]
Проверьте, что адрес для редиректа совпадает полностью (включая слеши, гет параметры и тд) в интерфейсе и с тем, который указан в коде

**Comment by nkarpovich** [comment]
> $accessToken = $apiClient->getOAuthClient()->getAccessTokenByCode($_GET['code']);
> 
> AmoCRM\Exceptions\AmoCRMoAuthApiException
> AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны
> 
> В чём проблема?

Такая же была ошибка, в настройках API слеш стоял в конце в адресе для редиректа, а в моем коде слеша не было

**Comment by i4j5** [comment]
$apiClient->setAccountBaseDomain($domain);  
Домен можно добавлять только после авторизации

**Comment by PHPTCloud** [comment]
> $apiClient->setAccountBaseDomain($domain);
> Домен можно добавлять только после авторизации

examples/get_token.php
```php
<?php

include_once __DIR__ . '/bootstrap.php';

session_start();

if (isset($_GET['referer'])) {
    $apiClient->setAccountBaseDomain($_GET['referer']);
}

...
```

**Comment by Bodarev** [comment]
> а если это не адрес, то что может быть? у меня адрес идентичен, как в коде так и в настройках api ? - http://joxi.ru/brRvexGUBVvEar
