### ISSUE TITLE
400 Request validation failed для leads()->addOne

### ISSUE THREAD

**Issue by ramik5** [amocrm/amocrm-api-php#115]
Если указать не существующее значение в поле тип "Список", сделка не добавляется. Вылетает ошибка:

[last_response] => {"validation-errors":[{"request_id":"0","errors":[{"code":"NotSupportedChoice","path":"custom_fields_values.6.values.0.value","detail":"The value you selected is not a valid choice."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}[last_response_code] => 400

Это баг или ограничение амо?

**Comment by bessudnov** [comment]
Запрос не прошел валидацию, это нормальное поведение API, если передать не валидные данные - будет ошибка валидации ответ от API
