### ISSUE TITLE
Проблема с добавлением сделки вместе с тегами

### ISSUE THREAD

**Issue by RomanMazyrin** [amocrm/amocrm-api-php#12]
Пытаюсь добавить сделку с тегами, делаю по примеру из [этого файла](https://github.com/amocrm/amocrm-api-php/blob/master/examples/tags_actions.php)

Выяснилось, что сервер не хочет принимать запрос на добавление, когда видит поле request_id у тега. Текст ошибки:

`Response has validation errors`

Вот отрывок из getLastRequestInfo() исключения:

```
{"validation-errors":[{"request_id":"0","errors":[{"code":"FieldNotExpected","path":"_embedded.tags.0.request_id","detail":"This field was not expected."},{"code":"FieldNotExpected","path":"_embedded.tags.1.request_id","detail":"This field was not expected."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}
```

Вот пример кода на добавление:

```
$tags = $apiClient->tags(EntityTypesInterface::LEADS)->get((new TagsFilter())->setQuery($tagName));
if (!is_null($tags)) {
    $tagsCollection->add($tags->getBy("name", $tagName));
} else {
    $newTag = new TagModel();     
    $newTag->setName($tagName);
    $newTag = $apiClient->tags(EntityTypesInterface::LEADS)->addOne($newTag);
    $tagsCollection->add($newTag);
}

...

$newLead = new LeadModel();
$newLead->setName($leadName)->setTags($tagsCollection);
return $leadsService->addOne($newLead)->getId();
```

**Comment by bessudnov** [comment]
Посмотрю сегодня

А на новую версию аккаунт уже переходил, с которым работаете?

**Comment by RomanMazyrin** [comment]
Что подразумевается под новой версией? Где можно посмотреть версию вообще?

**Comment by bessudnov** [comment]
В любом случае поправил)

Новая версия эта та, которую показали в мае. Понять новая версия или нет можно в методе api/v4/account?with=version - 10 старая, 11 - новая

+ можно посмотреть если у админа аккаунта есть в настройках пункт "Обновление весна 2020", то старая

**Comment by RomanMazyrin** [comment]
А, да не, я думал там что-то более тонкое) В таком случае обновленная у нас конечно)

Спасибо за исправление!

**Comment by bessudnov** [comment]
В мастер влил фикс, релиз думаю завтра с утра будет

**Comment by bessudnov** [comment]
Исправлено в релизе 0.2.3
