### ISSUE TITLE
Логика действий, когда код ответа 204

### ISSUE THREAD

**Issue by nomelodic** [amocrm/amocrm-api-php#122]
Здравствуйте. Хочу прояснить один волнующий меня момент:

Делаю запрос
`$unsortedFiler = new UnsortedFilter();`
`$unsortedFiler->setPipelineId($pipeline_id);`
`$response = $client->unsorted()->get($unsortedFiler);`

В передаваемой воронке в неразобранном ничего нет, получаем в ответ код 204.
По логике, описанной в документации на сайте коды 200 и 204 считаются успешными
`try`
`{`
`    /** Если код ответа не успешный - возвращаем сообщение об ошибке */`
`    if ($code < 200 || $code > 204) {`
`        throw new Exception(isset($errors[$code]) ? $errors[$code] : 'Undefined error', $code);`
`    }`
`}`
`catch(\Exception $e)`
`{`
`    die('Ошибка: ' . $e->getMessage() . PHP_EOL . 'Код ошибки: ' . $e->getCode());`
`}`

Однако, библиотека отваливает Exception с описанием ошибки "No content". Получается такая ситуация, что вроде как это ошибкой считаться не должно и, соответственно, в ответе нужно вернуть пустой массив или null, или false, или что угодно, но вернуть, а вместо этого мы получаем ошибку, т.е. при работе с библиотекой нужно дополнительно отлавливать код 204 в catch и вместо ошибки возвращать пустой массив.

Отсюда вопрос: так и планировалось? И если да, то может быть стоит как-то согласовать этот момент с документацией

**Comment by nomelodic** [comment]
Собственно, вот код, который отвечает за этот Exception (файл src/AmoCRM/Client/AmoCRMApiRequest.php, строки 443-449):
```
if ((int)$response->getStatusCode() === StatusCodeInterface::STATUS_NO_CONTENT) {
            throw new AmoCRMApiNoContentException(
                "No content",
                $response->getStatusCode(),
                $this->getLastRequestInfo()
            );
        }
```
Но вот что интересно, следом, в строке 451 идёт такая проверка:
`if (!in_array((int)$response->getStatusCode(), self::SUCCESS_STATUSES, true)) {`

И если заглянуть в константу `self::SUCCESS_STATUSES`, то можно увидеть, что `StatusCodeInterface::STATUS_NO_CONTENT` входит в список "успешных" статусов:
```
public const SUCCESS_STATUSES = [
        StatusCodeInterface::STATUS_OK,
        StatusCodeInterface::STATUS_CREATED,
        StatusCodeInterface::STATUS_ACCEPTED,
        StatusCodeInterface::STATUS_NO_CONTENT,
    ];
```

**Comment by bessudnov** [comment]
Согласен, что не супер логично, на самом начальном этапе так и планировалось, после начала использования в массах, стало понятно, что это не очень удобно, но без мажорного релиза этот момент мы точно менять не будем, в ближайшее время он не планируется
