### ISSUE TITLE
Вопрос по oAuth

### ISSUE THREAD

**Issue by nkarpovich** [amocrm/amocrm-api-php#123]
У меня настроен вебхук с сайта при обновлении сделки к моему скрипту, который обращается по API при поступившем запросе.

С первичной авторизацией и получением refresh-токена нет проблем. 
У меня добавлен обработчик onAccessTokenRefresh, я его тестировал руками (просто expires менял на прошедшую дату) - он работает, токены обновляются и записываются.

День-другой это все крутится а потом при запросах выдает ошибку:
`{"hint":"Token has been revoked","title":"Некорректный запрос","type":"https://developers.amocrm.ru/v3/errors/OAuthProblemJson","status":401,"detail":"В запросе отсутствует ряд параметров или параметры невалидны"}`

До запросов по API дело не доходит, это происходит на этапе попытки запросить новый токен по рефреш-токену.

Может быть есть какие-то идеи, почему так может происходить? На другом проекте у меня код идентичный, кроме веб-хука ничем не отличается в части авторизации. Был бы признателен.

**Comment by bessudnov** [comment]
Такая ошибка может происходить, если вы используете refresh token, который уже был использован

**Comment by katw3ll** [comment]
@bessudnov так что делать то? Тоже с такой проблемой только что столкнулся(

**Comment by katw3ll** [comment]
`
const getContactId = async(leadId) => {
    const response = await crm.request.get( '/api/v4/leads/'+leadId+'/links');
    const data = response.data['_embedded']['links'];
    let contactId;
    data.forEach(function(item) {
        if (item['to_entity_type'] == 'contacts'){
            contactId = item['to_entity_id'];
        }
    });
    return contactId;
}

const getEmail = async(contactId) => {
    const response = await crm.request.get( '/api/v4/contacts/'+contactId);
    console.log(response.data)
    // const data = response.data['_embedded']['links'];
}

(async () => {
    console.log(await getContactId(3595327))
    console.log(await getEmail(5876807))
})();
`
Возможно я что-то делаю неправильно, помогите пожалуйста.
Мне нужно получить почту для определенного лида. Данная билиотечка не позволяет второй раз выполнить запрос((
@bessudnov 
Консоль выдачи:
`
5876807
(node:17878) UnhandledPromiseRejectionWarning: Error: Auth Error
    at /home/katw3ll/node_modules/amocrm-js/dist/base/AmoConnection.js:262:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by nkarpovich** [comment]
> Такая ошибка может происходить, если вы используете refresh token, который уже был использован

спасибо, был косяк с правами доступа к файлу, в который записывался токен и из-за этого туда не записывался обновленный рефреш токен
