### ISSUE TITLE
Ошибка Unprocessable field type - org_legal_name

### ISSUE THREAD

**Issue by devleatherks** [amocrm/amocrm-api-php#125]
Если пользователь создать поле типа "org_legal_name" то sdk выбрасывает эксепшн:  "Unprocessable field type - org_legal_name"

В ходе разговора с тех. поддержкой было установлено следующее: 
1. Данное поле может быть создано только на аккаунтах .COM 
2. Данное поле не имеет значения

Чтоб воспроизвести данную ошибку в SDK нужно заполнить у контакта поле с типом "org_legal_name"

Нужно как-то обрабатывать данное поле чтоб не было ошибки, так как: 
Если мы запросим контакт с данным полем, то мы получим ошибку и дальше с данной сущностью мы не сможем работать, а пользователя как бы мало интересует что там какая-то SDK не может обработать.

**Comment by devleatherks** [comment]
Где искать исключение: 
src/AmoCRM/Models/CustomFieldsValues/Factories

**Comment by devleatherks** [comment]
Пример контакта с заполненным полем типа "org_legal_name": 
`{
    "id": 43591281,
    "name": "Контакт email-email@mail.ru",
    "first_name": "",
    "last_name": "",
    "responsible_user_id": 1640260,
    "group_id": 0,
    "created_by": 3061717,
    "updated_by": 1640260,
    "created_at": 1581500866,
    "updated_at": 1599115566,
    "closest_task_at": null,
    "custom_fields_values": [
        {
            "field_id": 480287,
            "field_name": "Contact_List",
            "field_code": null,
            "field_type": "select",
            "values": [
                {
                    "value": "option 3",
                    "enum_id": 947829
                }
            ]
        },
        {
            "field_id": 480281,
            "field_name": "Contact_Text",
            "field_code": null,
            "field_type": "text",
            "values": [
                {
                    "value": "Text of text field"
                }
            ]
        },
        {
            "field_id": 365031,
            "field_name": "Email",
            "field_code": "EMAIL",
            "field_type": "multitext",
            "values": [
                {
                    "value": "accaunt@mail.ru",
                    "enum_id": 772987,
                    "enum_code": "WORK"
                },
                {
                    "value": "t-accaunt@e.cn.ua",
                    "enum_id": 772987,
                    "enum_code": "WORK"
                }
            ]
        },
        {
            "field_id": 480289,
            "field_name": "Contact_MultiList",
            "field_code": null,
            "field_type": "multiselect",
            "values": [
                {
                    "value": "3",
                    "enum_id": 947839
                },
                {
                    "value": "5",
                    "enum_id": 947843
                }
            ]
        },
        {
            "field_id": 489779,
            "field_name": "Contact_Link",
            "field_code": null,
            "field_type": "url",
            "values": [
                {
                    "value": "http://7777"
                }
            ]
        },
        {
            "field_id": 480305,
            "field_name": "Contact_Company",
            "field_code": null,
            "field_type": "legal_entity",
            "values": [
                {
                    "value": {
                        "name": "СХПК \"КОЛХОЗ \"НОВОКУРУПКАЕВСКИЙ\"",
                        "entity_type": null,
                        "vat_id": "5418102085",
                        "tax_registration_reason_code": null,
                        "address": null,
                        "kpp": "545451010",
                        "external_uid": null
                    }
                }
            ]
        },
        {
            "field_id": 480307,
            "field_name": "Contact_Organization",
            "field_code": null,
            "field_type": "org_legal_name",
            "values": []
        },
        {
            "field_id": 489793,
            "field_name": "Юр. лицо",
            "field_code": null,
            "field_type": "legal_entity",
            "values": [
                {
                    "value": {
                        "name": "5555",
                        "entity_type": null,
                        "vat_id": null,
                        "tax_registration_reason_code": null,
                        "address": null,
                        "kpp": null,
                        "external_uid": null
                    }
                }
            ]
        }
    ],
    "account_id": 15816835,
    "_links": {
        "self": {
            "href": "https://instadirect.amocrm.ru/api/v4/contacts/43591281"
        }
    },
    "_embedded": {
        "tags": [],
        "companies": []
    }
}`

**Comment by bessudnov** [comment]
Согласен, бага, данное поле просто должно быть пропущено библиотекой, так как по-сути, является deprecated, из-за бага порядка нескольких месяцев можно было добавить подобное поле в аккаунте
В ближайшее время поправим
