### ISSUE TITLE
Заявка с сайта

### ISSUE THREAD

**Issue by i4j5** [amocrm/amocrm-api-php#131]
Подскажите, как правильно работать с полями. Например. Заявка с сайта. Нужно создать контакт и сделку. заполнить всю информацию. Написать примечание. Поставить задачу.  Не могу разобраться.

**Comment by nomelodic** [comment]
Здесь с документацией проблемы, поэтому попробую вам помочь выжимками из примеров.

Все методы для добавления полей именуются по такому принципу `->setИмяПоля`. Идентификаторы полей нужно получать либо по API (`https://www.amocrm.ru/developers/content/crm_platform/custom-fields#custom-fields-list`), либо в браузере в аккаунте AmoCRM с помощью консоли разработчика выловить.

Именования коллекций, моделей и т.п. придерживаются такой же логики, что и методов, т.е. если вам нужно работать с текстовым (text) доп. полем, то модель значений, например, будет иметь имя `TextCustomFieldValuesModel`. У примечаний такая же логика.

Вам нужно выполнить последовательность действий:
1. Добавить контакт (возможные поля описаны здесь [https://www.amocrm.ru/developers/content/crm_platform/contacts-api#contacts-add](https://www.amocrm.ru/developers/content/crm_platform/contacts-api#contacts-add))
```
//Создадим контакт
$contact = new ContactModel();
$contact->setName('Example');
try {
    $contactModel = $apiClient->contacts()->addOne($contact);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

2. Добавить сделку (возможные поля описаны здесь [https://www.amocrm.ru/developers/content/crm_platform/leads-api#leads-add](https://www.amocrm.ru/developers/content/crm_platform/leads-api#leads-add)). Для дополнительные полей есть отдельное описание: [https://www.amocrm.ru/developers/content/crm_platform/custom-fields#cf-types](https://www.amocrm.ru/developers/content/crm_platform/custom-fields#cf-types)
```
//Создадим сделку с заполненым полем типа текст
$lead = new LeadModel();

// Здесь описывается добавление дополнительных полей
// Такую методику можно использовать и в контактах
$leadCustomFieldsValues = new CustomFieldsValuesCollection();
$textCustomFieldValueModel = new TextCustomFieldValuesModel();
$textCustomFieldValueModel->setFieldId(269303);
$textCustomFieldValueModel->setValues(
    (new TextCustomFieldValueCollection())
        ->add((new TextCustomFieldValueModel())->setValue('Текст'))
);
$leadCustomFieldsValues->add($textCustomFieldValueModel);
$lead->setCustomFieldsValues($leadCustomFieldsValues);
$lead->setName('Example');

$leadsCollection = new LeadsCollection();
$leadsCollection->add($lead);
try {
    $lead = $leadsService->addOne($lead);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

3. Связать контакт со сделкой
```
//Получим контакт по ID, сделку и привяжем контакт к сделке
try {
    $contact = $apiClient->contacts()->getOne(7143559); // Вместо этого можно использовать уже имеющуюся модель контакта
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
$links = new LinksCollection();
$links->add($contact);
try {
    $apiClient->leads()->link($lead, $links);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

4. Добавить примечание, указывая в качестве `entity_id` идентификатор сделки (или контакта). Для каждого примечания существуют разные типы, список здесь: [https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#notes-types](https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#notes-types).
```
//Создадим примечания
$notesCollection = new NotesCollection();
$serviceMessageNote = new ServiceMessageNote();
$serviceMessageNote->setEntityId(1)
    ->setText('Текст примечания')
    ->setService('Api Library')
    ->setCreatedBy(0);

$callInNote = new CallInNote(); // Вот здесь необходимо объявлять тот тип, который вам нужен, выше ссылка, названия классов для каждого типа по такой логике ИмяТипаNote
$callInNote->setEntityId(1)
    ->setPhone('+7912312321')
    ->setCallStatus(CallNote::CALL_STATUS_SUCCESS_CONVERSATION)
    ->setCallResult('Разговор состоялся')
    ->setDuration(148)
    ->setUniq(Uuid::uuid4())
    ->setSource('integration name')
    ->setLink('https://example.test/test.mp3');

$smsNote = new SmsOutNote();
$smsNote->setEntityId(1)
    ->setText('Исходящее SMS')
    ->setPhone('+7912312321')
    ->setCreatedBy(0);

$notesCollection->add($serviceMessageNote);
$notesCollection->add($smsNote);
$notesCollection->add($callInNote);

try {
    $leadNotesService = $apiClient->notes(EntityTypesInterface::LEADS);
    $notesCollection = $leadNotesService->add($notesCollection);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

5. Добавить задачу (возможные поля описаны здесь: [https://www.amocrm.ru/developers/content/crm_platform/tasks-api#tasks-add](https://www.amocrm.ru/developers/content/crm_platform/tasks-api#tasks-add))
```
//Создадим задачу
$tasksCollection = new TasksCollection();
$task = new TaskModel();
$task->setTaskTypeId(TaskModel::TASK_TYPE_ID_CALL)
    ->setText('Новая задач')
    ->setCompleteTill(mktime(10, 0, 0, 10, 3, 2020))
    ->setEntityType(EntityTypesInterface::LEADS)
    ->setEntityId(1)
    ->setDuration(30 * 60 * 60) //30 минут
    ->setResponsibleUserId(123);
$tasksCollection->add($task);

try {
    $tasksCollection = $apiClient->tasks()->add($tasksCollection);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

**Comment by i4j5** [comment]
Подскажите как добавить email и телефон к контакту

**Comment by nomelodic** [comment]
Телефон и Email являются дополнительными полями. В примерах рассмотрен вариант с добавлением телефона:
```
//Получим один контакт и добавим ему значение поля телефон
try {
    $contact = $apiClient->contacts()->getOne(3); // Здесь указывается ID контакта
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

//Получим коллекцию значений полей контакта
$customFields = $contact->getCustomFieldsValues();
//Получим значение поля по его коду
$phoneField = $customFields->getBy('fieldCode', 'PHONE'); // Для Email здесь будет код EMAIL

//Если значения нет, то создадим новый объект поля и добавим его в коллекцию значений
if (empty($phoneField)) {
    $phoneField = (new MultitextCustomFieldValuesModel())->setFieldCode('PHONE'); // Для Email здесь будет код EMAIL
    $customFields->add($phoneField);
}

//Установим значение поля
$phoneField->setValues(
    (new MultitextCustomFieldValueCollection())
        ->add(
            (new MultitextCustomFieldValueModel())
                ->setEnum('WORKDD')
                ->setValue('+79123')
        )
);

//Сохраним контакт
try {
    $apiClient->contacts()->updateOne($contact);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

**Comment by SiteMD** [comment]
//Создадим контакт
$contact = new ContactModel();
$contact->setName('Example');
try {
    $contactModel = $apiClient->contacts()->addOne($contact);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

//Получим коллекцию значений полей контакта
$customFields = $contact->getCustomFieldsValues();
//Получим значение поля по его коду
$phoneField = $customFields->getBy('fieldCode', 'PHONE'); // Для Email здесь будет код EMAIL

//Если значения нет, то создадим новый объект поля и добавим его в коллекцию значений
if (empty($phoneField)) {
    $phoneField = (new MultitextCustomFieldValuesModel())->setFieldCode('PHONE'); // Для Email здесь будет код EMAIL
    $customFields->add($phoneField);
}

//Установим значение поля
$phoneField->setValues(
    (new MultitextCustomFieldValueCollection())
        ->add(
            (new MultitextCustomFieldValueModel())
                ->setEnum('WORKDD')
                ->setValue('+79123')
        )
);

//Сохраним контакт
try {
    $apiClient->contacts()->updateOne($contact);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

**PHP Fatal error:  Uncaught Error: Call to a member function getBy() on null**

**Comment by SiteMD** [comment]
> $phoneField = (new MultitextCustomFieldValuesModel())->setFieldCode('PHONE'); // Для Email здесь будет код EMAIL

`//Создадим контакт
$contact = new ContactModel();
$contact->setName('Example');

//Создадим коллекцию полей сущности
$customFields = new CustomFieldsValuesCollection();
//Создадим модель значений поля типа текст
$phoneField = new MultitextCustomFieldValuesModel();
//Укажем ID поля
$phoneField->setFieldCode('PHONE');
//Добавим значения
$phoneField->setValues(
    (new MultitextCustomFieldValueCollection())
        ->add(
            (new MultitextCustomFieldValueModel())
            ->setEnum('WORKDD')
            ->setValue('+79123')
         )
);
//Добавим значение в коллекцию полей сущности
$customFields->add($phoneField);
//Установим сущности эти поля
$contact->setCustomFieldsValues($customFields);

try {
   $contactModel = $apiClient->contacts()->addOne($contact);
} catch (AmoCRMApiException $e) {
   printError($e);
   die;
}
`

Рабочий пример, но все таки почему функция getBy() вызывает error не выяснил

**Comment by nomelodic** [comment]
> Рабочий пример, но все таки почему функция getBy() вызывает error не выяснил

Здесь скорее всего из-за того, что я копировал куски кода из примера, но из разных частей. Не посмотрел на переменные. И вместо `$contact` для вызова `getCustomFieldsValues()` в данном случае нужно было использовать `$contactModel`, т.к. именно он содержит информацию об уже добавленном контакте и, соответственно, о возможных доп. полях.

В вашем примере сработало, потому что вместо получения имеющихся полей (которых нет, и поэтому появляется ошибка, где говориться, что вы пытаетесь вызвать `getBy()` из `null`), вы создаёте новые.

Старый код (здесь `$contact` не содержит в себе информации о доп. полях):
```
$contactModel = $apiClient->contacts()->addOne($contact);
$customFields = $contact->getCustomFieldsValues();
```

Новый код:
```
$contactModel = $apiClient->contacts()->addOne($contact);
$customFields = $contactModel->getCustomFieldsValues();
```

Всё же библиотека написана хорошо, но документации ей явно не хватает. А с документацией на сайте амо, к сожалению, не всё так очевидно(

**Comment by RonnyXD** [comment]
> //Создадим контакт
> $contact = new ContactModel();
> $contact->setName('Example');
> 
> //Создадим коллекцию полей сущности
> $customFields = new CustomFieldsValuesCollection();
> //Создадим модель значений поля типа текст
> $phoneField = new MultitextCustomFieldValuesModel();
> //Укажем ID поля
> $phoneField->setFieldCode('PHONE');
> //Добавим значения
> $phoneField->setValues(
>     (new MultitextCustomFieldValueCollection())
>         ->add(
>             (new MultitextCustomFieldValueModel())
>             ->setEnum('WORKDD')
>             ->setValue('+79123')
>          )
> );
> //Добавим значение в коллекцию полей сущности
> $customFields->add($phoneField);
> //Установим сущности эти поля
> $contact->setCustomFieldsValues($customFields);
> 
> try {
>    $contactModel = $apiClient->contacts()->addOne($contact);
> } catch (AmoCRMApiException $e) {
>    printError($e);
>    die;
> }

 Всем доброго времени суток, разбирал этот вариант, учитывая комментарии выше, да и все примеры пробовал, не получается, Подскажите, может у кого то получилось сделать рабочий вариант? Не могу разобраться. Подскажите пожалуйста. 3-ий день пытаюсь, и всё ругается на Error: Call to a member function getBy() on null. Заранее благодарен

**Comment by GERAunits** [comment]
Все заточено на платную поддержку(
