### ISSUE TITLE
Вопросы по примечаниям с типом attachment

### ISSUE THREAD

**Issue by nomelodic** [amocrm/amocrm-api-php#132]
Обратил внимание на довольно внушительный список типов примечаний в `AmoCRM\Models\Factories\NoteFactory`, среди которых есть в том числе и `public const NOTE_TYPE_CODE_ATTACHMENT = 'attachment'`. В это же время в официальной документации данный тип в список возможных не входит.

Если делать запрос, например, `$client->notes('leads')->getByParentId(123)`, то, если в сделке присутствуют примечания с вложениями, они вернутся в списке. Среди параметров, которые возвращаются для этого типа примечаний, есть только `attachment` и `original_name`. По параметру `attachment` можно получить файл, сформировав предварительно ссылку вида `'https://' . $subdomain . '.amocrm.ru/download/' . $attachment`.

Теперь сами вопросы:
1. Помимо получения предусмотрено ли функционалом библиотеки создание примечаний с типом `attachment` или методы `setAttachment()` и `setOriginalName()` в модели созданы, т.к. есть соответствующие геттеры? 
2. Если предусмотрено, то каким образом можно осуществить непосредственно загрузку файла на сервера AmoCRM, чтобы было к чему устанавливать параметр `attachment`?

**Comment by bessudnov** [comment]
Создание примечаний данного типа в данный момент недоступно через API
