### ISSUE TITLE
Добавление поддержки Laravel 8

### ISSUE THREAD

**Issue by rnixik** [amocrm/amocrm-api-php#134]
Сейчас требование пакета выглядит так `"illuminate/support": "5.* || 6.* || 7.*"`, что не позволяет использовать библиотеку вместе с Laravel 8

**Comment by rnixik** [comment]
https://github.com/amocrm/amocrm-api-php/pull/135

**Comment by bessudnov** [comment]
Приняты правки, в ближайшем релизу будут

**Comment by BoShurik** [comment]
@bessudnov может имеет смысл отказаться от этой зависимости? Судя по всему она используется только для конвертации в PascalCase и интерфейса Arrayable, который нигде не используется.
В не-laravel проекте этот пакет выглядит странным :)
