### ISSUE TITLE
Невозможно установить библиотеку в проект, где тянется guzzle 7.*

### ISSUE THREAD

**Issue by goale** [amocrm/amocrm-api-php#137]
В частности свежий Laravel 8 тянет за собой зависимость guzzle 7
![image](https://user-images.githubusercontent.com/4661017/93244376-4dc0fa80-f792-11ea-9c5d-5307685f3264.png)

В composer.json библиотеки же указано
```
"guzzlehttp/guzzle": "6.*"
```

**Comment by bessudnov** [comment]
принял реквест, в ближайшем релизе будет

**Comment by PHPTCloud** [comment]
Надеюсь поддержка для новых версий guzzle будет включена в след релизе. Но временно можно сделать так:
```
// composer.json в папке проекта laravel
...
"require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "6.* || 7.*",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "amocrm/amocrm-api-library": "^0.3.1"
    },
...
```
