### ISSUE TITLE
Ошибка при попытке вызова ContactModel->toArray()

### ISSUE THREAD

**Issue by RomanMazyrin** [amocrm/amocrm-api-php#14]
Вот такой кусок кода:

```
$newContact = new ContactModel();
$newContact
    ->setName($name)
    ->setResponsibleUserId(123)
    ->setCustomFieldsValues($customFieldsCollection);
var_dump($newContact->toArray());
```

Возникает ошибка:

`Exception 'TypeError' with message 'Return value of AmoCRM\Models\ContactModel::getCustomers() must be an instance of AmoCRM\Collections\Customers\CustomersCollection, null returned'`

Вот stacktrace небольшой:

```
Exception 'TypeError' with message 'Return value of AmoCRM\Models\ContactModel::getCustomers() must be an instance of AmoCRM\Collections\Customers\CustomersCollection, null returned'

in /Users/romanmazyrin/PhpstormProjects/mazdata/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/ContactModel.php:452

Stack trace:
#0 /Users/romanmazyrin/PhpstormProjects/mazdata/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/ContactModel.php(618): AmoCRM\Models\ContactModel->getCustomers()
#1 /Users/romanmazyrin/PhpstormProjects/mazdata/models/AmocrmCustomIntegrations/DeltasalesIntegration.php(136): AmoCRM\Models\ContactModel->toArray()
```

Там очевидно, что интерпретатор ругается на возврат null вместо указанного типа, ведь при построении контакта поле customers я не трогаю и оно остается null.

Вот проблемный код:

[Файл ContactModel.php](https://github.com/amocrm/amocrm-api-php/blob/master/src/AmoCRM/Models/ContactModel.php), строка 452
```
/**
     * @return CustomersCollection
     */
    public function getCustomers(): CustomersCollection
    {
        return $this->customers;
    }
```

**Comment by bessudnov** [comment]
Ага, точно бага)
должно быть ?CustomersCollection

ближе к ночи поправлю или с утра завтра

**Comment by bessudnov** [comment]
Исправлено в релизе 0.2.3
