### ISSUE TITLE
Примечание сущности (notes). Как получить его без купюр? 

### ISSUE THREAD

**Issue by ginterbin** [amocrm/amocrm-api-php#140]
Пытаюсь получить примечание сущности сделки:

$leadNotesService = $apiClient->notes(EntityTypesInterface::LEADS);
$leadId = 1234569;
$notesCollection = $leadNotesService->getByParentId($leadId);
var_dump($notesCollection);

 - в дампе отсутствует блоки "params": {} и "note_type": 
Хотя при обращении к апи из броузера:
https://myaccaunt.amocrm.ru/api/v4/leads/1234569/notes
во всех notes блоки "params": {} и "note_type":  присутствуют.

И если обратиться к апи таким образом:
$response = $request->get('https://myaccaunt.amocrm.ru/api/v4/leads/1234569/notes);
во всех notes блоки "params": {} и "note_type":  присутствуют.

Как можно получить полную информацию о notes с помощью  $apiClient->notes() ?
ЗЫ: никаких with в модели Notes не предусмотрено:
/**
 * Class NoteModel
 *
 * @package AmoCRM\Models
 */
...
    /**
     * @return array
     */
    public static function getAvailableWith(): array
    {
        return [];
    }

**Comment by bessudnov** [comment]
params и note_type нет в моделях

под каждый тип примечания есть отдельная модель данных, которая зависит от note_type
params так же раскрываются в свойства моделей

модели доступны в директории /src/AmoCRM/Models/NoteType
фабрика моделей, которая вызывается при получении данных из API:
\AmoCRM\Models\Factories\NoteFactory::createForType
