### ISSUE TITLE
NextPage: Как изменить offset (limit_rows)?

### ISSUE THREAD

**Issue by FrontEndTCloud** [amocrm/amocrm-api-php#145]
```
    $leadsFilter = new LeadsFilter();
    $leadsFilter->setPage(2);

    $leads = $amoApiClient->leads($leadsFilter)->get();
```

Хочу получить следующую страницу. Пример того, как пытался выше. Подскажите как с offset-ом работать. Спасибо.

**Comment by FrontEndTCloud** [comment]
Нашел вот такое решение:
```
$leads = $amoApiClient->leads()->get();
$amoApiClient->leads()->nextPage($leads);
```
Но я не хочу странички перебирать, а хочу сразу нужную получить.

**Comment by nomelodic** [comment]
У вас в первом варианте вероятно ошибка:
`$leads = $amoApiClient->leads($leadsFilter)->get();`

Метод `leads()` не принимает аргументов, поэтому в него нельзя передать фильтр. А вот метод `get()` как раз с фильтром и работает: `@method LeadsCollection get(BaseEntityFilter $filter = null, array $with = []) : ?LeadsCollection`

Попробуйте выполнить код в таком виде:
`$leads = $amoApiClient->leads()->get($leadsFilter);`

**Comment by FrontEndTCloud** [comment]
> У вас в первом варианте вероятно ошибка:
> `$leads = $amoApiClient->leads($leadsFilter)->get();`
> 
> Метод `leads()` не принимает аргументов, поэтому в него нельзя передать фильтр. А вот метод `get()` как раз с фильтром и работает: `@method LeadsCollection get(BaseEntityFilter $filter = null, array $with = []) : ?LeadsCollection`
> 
> Попробуйте выполнить код в таком виде:
> `$leads = $amoApiClient->leads()->get($leadsFilter);`

Спасибо.
