### ISSUE TITLE
Change product in AMO

### ISSUE THREAD

**Issue by AlexanderKopyl** [amocrm/amocrm-api-php#148]
Добрый день .. Подскажите пожалуйста .. Как можно поменять поле в товаре .. Который уже занесен в Амо?

**Comment by bessudnov** [comment]
Вы можете посмотреть примеры в папке examples.
examples/catalogs_elements_actions.php - пример работы с элементами каталогов (товары - частный случай каталога)
Пример по работе с полями доступ тут examples/leads_actions.php

**Comment by Mausina** [comment]
Так себе примеры если честно .. Лучше бы документация была ..

**Comment by bessudnov** [comment]
Записал в бэклог, чтобы расширить примеры по полям каталогов
Но по сути поля сущностей и каталогов работают через единый механизм

**Comment by AlexanderKopyl** [comment]
Понял .. Тестируем =)
