### ISSUE TITLE
getAccessTokenByCode не корректно работает.

### ISSUE THREAD

**Issue by DutiFruti** [amocrm/amocrm-api-php#150]
Столкнулся с необходимостью получить токен по коду. Есть метод getAccessTokenByCode у AmoCRMOAuth, который использует для формирования запроса PostAuthOptionProvider из league пакета. Который отправляет в формате application/x-www-form-urlencoded. В то время как API хочет в JSON. Хотел переопределить OptionProvider, тк библиотека поваляет это, но нет метода достучаться до oauthProvider для того чтоб выполнить  setOptionProvider.
В итоге я получаю ошибку:

`{
    "title": "Некорректный клиент",
    "type": "https://developers.amocrm.ru/v3/errors/OAuthProblemJson",
    "status": 401,
    "detail": "Авторизация клиента не прошла"
}`

**Comment by bessudnov** [comment]
Вообще API принимает как application/json, так и application/x-www-form-urlencoded
Точно ли все параметры верные? Совпадает ли redirect_uri полностью, вплоть до последнего слэша?

**Comment by DutiFruti** [comment]
Видимо вы правы, когда я пытался через JSON, я вставлял другой url. По ошибке сразу не заподозрил что дело в url. Думаю вопрос можно закрывать. Спасибо. 

П.С. Если будет возможности, сделайте, пожалуйста, ошибки более информативными :)
