### ISSUE TITLE
Поменять значения поля.

### ISSUE THREAD

**Issue by AlexanderKopyl** [amocrm/amocrm-api-php#155]
Поле в товаре есть но пустое .. То есть NUll .. Как присвоить ему значение?

**Comment by bessudnov** [comment]
Можете предоставить более подробное описание вопроса?
Примера кода, какое запрос делаете, какое ответ приходит?
Установить значения полей можно по описанию в этом разделе https://github.com/amocrm/amocrm-api-php#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8F%D0%BC%D0%B8-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9
