### ISSUE TITLE
Добавление контакта вместе со сделкой (без линковки)

### ISSUE THREAD

**Issue by Romik90** [amocrm/amocrm-api-php#159]
Увидел метод setContacts у экземпляра класса LeadModel. Попробовал создать сделку, создалась без контакта

![image](https://user-images.githubusercontent.com/17782452/95477464-098bd900-0991-11eb-8140-50a992c8287e.png)

Как создать сделку сразу с прикрепленным контактом, без линковки?

**Comment by nomelodic** [comment]
Скорее всего никак. В старой версии API, насколько я помню, была такая возможность. В текущей версии в официальной документации связь описывается отдельно [https://www.amocrm.ru/developers/content/crm_platform/entity-links-api](https://www.amocrm.ru/developers/content/crm_platform/entity-links-api), а у самих объектов нет никаких параметров, которые за это отвечают.

Метод `setContacts` у `LeadModel` скорее всего работает в паре с `getContacts`. Нужны они для того, чтобы при получении сделки отдавать дополнительно связанные контакты (когда в запросе передавался параметр `with` или уже после получения сделки отдельным запросом). В примерах есть такой код с использованием `getContacts`:
```
//Получим основной контакт сделки
/** @var ContactsCollection $leadContacts */
$leadContacts = $lead->getContacts();
if ($leadContacts) {
    $leadMainContact = $leadContacts->getBy('isMain', true);
}
```

А в самом `LeadModel` метод `setContacts` используется в таком виде:
```
if (!empty($lead[AmoCRMApiRequest::EMBEDDED][self::CONTACTS])) {
    $contactsCollection = new ContactsCollection();
    $contactsCollection = $contactsCollection->fromArray($lead[AmoCRMApiRequest::EMBEDDED][self::CONTACTS]);
    $leadModel->setContacts($contactsCollection);
}
```

Оба метода работают с одной и той же переменной.
Но я могу ошибаться, поэтому давайте подождём ответа разработчиков.

**Comment by bessudnov** [comment]
В данный момент одним запросом это сделать нельзя, но мы рассмотрим возможность добавить эту возможность

**Comment by Romik90** [comment]
Очень жду эту возможность

**Comment by Romik90** [comment]
Очень жду эту возможность, а так же возможность сразу прикреплять комментарий к сделке, без линковки, иначе теряется всё преимущество пакетной загрузки сделок

**Comment by bessudnov** [comment]
Задача в плане есть, чтобы можно было через API добавлять сделки с указанием id контактов и компании, но по срокам информации пока что нет.

**Comment by Romik90** [comment]
> Задача в плане есть, чтобы можно было через API добавлять сделки с указанием id контактов и компании, но по срокам информации пока что нет.

есть новости?

**Comment by bessudnov** [comment]
О сроках не можем сказать, но задача всё еще в плане, в бэклог не ушла

**Comment by RodionovSlsUp** [comment]
@bessudnov а есть ли в открытом доступе список задач с сроками? Очень круто, если была бы возможность ориентироваться, что будет добавлено в ближайшее время, а что нет. В качестве примера, у меня клиент прождал два месяца добавления в тестирование нового апи фильтрации, но так ответ и не пришел (хотя мы входим в топ 10 интеграторов). Задача была получать сделки с определенного этапа. В результате реализовалась костылем из второй версии апи. Было бы здорово понимать, какие инструменты будут в ближайшее время, что бы ориентироваться по реализации.

**Comment by bessudnov** [comment]
В API подобную функциональность добавили в конце декабря
В ближайшее время обновим документацию и захватим изменение в библиотеку

**Comment by bessudnov** [comment]
> @bessudnov а есть ли в открытом доступе список задач с сроками? Очень круто, если была бы возможность ориентироваться, что будет добавлено в ближайшее время, а что нет. В качестве примера, у меня клиент прождал два месяца добавления в тестирование нового апи фильтрации, но так ответ и не пришел (хотя мы входим в топ 10 интеграторов). Задача была получать сделки с определенного этапа. В результате реализовалась костылем из второй версии апи. Было бы здорово понимать, какие инструменты будут в ближайшее время, что бы ориентироваться по реализации.

К вашему сожалению, открытого списка задач нет, а по срокам не можем точно ориентировать в том числе из-за того, что могут появляться задачи, которые являются аварийными или более приоритетными. Не хочется подводить клиентов и партнеров, когда мы говорим, что через 2 недели будет решение, а выпускаем его только через 4.

**Comment by bessudnov** [comment]
Добавили возможность при создании сделки передать ID контактов и компании для привязки
https://github.com/amocrm/amocrm-api-php/compare/0.4.1...0.4.3#diff-bba8242183515cfde63f35772c47da714eb26416aff06652106bfa2364a968c0
