### ISSUE TITLE
Refresh access token event doesn't work

### ISSUE THREAD

**Issue by silenseram** [amocrm/amocrm-api-php#161]
Some code like this does not work as expected

```
$apiClient->onAccessTokenRefresh(function ($accessToken, $baseDomain) {
    //some refresh logic, like saving to database
});
```
We are expect, that this callback fired when we get a new access token (doesn't matter we force it or system do it automatically), but it doesn't. If we want to handle updating our token, we need to use this
```
$apiClient->getOAuthClient()->setAccessTokenRefreshCallback(function ($accessToken, string $baseDomain) {
    //some refresh logic, like saving to database;
});
```
First case show'n in main page of documentation

**Comment by bessudnov** [comment]
Please, send us some examples how you are using library.
If you are using services to get data, callback will be set on building request object
https://github.com/amocrm/amocrm-api-php/blob/c8e10640441a242276722e93ea5f775fb136d1ed/src/AmoCRM/Client/AmoCRMApiClient.php#L130

**Comment by buryabuha** [comment]
Check to see if the reason is the same
#246
