### ISSUE TITLE
Как добавить к запросу заголовок If-Modified-Since

### ISSUE THREAD

**Issue by naur1970** [amocrm/amocrm-api-php#162]
В документации к АПИ на странице https://www.amocrm.ru/developers/content/api/recommendations рекомендовано использовать заголовок If-Modified-Since для получения "недавно обновленных сущностей". Но мне не удается найти как можно его (заголовок) указать при использовании этой стандартной библиотеки. Поиск в исходном коде показал, что например метод AmoCRM\EntitiesServices\BaseEntity::get() принимает два параметра и внутри себя вызывает метод AmoCRM\Client\AmoCRMApiRequest::get(), который третьим параметром ожидает заголовки. Но передать их туда невозможно. Возможно предусмотрен какой то иной способ получить список сущностей, которые были обновлены после некоторой метки времени..

**Comment by DenisKor2208** [comment]
+

**Comment by tonnedo** [comment]
Есть фильтр для диапазона, например по времени изменения сущности

$range = new BaseRangeFilter();
$range->setFrom(1605076866);
$range->setTo(1605078444);

$filter = new LeadsFilter();
$filter->setUpdatedAt($range);

$leads = $apiClient->leads()->get($filter);
