### ISSUE TITLE
TypeError при получении списка примечаний сделки

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#167]
При вызове EntityNotes->nextPage($collection) словил TypeError
> TypeError: Argument 1 passed to AmoCRM\Models\NoteType\CallNote::setUniq() must be of the type string or null, array given, called in /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/NoteType/CallNote.php on line 51 and defined in /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/Traits/CallTrait.php:56
Stack trace:
#0 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/NoteType/CallNote.php(51): AmoCRM\Models\NoteType\CallNote->setUniq(Array)
#1 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/Factories/NoteFactory.php(79): AmoCRM\Models\NoteType\CallNote->fromArray(Array)
#2 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Collections/NotesCollection.php(40): AmoCRM\Models\Factories\NoteFactory::createForType('call_in', Array)
#3 [internal function]: AmoCRM\Collections\NotesCollection::AmoCRM\Collections\{closure}(Array)
#4 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Collections/NotesCollection.php(39): array_map(Object(Closure), Array)
#5 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(105): AmoCRM\Collections\NotesCollection::fromArray(Array)
#6 /app/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/Traits/PageMethodsTrait.php(40): AmoCRM\EntitiesServices\BaseEntity->createCollection(Array)

 Пока ошибка воспроизводилась, успел в NoteFactory->createForType перед вызовом fromArray дампнуть содержимое $note: по какой-то причине в $note['params']['uniq'] содержался пустой массив

Среда:
amocrm-api-library 0.3.13
php 7.3

**Comment by bessudnov** [comment]
Вероятно битый звонок, добавим в библиотеку обработку подобного кейса

**Comment by bessudnov** [comment]
Исправление выпущено в релизе 0.3.14
