### ISSUE TITLE
Неверное оформление @method

### ISSUE THREAD

**Issue by eugene-borovov** [amocrm/amocrm-api-php#168]
Возвращаемый тип оформлен после параметров, а перед названием метода класс, к которому принадлежит метод (вроде правильно понял задумку).

Но нужно возвращаемый тип писать перед названием метода в теге ([см. документацию](https://docs.phpdoc.org/latest/guide/references/phpdoc/tags/method.html))
Это влияет на подсказки IDE и на анализаторы кода.

Для примера:
`* @method BaseCustomFieldValuesModel getBy($key, $value) : ?BaseApiModel` -- понимается IDE как всегда nonNull BaseCustomFieldValuesModel и анализаторы кода ругаются на лишние проверки на NULL

Должно быть так:
`* @method BaseCustomFieldValuesModel|null getBy($key, $value)  описание метода`
или так
`* @method BaseApiModel|null getBy($key, $value) описание метода`

**Comment by bessudnov** [comment]
В будущих релизах учтем, спасибо

**Comment by eugene-borovov** [comment]
Спасибо
