### ISSUE TITLE
Как удалять объекты через API

### ISSUE THREAD

**Issue by eugene-borovov** [amocrm/amocrm-api-php#174]
Как можно удалить объекты с помощью API? Не нашёл такого метода.
Порой очень полезно подчистить за собой следы неудачной транзакции.

**Comment by bessudnov** [comment]
К сожалению, удаление недоступно через API

**Comment by vodnicearv** [comment]
а планируеться добавить такую возможность в будущем?

**Comment by vodnicearv** [comment]
@bessudnov все еще не планируется реализовать удаление через API?
