### ISSUE TITLE
Обновите league/oauth2-client

### ISSUE THREAD

**Issue by eugene-borovov** [amocrm/amocrm-api-php#175]
Обновите, пожалуйста, league/oauth2-client, чтобы можно было пользоваться  guzzlehttp/guzzle ^7.0.  А то как-то странно, что amocrm/amocrm-api-library позволяет, а зависимость нет. Тем более, что league/oauth2-client 2.5 по сути только разрешает guzzle7, а 2.6  -- только тестовые инструменты.

```
composer why --tree  guzzlehttp/guzzle
guzzlehttp/guzzle 6.5.5 Guzzle is a PHP HTTP client library
+--amocrm/amocrm-api-library 0.3.15 (requires guzzlehttp/guzzle 6.* || 7.*)
L--league/oauth2-client 2.4.1 (requires guzzlehttp/guzzle ^6.0)
   L--amocrm/oauth2-amocrm 2.0.5 (requires league/oauth2-client 2.4.*)
      L--amocrm/amocrm-api-library 0.3.15 (requires amocrm/oauth2-amocrm ^2.0)
```

**Comment by bessudnov** [comment]
Обновление для amocrm/oauth2-amocrm доступно, добавлена поддержка league/oauth2-client 2.5

**Comment by eugene-borovov** [comment]
Спасибо
