### ISSUE TITLE
Звонки виджетов

### ISSUE THREAD

**Issue by rmkrylov** [amocrm/amocrm-api-php#177]
Добрый день. У лида есть звонки, которые совершали через манго и uis. Их можно как то получить по апи?
Через этот способ не выводятся, в линках тоже их нет, подскажите куда капать?

`$notesCollection = $leadNotesService->getByParentId(id, (new NotesFilter())->setNoteTypes([NoteFactory::NOTE_TYPE_CODE_CALL_IN]));`

**Comment by bessudnov** [comment]
в id передается ID сделки?

можете предоставить вывод для подробного разбора?
$leadNotesService->getLastRequestInfo()

**Comment by rmkrylov** [comment]
`"data":{"Error":"No content","Code":204,"DebugInfo":{"last_http_method":"GET","last_method":"https:\/\/*.amocrm.ru\/api\/v4\/leads\/32229816\/notes","last_body":[],"last_query_params":{"filter":{"note_type":["call_in"]},"limit":50,"page":1},"last_response":"","last_response_code":204,"last_request_id":"299d361dfe220c531a51cbcbe216e301","jquery_call":"\n$.ajax({\n    url: \"https:\/\/*.amocrm.ru\/api\/v4\/leads\/32229816\/notes?filter%5Bnote_type%5D%5B0%5D=call_in&limit=50&page=1\",\n    data: JSON.stringify([]),\n    type: \"GET\",\n    contentType: \"application\/json\"\n});","curl_call":"curl \"https:\/\/*.amocrm.ru\/api\/v4\/leads\/32229816\/notes?filter%5Bnote_type%5D%5B0%5D=call_in&limit=50&page=1\" -X \"GET\" -d\"\"","timestamp":1605685028}}`

Если в запросе
`$notesCollection = $leadNotesService->getByParentId($lead->id, (new NotesFilter())->setNoteTypes([NoteFactory::NOTE_TYPE_CODE_CALL_IN]));`
убрать фильтр то выводятся текстовое и смс примечание.
https://yadi.sk/i/G1kYFA4L15gsFg

Сам лид
https://yadi.sk/i/rUAptlVqAbEZ7Q

**Comment by bessudnov** [comment]
А точно звонок прикреплен к сделке?
Очень часто телефонии добавляют звонки к привязанному контакту

**Comment by rmkrylov** [comment]
Да, привязаны к контакту, спасибо.
