### ISSUE TITLE
Как создать товары и внести их в AmoCRM

### ISSUE THREAD

**Issue by MiXALK** [amocrm/amocrm-api-php#185]
Добрый день. Есть ли возможность добавления товаров в AmoCRM посредствам api? В классе Products нашёл комментарий "Для работы с API товаров, есть только методы настроек". ProductsСollection отсутствует по аналогии с другими энтити. Все традиционные методы типа get, getOne, add, addOne и т.д. бросают исключение "Method not available for this entity". Это планируется к добавлению в новых версиях, или не планируется вообще?
 Во всех issues удалось найти только https://github.com/amocrm/amocrm-api-php/issues/148, который порадил ещё больше вопросов. С товарами в текущем api (v 0.3.18.2) нужно работать как с CatalogElementModel? Если, да то выходит обязательно нужно создать какой-нибудь каталог?

**Comment by bessudnov** [comment]
Товары - это частный случай каталогов с предустановленными полями, при включении товаров в amoCRM - каталог товаров будет создан автоматически
