### ISSUE TITLE
Не могу применить ни один пример для получения сделок, а при обновлении страницы вообще пишет ошибку авторизации

### ISSUE THREAD

**Issue by Kordak** [amocrm/amocrm-api-php#191]
Ошибка:
Fatal error: Uncaught Error: Call to a member function leads() on null in /home/host1749169/host1749169.hostland.pro/htdocs/www/test_amo/index.php
код: 

include_once ('/home/host1749169/vendor/autoload.php');
include_once ('/home/host1749169/vendor/amocrm/oauth2-amocrm/src/AmoCRM.php');

use AmoCRM\Collections\ContactsCollection;
use AmoCRM\Collections\CustomFieldsValuesCollection;
use AmoCRM\Collections\Leads\LeadsCollection;
use AmoCRM\Collections\LinksCollection;
use AmoCRM\Collections\NullTagsCollection;
use AmoCRM\Exceptions\AmoCRMApiException;

use AmoCRM\Filters\BaseRangeFilter;
use AmoCRM\Filters\LeadsFilter;

use AmoCRM\Models\CustomFieldsValues\TextCustomFieldValuesModel;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\NullCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\TextCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueModels\TextCustomFieldValueModel;
use AmoCRM\Models\LeadModel;
use League\OAuth2\Client\Token\AccessTokenInterface;

use AmoCRM\OAuth2\Client\Provider\AmoCRM;

(тут код авторизации с кнопкой)

$leadsService = $apiClient->leads();

//Получим сделки и следующую страницу сделок
try {
    $leadsCollection = $leadsService->get();
    $leadsCollection = $leadsService->nextPage($leadsCollection);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

ошибка при обновлении страницы:

AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны (Authorization code has been revoked) in /home/host1749169/vendor/amocrm/oauth2-amocrm/src/AmoCRMException.php:28 Stack trace: #0 /home/host1749169/vendor/amocrm/oauth2-amocrm/src/AmoCRM.php(163): AmoCRM\OAuth2\Client\Provider\AmoCRMException::errorResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /home/host1749169/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): AmoCRM\OAuth2\Client\Provider\AmoCRM->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #2 /home/host1749169/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #3 /home/host1749169/host1749169.hostland.pro/htdocs/www/test_amo/index.php(100): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array) #4 {main}

**Comment by denostr** [comment]
В ошибке описана проблема `Authorization code has been revoked`, время действия кода авторизации закончилось

**Comment by MaximBobylev** [comment]
Так же `Authorization code has been revoked` может возвращаться, если интеграция отключена или удалена

**Comment by Kordak** [comment]
> В ошибке описана проблема `Authorization code has been revoked`, время действия кода авторизации закончилось

Мне нужно в итоге научиться без танцев с бубнами получать успешно реализованные по датам из кастомных полей. Вы можете дать мне платную консультацию (со мной добиться получения таких сделок в итоге).
