### ISSUE TITLE
Возможно ли получить общее количество сущностей?

### ISSUE THREAD

**Issue by PHPTCloud** [amocrm/amocrm-api-php#193]
Возможно ли получить общее количество сущностей?
Например, возвать leads() сервис и через итератор получить что-то вроде "totalCount"/"total".

**Comment by bessudnov** [comment]
В данный момент такой опции нет

**Comment by PHPTCloud** [comment]
> В данный момент такой опции нет

Жаль, было бы круто в итератор такие поля добавить как :
- всего сущностей;
- всего страниц;

И исправить генерацию ссылки для страниц в поле nextPageLink, так как даже при отсутствии сущностей на следующей странице генерируется ссылка (некорректная ссылка), из-за который выбрасывается NotContentException...

**Comment by pazakharov** [comment]
У меня постоянно скрипт нарывается на исключение, No content Code: 204, Когда по страницам пытаюсь собирать все сущности в одну коллекцию, в конце генерируется ссылка на следующую страницу, которой нет.  А как вообще можно получить все сущности ?

**Comment by RodionovSlsUp** [comment]
@pazakharov для себя решаю эту проблему последовательным получением страниц, пока не нарвусь на исключение noContent.
Возможно не самое элегантное решение, но при текущих инструментах лучшего не нашел.

Метод получения количества всех сущностей правда очень помог бы. Можно как то оставить заявку на его добавление @bessudnov ?

**Comment by pazakharov** [comment]
Вопрос как раз и стоит в элегантности) Я для этого случая исключение отдельное завел.

**Comment by bessudnov** [comment]
> Метод получения количества всех сущностей правда очень помог бы. Можно как то оставить заявку на его добавление @bessudnov ?


в текущей архитектуре точно не будет добавлен, запишем в бэклог, вероятно получится что-то подобное сделать с включенной альфа-фильтрацией
