### ISSUE TITLE
Поддержка PHP 8.0 (обновление lcobucci/jwt)

### ISSUE THREAD

**Issue by rnixik** [amocrm/amocrm-api-php#194]
Данный пакет невозможно использовать с PHP 8.0 по причине того, что используемая версия `"lcobucci/jwt": "^3.3"` не поддерживает работу с php 8.0. Для решения проблемы следует обновить используемую версию cobucci/jwt до 4.х. Их руководство по обновлению заявляет, что можно внести изменения, при которых будут поддерживаться и 3.x и 4.x версии одновременно:
>However, you can also find here the instructions on how to make your code compatible with both versions.

https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/

**Comment by bessudnov** [comment]
Здравствуйте, проверим, но не раньше 14 декабря

**Comment by eugene-borovov** [comment]
Это сразу задерёт версию PHP до 7.4 для всего проекта. У нас, например, сейчас PHP7.2.
Вероятно придётся авторизацию выносить в виде плагина, чтобы версии реализаций не ограничивали проект.

**Comment by salfum** [comment]
> Здравствуйте, проверим, но не раньше 14 декабря

Здравствуйте, можно обновить lcobucci/jwt и league/oauth2-client для совместимости с PHP 8 ?

**Comment by bessudnov** [comment]
В ближайшем релизе планируем захватить

**Comment by bessudnov** [comment]
в master влили правки, завтра выпустим в релизе

**Comment by bessudnov** [comment]
Поддержка добавлена в релизе 0.4.3
