### ISSUE TITLE
Не работает обновление истекшего токена в базовом примере

### ISSUE THREAD

**Issue by StawR0s** [amocrm/amocrm-api-php#199]
По истечению срока действия токена, onAccessTokenRefresh не срабатывает, в чем дело?

`$accessToken = getToken();

$apiClient->setAccessToken($accessToken)
    ->setAccountBaseDomain($accessToken->getValues()['baseDomain'])
    ->onAccessTokenRefresh(
        function (AccessTokenInterface $accessToken, string $baseDomain) {
            saveToken(
                [
                    'accessToken' => $accessToken->getToken(),
                    'refreshToken' => $accessToken->getRefreshToken(),
                    'expires' => $accessToken->getExpires(),
                    'baseDomain' => $baseDomain,
                ]
            );
        }
    );`

**Comment by streeboga** [comment]
Аналогичный вопрос.
При каких условиях должен сработать коллбэк?
Или всегда при инициализации класса нужно проверять токен и запрашивать его обновление если прошли сутки? - но это тоже не работает, делаю вызов  
$apiClient->getOAuthClient()->getAccessTokenByRefreshToken($accessToken)
пишет ошибку что мало параметров.

Подскажите пожалуйста в чем дело и как нужно с этим всем работать? 
@StawR0s @egorshar @soul-rise @rnixik @MihailovJava 
Извините, что так пингую. Но техподдержка отправила сюда, а вопрос достаточно срочный.
Спасибо)

**Comment by trickwow** [comment]
этот метод срабатывает при обновлении AccessToken, а не по истечении срока какого-либо токена

**Comment by bessudnov** [comment]
Можете уточнить, проблема еще актуальна?

**Comment by buryabuha** [comment]
Проверьте у себя, возможно причина такая же как у нас.
https://github.com/amocrm/amocrm-api-php/issues/246
