### ISSUE TITLE
PHP 7.3 LeadsFilter::setLimit TypeError

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#2]
## Expected Behavior
Вызов setLimit устанавливает значение для свойства limit, возвращает текущий объект

## Current Behavior
При попытке вызова метода setLimit у экземпляра класса LeadsFilter происходит ошибка

> TypeError: Return value of AmoCRM\Filters\LeadsFilter::setLimit() must be an instance of AmoCRM\Filters\Traits\PagesFilterTrait, instance of AmoCRM\Filters\LeadsFilter returned in /.../amocrm/amocrm-api-library/src/AmoCRM/Filters/Traits/PagesFilterTrait.php:44

## Environment
PHP 7.3

**Comment by bessudnov** [comment]
Спасибо за фидбек, в ближайшем релизе подготовим фикс. Думаю в течении недели.

**Comment by bessudnov** [comment]
Исправлено в релизе 0.2
