### ISSUE TITLE
Не возвращается текст примечаний sms_out

### ISSUE THREAD

**Issue by magnum79** [amocrm/amocrm-api-php#203]
API запрос "Получение примечания по ID", как описано здесь: https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#note-detail

Возвращает null для полей text и phone. При этом в CRM эти примечания есть, телефон и текст есть.
Ответ API:
{
    "id": 128244877,
    "entity_id": 8043821,
    "created_by": 0,
    "updated_by": 6275200,
    "created_at": 1523365758,
    "updated_at": 1600430706,
    "responsible_user_id": 6275200,
    "group_id": 0,
    "note_type": "sms_out",
    "params": {
        "text": null,
        "phone": null
    },
    "account_id": 14380216,
    "_links": {
        "self": {
            "href": "https://ourdomain.amocrm.ru/api/v4/leads/8043821/notes/128244877"
        }
    }
}

**Comment by bessudnov** [comment]
А как добавляется SMS?

Похоже, что проблема именно в API и лучше обратиться в техническую поддержку

**Comment by magnum79** [comment]
SMS было добавлено с помощью сервиса sms.ru, это было в 2017 году.
Суть вопроса от этого не меняется. Почему в браузере в карточке сделки текст сообщения есть, а по API его получить нельзя?
Видимо ошибка в API.
Хорошо, я напишу в техподдержку.

**Comment by magnum79** [comment]
По результатам общения с технической поддержкой выяснилось, что запрос вида
/api/v2/notes?type=lead&id=128244877

возвращает объект, с ключами TEXT и PHONE в верхнем регистре. По-видимому api/v4 это не поддерживает.

```{
  "_links": {
    "self": {
      "href": "/api/v2/notes?type=lead&id=128244877",
      "method": "get"
    }
  },
  "_embedded": {
    "items": [
      {
        "id": 128244877,
        "responsible_user_id": 6275200,
        "created_by": 0,
        "created_at": 1523365758,
        "updated_at": 1600430706,
        "account_id": 111,
        "updated_by": 6275200,
        "group_id": 0,
        "is_editable": false,
        "element_id": 8043821,
        "element_type": 2,
        "attachment": null,
        "note_type": 103,
        "params": {
          "TEXT": "Получена оплата за практикум. Доступы к кабинету отправлены вам на email. Связь: info@***.org или тел. 8 800 ***",
          "PHONE": **,
          "HTML": "Исходящее SMS: Получена оплата за практикум. Доступы к кабинету отправлены вам на email. Связь: info@***.org или тел. 8 800 ***"
        },
        "_links": {
          "self": {
            "href": "/api/v2/notes?id=128244877&type=lead",
            "method": "get"
          }
        }
      }
    ]
  }
}```

**Comment by bessudnov** [comment]
Сделаем фикс, а то это не нормальное поведение)
