### ISSUE TITLE
TypeError в методе getAttachCount()

### ISSUE THREAD

**Issue by magnum79** [amocrm/amocrm-api-php#204]
Происходит ошибка при запросе attachCount у примечания с типом amomail_message.

Exception has occurred.
TypeError: Return value of AmoCRM\Models\NoteType\AmoMailMessageNote::getAttachCount() must be of the type int, null returned

Происходит здесь:
https://github.com/amocrm/amocrm-api-php/blob/651294057ae5ca1eaf9e637f75d75f7c7504dc7b/src/AmoCRM/Models/NoteType/AmoMailMessageNote.php#L210

При этом метод toArray() возвращает
Array
(
    [id] => 85835523
    [entity_id] => 9965535
    [note_type] => amomail_message
    [responsible_user_id] => 1451212
    [group_id] => 0
    [created_by] => 1451212
    [updated_by] => 1451212
    [created_at] => 1510824756
    [updated_at] => 1510825140
    [account_id] => 14380216
)

Вызов /api/v4/leads/notes/85835523 в браузере возвращает:
{
    "id": 85835523,
    "entity_id": 9965535,
    "created_by": 1451212,
    "updated_by": 1451212,
    "created_at": 1510824756,
    "updated_at": 1510825140,
    "responsible_user_id": 1451212,
    "group_id": 0,
    "note_type": "amomail_message",
    "params": {
        "thread_id": "32178718",
        "message_id": "54197510",
        "private": true,
        "income": false,
        "from": {
            "email": "****",
            "name": "****"
        },
        "to": {
            "email": "****",
            "name": "****"
        },
        "version": 3
    },
    "account_id": 14380216,
    "_links": {
        "self": {
            "href": "https://****.amocrm.ru/api/v4/leads/9965535/notes/85835523"
        }
    }
}

**Comment by bessudnov** [comment]
Влил, в ближайшем релизе будет этот фикс
