### ISSUE TITLE
Как получить группы пользователей в системе?

### ISSUE THREAD

**Issue by PHPTCloud** [amocrm/amocrm-api-php#208]
Уважаемые разработчики,
как получить группы пользователей через API, которые настраиваются в настройках пользователей?

Вот как я пытался получить список групп, но в обоих случаях "группы" и "роли" пусты. В первом случае только id группы конкретного пользователя(
```
$collection = $this->getApiClient()->users()->get();
// ...
$collection = $this->getApiClient()->roles()->get();
```

**Comment by bessudnov** [comment]
`$this->account->getCurrent([AccountModel::USER_GROUPS]);`
