### ISSUE TITLE
NextPage: Нет следующей страницы

### ISSUE THREAD

**Issue by eugene-borovov** [amocrm/amocrm-api-php#209]
Не могу понять принцип работы формирование `nextPageLink` в коллекциях. Делаю запрос к коллекции с фильтром по `id` на два элемента и получаю существование следующей страницы при размере страницы 50. Как-то странно.
Я полагал, исходя из HATEOAS, что можно итерироваться по коллекции и проверять наличие следующей страницы без запроса к API. То есть должно быть достаточно условия `nextPageLink !== null` для продолжения обхода. Но приходится делать запрос и ловить исключение `AmoCRMApiNoContentException`, хотя есть исключение `AmoCRMApiPageNotAvailableException`.

И второй вопрос: как выяснить количество элементов в коллекции удовлетворяющих фильтру. Не в загруженной странице, а вообще в CRM.

**Comment by eugene-borovov** [comment]
Как оказалось запрос частично дублирует комментарий
https://github.com/amocrm/amocrm-api-php/issues/193#issuecomment-740139104

**Comment by bessudnov** [comment]
Из-за архитектурных особенностей, некоторые методы API не могут посчитать точное количество элементов, которые подходят под запрос, подобные методы сейчас возвращают ссылку на следующую страницу всегда.
Если вернулось объектов меньше, чем заданный размер страницы (дефолтный 50), то второй страницы точно нет.

> И второй вопрос: как выяснить количество элементов в коллекции удовлетворяющих фильтру. Не в загруженной странице, а вообще в CRM.

В данный момент это невозможно, так как подобная операция является достаточно затратной на ресурсы, мы не хотим, чтобы наше API отвечало на запрос по 3-5-10 и больше секунд, поэтому не возвращаем подобную информацию.
