### ISSUE TITLE
Проблема с добавлением кастомных полей в сущности

### ISSUE THREAD

**Issue by YudovAlexei** [amocrm/amocrm-api-php#21]
Использовал код из первого примера:
[Работа с кастомными полями](https://github.com/amocrm/amocrm-api-php#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC%D0%B8-%D0%BF%D0%BE%D0%BB%D1%8F%D0%BC%D0%B8-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9)

По какой то причине выдает ошибку:
`
Fatal error: Uncaught AmoCRM\Exceptions\AmoCRMApiErrorResponseException: Response has validation errors
`

**Comment by YudovAlexei** [comment]
`array(10) { ["last_http_method"]=> string(4) "POST" ["last_method"]=> string(48) "https://amosalesevolution.amocrm.ru/api/v4/leads" ["last_body"]=> array(1) { [0]=> array(3) { ["name"]=> string(9) "some lead" ["custom_fields_values"]=> array(1) { [0]=> array(3) { ["field_id"]=> int(123) ["field_code"]=> NULL ["values"]=> array(1) { [0]=> array(1) { ["value"]=> string(10) "Текст" } } } } ["request_id"]=> string(1) "0" } } ["last_query_params"]=> array(0) { } ["last_response"]=> string(288) "{"validation-errors":[{"request_id":"0","errors":[{"code":"NotSupportedChoice","path":"custom_fields_values.0.field_id","detail":"The value you selected is not a valid choice."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}" ["last_response_code"]=> int(400) ["last_request_id"]=> string(32) "b686fc6990a6aded0d4dec8a6b1f8eb7" ["jquery_call"]=> string(289) " $.ajax({ url: "https://amosalesevolution.amocrm.ru/api/v4/leads", data: JSON.stringify([{"name":"some lead","custom_fields_values":[{"field_id":123,"field_code":null,"values":[{"value":"Текст"}]}],"request_id":"0"}]), type: "POST", contentType: "application/json" });" ["curl_call"]=> string(260) "curl "https://amosalesevolution.amocrm.ru/api/v4/leads" -X "POST" -d"0%5Bname%5D=some+lead&0%5Bcustom_fields_values%5D%5B0%5D%5Bfield_id%5D=123&0%5Bcustom_fields_values%5D%5B0%5D%5Bvalues%5D%5B0%5D%5Bvalue%5D=%D0%A2%D0%B5%D0%BA%D1%81%D1%82&0%5Brequest_id%5D=0"" ["timestamp"]=> int(1591913949) }`

**Comment by YudovAlexei** [comment]
`array(10) { ["last_http_method"]=> string(4) "POST" ["last_method"]=> string(48) "https://sadfsafsdf.amocrm.ru/api/v4/leads" ["last_body"]=> array(1) { [0]=> array(3) { ["name"]=> string(9) "some lead" ["custom_fields_values"]=> array(1) { [0]=> array(3) { ["field_id"]=> int(123) ["field_code"]=> NULL ["values"]=> array(1) { [0]=> array(1) { ["value"]=> string(10) "Текст" } } } } ["request_id"]=> string(1) "0" } } ["last_query_params"]=> array(0) { } ["last_response"]=> string(288) "{"validation-errors":[{"request_id":"0","errors":[{"code":"NotSupportedChoice","path":"custom_fields_values.0.field_id","detail":"The value you selected is not a valid choice."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}" ["last_response_code"]=> int(400) ["last_request_id"]=> string(32) "b686fc6990a6aded0d4dec8a6b1f8eb7" ["jquery_call"]=> string(289) " $.ajax({ url: "https://sadfsafsdf.amocrm.ru/api/v4/leads", data: JSON.stringify([{"name":"some lead","custom_fields_values":[{"field_id":123,"field_code":null,"values":[{"value":"Текст"}]}],"request_id":"0"}]), type: "POST", contentType: "application/json" });" ["curl_call"]=> string(260) "curl "https://sadfsafsdf.amocrm.ru/api/v4/leads" -X "POST" -d"0%5Bname%5D=some+lead&0%5Bcustom_fields_values%5D%5B0%5D%5Bfield_id%5D=123&0%5Bcustom_fields_values%5D%5B0%5D%5Bvalues%5D%5B0%5D%5Bvalue%5D=%D0%A2%D0%B5%D0%BA%D1%81%D1%82&0%5Brequest_id%5D=0"" ["timestamp"]=> int(1591913949) }`

**Comment by bessudnov** [comment]
Судя по ответу, отправлено невалидное id поля.
Нужно передавать id, которое доступно в вашем аккаунте.

Как узнать айди полей - это лучше в тех поддержку обратиться
