### ISSUE TITLE
Как получить больше 50 сделок? 

### ISSUE THREAD

**Issue by Kordak** [amocrm/amocrm-api-php#210]
Как получить больше 50 сделок?  Мне нужно получить закрытые за месяц. Это около 300. Системное ограничение api  же 500. Вот мне 500 и нужно.

**Comment by Kirimai** [comment]
$filter = new \AmoCRM\Filters\LeadsFilter();
$filter->setLimit(400);

$leadsCollection = $leadsService->get($filter);

**Comment by Kirimai** [comment]
> Как получить больше 50 сделок? Мне нужно получить закрытые за месяц. Это около 300. Системное ограничение api же 500. Вот мне 500 и нужно.

$filter = new \AmoCRM\Filters\LeadsFilter();
$filter->setLimit(400);
$leadsCollection = $leadsService->get($filter);

**Comment by nomelodic** [comment]
Любопытно получается. Здесь написано про 500 [https://www.amocrm.ru/developers/content/api/recommendations](https://www.amocrm.ru/developers/content/api/recommendations).

![изображение](https://user-images.githubusercontent.com/28806775/104140927-13284100-53c5-11eb-8efa-815ce5a3cb01.png)

А здесь [https://www.amocrm.ru/developers/content/crm_platform/leads-api#leads-list](https://www.amocrm.ru/developers/content/crm_platform/leads-api#leads-list) написано, что 250

![изображение](https://user-images.githubusercontent.com/28806775/104140798-4b7b4f80-53c4-11eb-992e-15340ab6115e.png)

Скорее всего второе. И, возможно, из-за того, что вы указываете 400 вместо максимальных 250, сервер API сбрасывает до некоего базового значения в 50.

**Comment by bessudnov** [comment]
https://www.amocrm.ru/developers/content/api/recommendations Немного устарела
api/v4 возвращает не более 250 записей на одной странице
если передается больше, то да, используется дефолтное значение 50
