### ISSUE TITLE
Как установить несколько фильтров для получения сделок

### ISSUE THREAD

**Issue by Kordak** [amocrm/amocrm-api-php#211]
У  меня есть два фильтра. Каждый по отдельности работает, как поместить оба фильтра?
+ не могу установить фильтр на статус: $filter->setStatuses([142]); -   не работает

$range = new BaseRangeFilter();
		$range->setFrom(1606830250);
		$range->setTo(1607175850);
$filter = new \AmoCRM\Filters\LeadsFilter();
    $filter->setClosedAt($range);
    $filter->setLimit(400);
    
$leadsCollection = $leadsService->get($filter);

**Comment by bessudnov** [comment]
Чтобы воспользоваться фильтром - необходимо обратиться в техническую поддержку для подключения аккаунта к альфа фильтрации
