### ISSUE TITLE
Как получить все кастомные поля для лидов

### ISSUE THREAD

**Issue by Stima94** [amocrm/amocrm-api-php#212]
Нужно получить все поля которые возвращает api по  - /api/v4/leads/custom_fields
Пробовал `$customFieldsService = $apiClient->customFields(EntityTypesInterface::LEADS);`, но возвращаются не все поля.
При выполнении запроса с postman на /api/v4/leads/custom_fields получаю 20 полей, 
а `$customFieldsService = $apiClient->customFields(EntityTypesInterface::LEADS);` возвращает только 2 поля.
Как получить все поля которые возвращает /api/v4/leads/custom_fields?

**Comment by bessudnov** [comment]
Можете уточнить какую версию библиотеки вы используете?

**Comment by Stima94** [comment]
Release - 0.4.1

**Comment by bessudnov** [comment]
хм, а можете сказать ID аккаунта, в котором наблюдается проблема, а также если есть возможность добавить дамп ошибки в 
src/AmoCRM/Collections/CustomFields/CustomFieldsCollection.php:45
`var_dump($e->getMessage());`

**Comment by Stima94** [comment]
![amo](https://user-images.githubusercontent.com/51567509/104567281-d1bfbc00-5678-11eb-9844-604ce9923595.png)
[response.txt](https://github.com/amocrm/amocrm-api-php/files/5813345/response.txt)
Приложил скрин дампа и ответ при запросе через постман

**Comment by bessudnov** [comment]
хм, в версии 0.4 и выше эти поля поддерживаются вообще
можете проверить версию в вашем файле composer.lock
а также, есть ли в файле https://github.com/amocrm/amocrm-api-php/blob/c8e10640441a242276722e93ea5f775fb136d1ed/src/AmoCRM/Models/CustomFields/Factories/CustomFieldModelFactory.php#L99 строка `case CustomFieldModel::TYPE_TRACKING_DATA:` ?

**Comment by Stima94** [comment]
Да, как оказалось поставили версию библиотеки 0.3, хотя должны были последнюю поставить. Спасибо за помощь!
