### ISSUE TITLE
CustomFIelds сервис не добавляет поле в сущность

### ISSUE THREAD

**Issue by PHPTCloud** [amocrm/amocrm-api-php#213]
Пытаюсь добавить новое кастомное поле в сущность сделку следующим образом:
```
$customFieldModel = CustomFieldModelFactory::createModel($this->getArguments()->getFields());
$customFieldsService = $this->getApiClient()
    ->customFields($this->getArguments()->getEntityType());

$result = $customFieldsService->addOne($customFieldModel);
```

Данные для модели (в этой части кода $this->getArguments()->getFields())
```
{
    "id": "654",
    "sort": "5",
    "entity_type": "leads",
    "type": "checkbox",
    "name": "MyCheckbox",
    "code": "MYCHECKBOX",
    "is_api_only": "true",
}
```

Ошибок нет, но и поле не добавляется в систему. Что я сделал нет так?

**Comment by PHPTCloud** [comment]
Не весь код в вопросе написал, исправил. Проблема все еще присутствует, подходящего решения пока не нашел...

**Comment by PHPTCloud** [comment]
@bessudnov ,
вобщем не получилось создать модель через фабрику. Получилось только при создании конкретной чистой модель кастомного поля, только в таком случае поле добавляется.

Может добавить в фабрику метод создания чистых моделей?
`
CustomFieldModelFactory::createEmptyModel()
`
чтобы можно было чистую модель кастомного поля получить без авто заполнения.

**Comment by PHPTCloud** [comment]
accountId в модель поля добавлял

**Comment by bessudnov** [comment]
Добавим в ближайшем релизе фабрику, которая чистые модели будет возвращать, которые дальше можно будет заполнить как объекты и уже передать в апи

**Comment by bessudnov** [comment]
Правки в мастере, в ближайшем релизе сегодня-завтра будут
Issue закрываю
