### ISSUE TITLE
не могу установить фильтр на статус: $filter->setStatuses([142]); - не работает

### ISSUE THREAD

**Issue by Kordak** [amocrm/amocrm-api-php#215]
не могу установить фильтр на статус: $filter->setStatuses([142]); - не работает

**Comment by RodionovSlsUp** [comment]
@Kordak насколько я понимаю, фильтрация пока на стадии бета-теста и для получения доступа нужно сделать запрос в поддержку в самой црм

**Comment by bessudnov** [comment]
дубль https://github.com/amocrm/amocrm-api-php/issues/211
