### ISSUE TITLE
notes attachment

### ISSUE THREAD

**Issue by trickwow** [amocrm/amocrm-api-php#216]
Здравствуйте, подскажите пожалуйста имееся ли возможность передавать файлы в примечания если да, то хотелось бы посмотреть пример. В моделях библиотеки нашел AttachmentNote.php, пробовал реализовать на подобие примеров из notes_actions.php, но ничего не получилось. Спасибо!

**Comment by bessudnov** [comment]
В данный момент такой возможности в апи нет

**Comment by RodionovSlsUp** [comment]
@bessudnov, а возможность планируется?

**Comment by bessudnov** [comment]
В ближайшем будущем нет

**Comment by jiharevzahar** [comment]
@bessudnov, здравствуйте, может уже такая возможность появилась?
