### ISSUE TITLE
Поправить `onAccessTokenRefresh` в Readme

### ISSUE THREAD

**Issue by CvekCoding** [amocrm/amocrm-api-php#217]
Добрый вечер.

В ридми не сказано явно, что метод `onAccessTokenRefresh` прописывать не надо если `apiClient` создается из фабрики - там это делается автоматически в кишочках.

Предлагаю это обозначить явно, чтобы не было у людей путаницы.

**Comment by bessudnov** [comment]
Согласен, в ближайшем релизе захватим

**Comment by bessudnov** [comment]
Правки в мастере, в ближайшем релизе сегодня-завтра будут
Issue закрываю
