### ISSUE TITLE
Check the `client_id` parameter , status:400

### ISSUE THREAD

**Issue by pazakharov** [amocrm/amocrm-api-php#218]
Рабочий скрипт через некоторое время начал выдавать 400 ошибку. Изменений не проводилось с ним. 
Всё работало. 
```
...
try {
	$contactsCollection = $contactsService->get($contactsFilter, ['leads']);
} catch (AmoCRMApiException $e) {
	printError($e);
	die;
}
...
```
Стало печатать такую ошибку:
```
<pre>Error: {"hint":"Check the `client_id` parameter","title":"Некорректный запрос","type":"https://developers.amocrm.ru/v3/errors/OAuthProblemJson","status":400,"detail":"В запросе отсутствует ряд параметров или параметры невалидны"}
Code: 0
Debug: array (
)</pre>
```

**Comment by bessudnov** [comment]
Не исключено, что полученный ранее аксесс токен был выдан для другого client_id
также стоит поверить при создании объекта передается верный client_id
$apiClient = new AmoCRMApiClient($clientId, $clientSecret, $redirectUri);

**Comment by bessudnov** [comment]
Нет ответа больше месяца, закрываю Issue, если будет уточнение - всегда можно открыть)
