### ISSUE TITLE
Ошибки при работе с датой доуниксовской эры

### ISSUE THREAD

**Issue by RodionovSlsUp** [amocrm/amocrm-api-php#219]
Наличие в любой сущности поля типа даты, в которое установлено значение до линуксовской эпохи (то есть таймстамп отрицательный) парализует любые действия со сделкой (кроме изменения этого значения на положительный таймстам или нулл). Ибо при попытке обновить любое поле сделки, происходит перезапись полей, а апи не позволяет вводить отрицательный таймстамп (такой функционал заложен в апи по словам поддержки), хотя интерфейс амоцрм позволяет установить дату до эпохи уникс.

Этот коллапс ведет к сложноотлавливаемым ошибкам в публичных интеграциях, функционал которых связан с обновлением сущностей.

**Comment by bessudnov** [comment]
Дубль https://github.com/amocrm/amocrm-api-php/issues/85
Этот Issue закрываю
