### ISSUE TITLE
Некорректное получение полей со эмодзи

### ISSUE THREAD

**Issue by RodionovSlsUp** [amocrm/amocrm-api-php#221]
Если в любом поле (текст, текстареа) есть эмодзи, попавшие при создании сделки с сайта, например, то при получении значения поля через апи возвращается значение до первого эмодзи. Если эмодзи первый в строке, то поле вообще не возвращается.

**Comment by bessudnov** [comment]
Данная проблема не является проблемой библиотеки, а является проблемой API. С такой проблемой нужно обратиться в техническую поддержку через ваш аккаунт

**Comment by RodionovSlsUp** [comment]
@bessudnov 
Техническая поддержка ничего не предпринимает, сроков нет и тд, вы можете как то стимулировать вопрос со своей стороны?
Подобно этому тикету
https://github.com/amocrm/amocrm-api-php/issues/224

**Comment by eugene-borovov** [comment]
Как оказалось, вырезать эмодзи из текста очень трудно: они раскиданы по таблице символов и постоянно добавляются новые. В интернете существует куча пакетов (в основном javascript), где вырезаются эмодзи по таблице символов (таблицы по 100 кБ). Я у себя использую вот такой простой фильтр -- инцидентов стало заметно меньше.

```php
function removeEmoji(string $text): string
{
    // https://stackoverflow.com/a/41831874
    // https://unicode.org/emoji/charts/full-emoji-list.html

    // Match Emoticons
    $clean_text = (string)preg_replace('/[\x{1F600}-\x{1F64F}]/mu', '', $text);

    // Match Miscellaneous Symbols and Pictographs
    $clean_text = (string)preg_replace('/[\x{1F300}-\x{1F5FF}]/mu', '', $clean_text);

    // Match Transport And Map Symbols
    $clean_text = (string)preg_replace('/[\x{1F680}-\x{1F6FF}]/mu', '', $clean_text);

    // Match Miscellaneous Symbols
    $clean_text = (string)preg_replace('/[\x{2600}-\x{26FF}]/mu', '', $clean_text);

    // Match Dingbats
    $clean_text = (string)preg_replace('/[\x{2700}-\x{27BF}]/mu', '', $clean_text);

    return $clean_text;
}
```
