### ISSUE TITLE
Fatal error examples\get_token.php

### ISSUE THREAD

**Issue by 1gmosfsb** [amocrm/amocrm-api-php#225]
Здравствуйте. После запуска локального сервера и переходе на http://localhost:8181/examples/get_token.php вылетает ошибка

Fatal error: Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "C:\amo2\vendor\amocrm\amocrm-api-library\examples/.env" environment file. in C:\amo2\vendor\amocrm\amocrm-api-library\vendor\symfony\dotenv\Dotenv.php:565 Stack trace: #0 C:\amo2\vendor\amocrm\amocrm-api-library\vendor\symfony\dotenv\Dotenv.php(92): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array) #1 C:\amo2\vendor\amocrm\amocrm-api-library\examples\bootstrap.php(9): Symfony\Component\Dotenv\Dotenv->load('C:\\amo2\\vendor\\...', 'C:\\amo2\\vendor\\...') #2 C:\amo2\vendor\amocrm\amocrm-api-library\examples\get_token.php(3): include_once('C:\\amo2\\vendor\\...') #3 {main} thrown in C:\amo2\vendor\amocrm\amocrm-api-library\vendor\symfony\dotenv\Dotenv.php on line 565

Подскажите в чем может быть проблема?

**Comment by eugene-borovov** [comment]
Переименуйте `examples/.env.dist` в `examples/.env` и заполните своими данными подключения.

**Comment by 1gmosfsb** [comment]
Спасибо, заработало. Правильно ли я понимаю, что acceess_token мне теперь из куков надо куда то записать (вопрос куда?), для того чтобы протестировать другие примеры из папки examples?

**Comment by eugene-borovov** [comment]
В файле `examples/token_actions.php` поправьте константу `TOKEN_FILE` на более виндовый путь. Остальные примеры подключают этот файл через `examples/bootstrap.php` 
В `TOKEN_FILE` сохраняется access_token. Ничего из куки копировать не надо.

**Comment by 1gmosfsb** [comment]
Access token file not found
Не совсем понял, константу TOKEN_FILE путь поправить в этой строке - define('TOKEN_FILE', DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'token_info.json'); ???

**Comment by 1gmosfsb** [comment]
не помогло, тоже самое Access token file not found. И файла token_info.json в examples нету

**Comment by eugene-borovov** [comment]
Ознакомьтесь пожалуйста вот с [инструкцией](https://github.com/amocrm/amocrm-api-php/blob/master/README.md#примеры). 
Принцип такой. Когда вы открываете http://localhost:8181/examples/get_token.php, вас перебрасывает на AmoCRM с запросом логина пароля. После авторизации в AmoCRM по адресу `CLIENT_REDIRECT_URI` (должен быть доступен из Интернета) передаётся авторизационный код, по которому запрашивается `access_token`.  В примере, хотя это и не обязательно, `CLIENT_REDIRECT_URI` и http://localhost:8181/examples/get_token.php указывают на один и тот же файл.
