### ISSUE TITLE
Повторная отправка хука

### ISSUE THREAD

**Issue by RodionovSlsUp** [amocrm/amocrm-api-php#226]
Не совсем понимаю, куда писать - поддержка упорно молчит, может быть через вас возможно

Проблема в том, бывают ситуации, когда хук не словлен. Не очень часто, тем не менее.
Возможен ли функционал с отправкой повторных вебхуков через минут, две, десять... если хук не был обработан?

**Comment by bessudnov** [comment]
Если на хук не был отдан ответ с http кодом 200-299, то мы попробуем отправить его еще раз через некоторое время

**Comment by RodionovSlsUp** [comment]
Этого нигде в документации не описано. Попробовал воспроизвести - в течение часа повторного не получил (отвечал 500 кодом). Через какое время приходит повторный?

**Comment by eugene-borovov** [comment]
Параметры повторной отправки описаны в [документации](https://www.amocrm.ru/developers/content/crm_platform/webhooks-format). Самый низ страницы. 

Но похоже есть ситуации когда хуки просто не оправляются. Мы сейчас расследуем в своём проекте ситуацию, когда хуки "пропадают". Есть отдельные хуки на изменение сделки и статуса сделки. Так вот хуки изменения статуса сделки не всегда приходят, а судя по логам хука на изменение сделки были срабатывания на изменения статуса. Непонятно обязуется ли AmoCRM присылать хуки по всем изменениями (даже если они были внутри секунды) или хуки только по снепшотам губо говоря за минуту-две

**Comment by bessudnov** [comment]
На прошлой неделе отгружали переработку части сервиса хуков. Количество "потерянных" хуков приблизилось к нулю. Теперь могут теряться только при падении сервиса, но такое возможно только при глобальной аварии.

Хуки уходят от нас по всем изменениям, могут быть какие-то кейсы, можно прям с ними в тп, тп проверит на тестовых аккаунтах и если воспроизводится зафиксирует ошибку

По повторным отправкам ситуация хуже, часто задержки составляют сильно больше заявленных в документации. Задача на оптимизацию этого момента есть, но пока не в работе

**Comment by RodionovSlsUp** [comment]
@bessudnov  Можно ли в хуке передавать номер попытки? (Для отслеживания частоты не переданных хуков)
Возможно даже как то отображать в интерфейсе црм лог отправленных хуков (в т.ч из диджитал пайплайн)?

**Comment by bessudnov** [comment]
Лога точно не планируется в ближайшее время
А вот по номеру попытки записал в бэклог, хорошая идея

**Comment by bessudnov** [comment]
Issue закрываю, так как тут всё-таки не поддержка amoCRM, а скорее вопросы и обсуждения именно по библиотеке
