### ISSUE TITLE
Как правильно работать с коллекциями?

### ISSUE THREAD

**Issue by RodionovSlsUp** [amocrm/amocrm-api-php#227]
Коллеги, вопрос может быть, немного простецкий, но подскажите, как оптимальнее всего перебирать коллекция сущностей, как удалять элемент из коллекции?

Сейчас перебираю так:

```
do{
$lead = $leadCollection->current();
$leadCollection->next();
//actions with a lead
}while($leadCollection->key())
```

По частоте использования цикла ду вай (при обучении и сейчас) подозреваю, что это не элегантное решение. Переоборудовать по это фор? тоже не уверен. 

Как поступать лучше?

И как удалять элемент из коллекции?
Потому что сейчас вместо удаления создаю новую коллекцию и перекладываю все нужное туда - при этом ощущение дикого костыля.

Спасибо заранее!

**Comment by eugene-borovov** [comment]
Чтобы пробежаться по странице коллекции достаточно сделать `foreach`.

Чтобы пройти всю коллекцию со всеми страницами, я сделал вот такой хелпер:
```php
function iterateLeads(LeadsCollection $leads): \Generator
{
    do {
        foreach ($leads as $lead) {
            yield lead;
        }
        if ($leads->getNextPageLink() === null) {
            break;
        }
        try {
            $leads = $this->amocrm->leads()->nextPage($leads);
        } catch (AmoCRMApiNoContentException | AmoCRMApiPageNotAvailableException $e) {
            break;
        }
    } while (true);
}
```
а дальше можно делать:
```php
foreach(iterateLeads($leads) as $lead) {
  // process lead
}
```

Наверное можно сделать универсальный хелпер, но пока только для сделок понадобилось.
