### ISSUE TITLE
Заметки и Почта

### ISSUE THREAD

**Issue by RodionovSlsUp** [amocrm/amocrm-api-php#229]
1. Интересуют возможности создавать типы заметок, в том числе с вложениями. Это планируется реализовывать?
Судя по классам такое есть, но пока не используется. 
2. Так же вопрос возможности добавления почты. Дело в том, что иногда нужно отправить какое то письмо клиенту, через апи это не сделать, потому что апи не позволят отправлять письма (а было бы классно, если бы такие методы были), тогда используется сторонний сервис, но тогда хочется засунуть письмо в сущность - сейчас вариант добавлять только через CommonNote - не очень элегантно. Возможно ли добавка своих писем в заметки?

А возможны ли хуки по входящим письмам? И вообще какая-либо работа с почтой? (Текущий решаемый кейс - парсерить входящие письма от банков с нескольких почт и класть их в сделки по нахождению в письме ФИО клиента)

**Comment by bessudnov** [comment]
Все вопросы по API, с таким лучше в техническую поддержку

1) В данный момент загружать файл через API невозможно
2) Публичного API у почты в данный момент нет. Добавлять примечания типа почты через публичное API даже если и получится, они будут криво и некорректно отображаться и работать
3) Хуки по входящим письмам - тут как вариант использовать хук о создании примечания и проверять тип примечания

Для описанного кейса есть встроенный парсер почты

**Comment by RodionovSlsUp** [comment]
@bessudnov можно поподробнее о последнем?
Задача такая - компания занимается рефинансированием кредитов. Они отправляют заявки в банки по лидам в воронке, а банки отвечают на электронную почту (банков больше 20, где-то письма определенного формата, где-то нет). Нужно эти письма раскладывать в сделки по содержимому (фио, инн и тд), находящиеся на определённом этапе.

Как я понимаю, амо такое не умеет.
