### ISSUE TITLE
Неверная сигнатура LeadModel::getComplexRequestIds()

### ISSUE THREAD

**Issue by CvekCoding** [amocrm/amocrm-api-php#232]
Вот тут указано что возвращается строго массив, при этом по умолчанию `complexRequestIds` === null. Думаю надо или геттер поправить, или дефолт-значение установить.
https://github.com/amocrm/amocrm-api-php/blob/72c1d75aa4c210cd18ee62604236e2f820beb0fc/src/AmoCRM/Models/LeadModel.php#L1062

**Comment by CvekCoding** [comment]
Ну и по другим геттерам та же проблема

**Comment by 2bj** [comment]
Надо сделать `nullable`:
```php
public function getComplexRequestIds(): ?array
```

Тоже поймал такую ошибку:
```php
TypeError: Return value of AmoCRM\Models\LeadModel::getComplexRequestIds() must be of the type array, null returned
```

**Comment by bessudnov** [comment]
А в каком кейсе вызываете? По-идее если вызываете эти методы, то мб слишком рано)
complexRequestIds заполняются после выполнения запроса, до выполнения нет смысла вызывать данный метод, сигнатуру конечно скорректируем в ближайшем релизе, но интересен кейс
