### ISSUE TITLE
Несовместимость с библиотекой lcobucci/jwt 4.*

### ISSUE THREAD

**Issue by Bolid1** [amocrm/amocrm-api-php#233]
В библиотеке lcobucci/jwt, начиная с 4-й версии убрали метод getClaim из [интерфейса токена](https://github.com/lcobucci/jwt/blob/4.0.x/src/Token.php). 

Строки
```json
"lcobucci/jwt": "^3.4 || 4.*"
```
в `composer.json` вводят в заблуждение composer, по умолчанию устанавливается последняя доступная версия.

Необходимо ввести поддержку 4-й версии библиотеки, либо убрать `4.*` из `composer.json`

**Comment by noweasily** [comment]
https://github.com/amocrm/amocrm-api-php/pull/244

**Comment by bessudnov** [comment]
Отгружено
