### ISSUE TITLE
Странны выглядят методы следующего вида

### ISSUE THREAD

**Issue by metaseller** [amocrm/amocrm-api-php#234]
![Снимок экрана 2021-01-25 в 17 17 28](https://user-images.githubusercontent.com/13105933/105711707-809eaa80-5f4b-11eb-8621-d546f5438e8a.png)

Переменная $cfFilter определяется, но не используется.

**Comment by metaseller** [comment]
версия 0.3.22

**Comment by bessudnov** [comment]
бага, в ближайшем релизе поправим

**Comment by bessudnov** [comment]
В релизе 0.4.6
