### ISSUE TITLE
Не получается обновить токен по refresh_token

### ISSUE THREAD

**Issue by prtngn** [amocrm/amocrm-api-php#235]
Добрый день. Пытаюсь обновить token по refresh_token
```
$accessToken = getToken();
$apiClient = new AmoCRMApiClient($clientId, $clientSecret, $redirectUri);
$apiClient->getOAuthClient()->getAccessTokenByRefreshToken($accessToken);
```
На getAccessTokenByRefreshToken возвращается 401 ошибка.
`
 {"title":"Некорректный клиент","type":"https://developers.amocrm.ru/v3/errors/OAuthProblemJson","status":401,"detail":"Авторизация клиента не прошла"}
`
Подскажите пожалуйста, куда копать? getToken() возвращает живой токен. То есть с этим токеном приложение работает, refresh_token там адекватный и через прямой rest запрос возвращается новый токен без вопросов.

UPD.
Посмотрел исходники, исходя из них access_token должен обновляться автоматически при любом запросе. Так вот токен не обновляется сам и точно так-же начинает сыпать ошибками 401, как выше.

**Comment by s-anches** [comment]
Разобрался видно, накосячил с вложенностью классов.

**Comment by s-anches** [comment]
И все таки, не работает. Когда у токена вышло время, при любом запросе к апи токен не обновляется и вылетает ошибка как выше. Колбек не вызывается для сохранения нового токена, как и сама функция обновления токена.

**Comment by buryabuha** [comment]
Проверьте у себя, возможно причина такая же как у нас.
#246

**Comment by bessudnov** [comment]
Нужны примеры кода, который используется, чтобы могли точно подсказать
