### ISSUE TITLE
В модели NoteModel нет поля "params". Как в создаваемых примечаниях добавлять текст?

### ISSUE THREAD

**Issue by alhimik1986** [amocrm/amocrm-api-php#236]
Согласно документации: https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#notes-add
хочу создать текстовое примечание, а в модели нет поля "params".

**Comment by bessudnov** [comment]
Необходимо использовать модель конкретного типа примечания, для текстового CommonNote
Другие типы доступны тут - src/AmoCRM/Models/NoteType
