### ISSUE TITLE
ComposerRepository: Undefined $data. 

### ISSUE THREAD

**Issue by whoim2** [amocrm/amocrm-api-php#237]
composer require amocrm/amocrm-api-library
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes

  [LogicException]
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/com
  poser/issues/new.

не ставится, centos 6, PHP 5.3.3 (cli)

**Comment by eugene-borovov** [comment]
Требование библиотеки `"php": ">=7.1"`
Чего вы пытаетесь добиться в конфигурации `centos 6, PHP 5.3.3 (cli)` ?

**Comment by whoim2** [comment]
Не углядел требование, спасибо.
