### ISSUE TITLE
TypeError при вызове AmoCRMApiClient без accessToken

### ISSUE THREAD

**Issue by antonsnowy** [amocrm/amocrm-api-php#239]
Если библиотека инициализирована $apiClient = new \AmoCRM\Client\AmoCRMApiClient($clientId, $clientSecret, $redirectUri); нет никакой возможности проверить, установлен ли accessToken. При отправке любого запроса, если мы не установили setAccessToken() будет Fatal error: Uncaught TypeError: Argument 1 passed to AmoCRM\Client\AmoCRMApiRequest::__construct() must be an instance of League\OAuth2\Client\Token\AccessTokenInterface, null given. Поэтому try/catch не сработает ни на \Exception ни на AmoCRMApiException.

Почему бы в buildRequest() перед тем как возвращать return new AmoCRMApiRequest($this->accessToken, $oAuthClient); не проверять, что $this->accessToken установлен, либо выбрасывать нужный AmoCRMApiException. И вообще, в AmoCRMApiClient нужен метод, проверяющий что токен хотя бы установлен. Ведь библиотека может работать и без него - до установки интеграции, для отрисовки кнопки ->getOAuthClient()->getOAuthButton()

**Comment by bessudnov** [comment]
Согласен с предложением, в ближайшем релизе добавим

**Comment by bessudnov** [comment]
В релизе 0.4.6
