### ISSUE TITLE
При использовании AmoCrm нет разделения между лидами разных пользователей вашего API.

### ISSUE THREAD

**Issue by senitskiy** [amocrm/amocrm-api-php#241]
При текущей ситуации может быть путаница в клиентах:
    Клиент1 => Пользователь1 => AmoCRM [phone, email, lead_id] => Лид1
    Клиент1 => Пользователь2 => AmoCRM [phone, email, lead_id] => Лид2 
Предлагаю дополнить данную таблицу {токенами пользователя}: [user_token, phone, email, lead_id]. Тогда клиенты разных пользователей не будут пересекаться.

Для простоты аналитики по клиентам пользователей AmoCRM и нормализации таблиц (и соответственно удаления дублей) предлагаю, разделить таблицу лидов [user_token, client_id, lead_id] и таблицу клиентов [user_id, client_id, phone, email], ну и соответственно заполнить таблицу токенов пользователей AmoCRM [user_id, user_token].

Данную задачу для упрощения можно разделить на две.

**Comment by bessudnov** [comment]
Не очень понятен вопрос, не могли бы уточнить и добавить примеры кода?
