### ISSUE TITLE
Unprocessable field type - tracking_data

### ISSUE THREAD

**Issue by VitalijOd** [amocrm/amocrm-api-php#243]
Если поле roistat у сделки заполнено, при получении данных сделки срабатывает exception:

AmoCRM\Exceptions\BadTypeException

Unprocessable field type - tracking_data

vendor\amocrm\amocrm-api-library\src\AmoCRM\Models\CustomFieldsValues\Factories\CustomFieldValuesModelFactory.php:107

Похоже происходит это из-за того, что появился новый тип поля tracking_data, который не описан в SDK. 
В результате синхронизация сделок перестает работать.

**Comment by bessudnov** [comment]
Какая версия библиотеки?
Поддержка данного поля появилась в версии 0.4 и выше

**Comment by VitalijOd** [comment]
Спасибо. Была установлена 0.3.22.
