### ISSUE TITLE
Возможная причина неверной работы автообновления токенов

### ISSUE THREAD

**Issue by buryabuha** [amocrm/amocrm-api-php#246]
Срок жизни refresh token составляет 3 месяца. По истечении этого срока мы вынуждены вручную менять refresh token, так как он не обновляется. Нужно снова обращаться к файлу авторизации examples/get_token.php и давать приложению доступ.

**Comment by eugene-borovov** [comment]
Если это реальный кейс, то вы можете по расписанию раз в неделю, например, запрашивать какой-нибудь статус в CRM. Тогда будете получать новый refresh_token каждый раз при обновлении access_token.

**Comment by buryabuha** [comment]
У нас приходят заявки с сайта. Интеграция была настроена по файлам примера в папке success. После отправки формы на файл в папке идет POST запрос. Можете скинуть пример кода для обновления токена?

**Comment by eugene-borovov** [comment]
Вообще за выдачу нового accessToken по refreshToken отвечает вот этот [метод](https://github.com/amocrm/amocrm-api-php/blob/8a722d4b00ea028427a1f808603301005065594a/src/AmoCRM/OAuth/AmoCRMOAuth.php#L149)

Но при правильно настроенном клиенте обновление токена делается автоматически при обращении к API.
Пример настройки клиента в examples/account_actions.php, как и во всех остальных примерах (здесь просто пример короткий). Таким образом первично получаем токен в examples/get_token.php, а далее автоматом токен обновляется. НО надо обращаться к API чаще чем раз в квартал. Для этого можно использовать вызовы по расписанию. Хотя бы тот же запрос информации об аккаунте.
