### ISSUE TITLE
Как установить ответственно для записи звонка

### ISSUE THREAD

**Issue by borzakap** [amocrm/amocrm-api-php#247]
https://www.amocrm.ru/developers/content/crm_platform/calls-api - позволяет устанавливать ответственного пользователя для звонка, но в CallModel я не смог найти соответствующего метода. А также установка некоторых других параметров, как время звонка, например.

**Comment by bessudnov** [comment]
Продолжительность звонка можно установить с помощью метода setDuration

Недостающие свойства добавим в ближайшем обновлении

**Comment by bessudnov** [comment]
В релизе 0.4.6
