### ISSUE TITLE
Неверный тип поля SipMetadata::from 

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#250]
[В документации](https://www.amocrm.ru/developers/content/crm_platform/unsorted-api#metadata-description) по неразобранному поле from метаданных неразобранного в категории sip [обозначено как string. ](http://joxi.ru/Rmz9GO6CYKw3wr.jpg)

В библиотеке же для поля используется тип int
https://github.com/amocrm/amocrm-api-php/blob/c9a3ad2b3bbea4a25b883d83c534748e1079a6dd/src/AmoCRM/Models/Unsorted/SipMetadata.php#L99

**Comment by bessudnov** [comment]
from выводится в воронке сделок в информации о звонке, апи может принимать и int (номер), так и string (например, имя)
в ближайшем релизе поправим
