### ISSUE TITLE
Разные данные при множественном вызове

### ISSUE THREAD

**Issue by makeroi** [amocrm/amocrm-api-php#251]
Заметил, что при вызове метода $apiClient->account()->getCurrent();
Элемент currency_symbol приходит разным через раз. При вызове метода десять раз от 3 до 4 раз придет символ рубля, от 6 до 7 надпись "руб.". Немного странное поведение, с чем это связано?

[Результат со значком](https://sun9-61.userapi.com/impg/hT7IzFN-nyVjPVqZLy4awthgL1Dg8RuMKv5Byw/F2ztWgGJ9ow.jpg?size=614x592&quality=96&proxy=1&sign=b5e1157c125f453d829d1dbb98a4a49c&type=album)

[Результат с "руб."](https://sun9-22.userapi.com/impg/-GDR8SrZJDpyW0pT_u1ZSUezuFyM2wsuvNCkPQ/5c8fEHhzZVM.jpg?size=586x590&quality=96&proxy=1&sign=e2fcd924573c1ea25c9341d3152654d0&type=album)

**Comment by eugene-borovov** [comment]
Присоединюсь к вопросу.

Мы в веб-хуках получаем разные данные по полям:
- Разное экранирование кавычек (html-сущность или slash)
- Поля дата и время приходят вместо локального времени (установленного в настройках) в UTC
- Поля типа created_at и updated_at могут иметь значения соответствующие 8500 лет (всего на тысячу больше чем от сотворения мира 😁 )

Встречается не так часто как в вопросе, но всё же неприятно.

**Comment by RodionovSlsUp** [comment]
@bessudnov
Поможете?

**Comment by bessudnov** [comment]
По символу валюты сейчас проблема должна быть решена, но нужен фидбек
По-разному возвращалась, из-за разных версий локализационных пакетов на разных серверах, сейчас везде одна версия


По хукам, нужны примеры, при каких действия приходят неверные данные

**Comment by viacheslav594** [comment]
@bessudnov Проблема не решена :(
[https://sun9-16.userapi.com/impg/f4ALr4XjRTaEFgwJp9njpvpdi2B_dZIO4l3UhQ/b36L9_oSA0U.jpg?size=718x948&quality=96&sign=e36feb04ffd70471e28026b35c487ea0&type=album](url)
[https://sun9-19.userapi.com/impg/orqKiejXdum--fUmd2LCdkfEKvR17-n8gR8LWA/MMQfqM4HlbU.jpg?size=778x926&quality=96&sign=199b0961bff235ce9a816434991daf3d&type=album](url)

**Comment by bessudnov** [comment]
Проверил, да проблема есть
Поставил задачу админам на приведение локалей к единообразию, но по срокам не скажу точно

**Comment by eugene-borovov** [comment]
@bessudnov вот примеры проблем в [хуках](https://disk.yandex.ru/d/Au4zVu1QhZ6qgA)

**Comment by bessudnov** [comment]
> @bessudnov Проблема не решена :(
> [Один](https://sun9-16.userapi.com/impg/f4ALr4XjRTaEFgwJp9njpvpdi2B_dZIO4l3UhQ/b36L9_oSA0U.jpg?size=718x948&quality=96&sign=e36feb04ffd70471e28026b35c487ea0&type=album)
> [Два](https://sun9-19.userapi.com/impg/orqKiejXdum--fUmd2LCdkfEKvR17-n8gR8LWA/MMQfqM4HlbU.jpg?size=778x926&quality=96&sign=199b0961bff235ce9a816434991daf3d&type=album)

Предварительный срок решения - середина-конец июня

**Comment by bessudnov** [comment]
Проблема с валютами исправлена

**Comment by bessudnov** [comment]
По хукам, тикет поставил, но пока не в работе.
Issue закрываю, так как тут не осталось чего-то связанного именно с библиотекой.
