### ISSUE TITLE
Получение удаленных сделок

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#254]
1. Невозможно с помощью SDL получить удаленные сделки c помощью методов Leads::get($filter,$with) / Leads::getOne($id,$with)
Передача [значения only_deleted](http://joxi.ru/KAxnlRQfZjODKm.jpg) в массиве with отфильтровывается, поскольку данное значение отсутствует в методе LeadModel::availableWith
https://github.com/amocrm/amocrm-api-php/blob/c9a3ad2b3bbea4a25b883d83c534748e1079a6dd/src/AmoCRM/Models/LeadModel.php#L975-L984
2. Если добавить значение only_deleted в LeadModel::availableWith , то список удаленного получить можно, однако большая часть полей приходит равной null, хоть в интерфейсе веб-версии AmoCRM они отображаются (поля Название сделки, Этап сделки), например
`{
                "id": 2602691,
                "name": null,
                "price": null,
                "responsible_user_id": null,
                "group_id": null,
                "status_id": null,
                "pipeline_id": null,
                "loss_reason_id": null,
                "created_by": null,
                "updated_by": 6795397,
                "created_at": null,
                "updated_at": 1615292420,
                "closed_at": null,
                "closest_task_at": null,
                "is_deleted": true,
                "custom_fields_values": null,
                "score": null,
                "account_id": 29324491,
                "_links": {
                    "self": {
                        "href": "https://yiji1.amocrm.ru/api/v4/leads/2602691"
                    }
                },
                "_embedded": {
                    "tags": [],
                    "companies": []
                }
            },
`
3. Если в параметре with вместе с only_deleted передать какое-либо валидное значение, апи ответит с кодом 500
4. Попытка фильтрация выдачи удаленных сделок с помощью передачи параметра query приводит удалению из выдачи всех результатов
5. Есть ли какой-то другой способ получить удаленные сделки с возможностью фильтрации результатов и чтения заполненных полей?

**Comment by bessudnov** [comment]
В ближайшем релизе будет доступно
