### ISSUE TITLE
Получить связи контакта

### ISSUE THREAD

**Issue by xlingvox** [amocrm/amocrm-api-php#256]
Пол дня пытаюсь разобраться как получить связи контакта (в моем случае сделки).
Получаем контакт (может быть несколько) по заданному поиску
`$userAmo = $this->apiClient->contacts()->get((new ContactsFilter())->setQuery($this->prideData));`
Прохожу по контакту, собираю нужные данные полей
`foreach ($userAmo as $contact) {
...
}`
Но никак не могу понять, как получить связи этих контактов  (в моем случае сделки). 
Или это делается не через связи а через поиск по 
`$apiClient->leads()`
С фильтром по Id контакта?

**Comment by xlingvox** [comment]
`			$leads = $this->apiClient
	->contacts()
	->getLinks(
		(new ContactModel())
			->setId($userData['id']),
		(new LinksFilter())
			->setToEntityType('leads')
	)
	->toArray();`

**Comment by eugene-borovov** [comment]
Попробуйте так:
```php
$userAmo = $this->apiClient->contacts()->get((new ContactsFilter())->setQuery($this->prideData), ContactModel::LEADS);
foreach ($userAmo as $contact) {  
   foreach($contact->getLeads() as $leadId) {
     $lead = $this->apiClient->leads()->getOne($leadId->getId());  
     // действия со сделкой ...
   }
}
```

Идентификаторы сделок можно собирать в пачки, либо отправлять всем скопом, так как `LeadCollection` сама режет запрос на страницы в 50 записей (поведение по умолчанию):
```php
$leads = $this->apiClient->contacts()->get((new LeadsFilter())->setIds(/* собранные из связи идентификаторы сделок */));
```

**Comment by xlingvox** [comment]
Проблема в том, что `$contact->getLeads()` не возвращает список сделок контакта (пробовал таким методом уже), метод срабатывает но ничего не возвращает.

**Comment by eugene-borovov** [comment]
Тогда действительно проблема )) 

Я так всегда делал. Ваш способ через линки даже не рассматривал, так как фильтрация не была подключена.

**Comment by xlingvox** [comment]
Еще поправлю свой ответ, по факту можно просто
`$this->apiClient->contacts()->getLinks((new ContactModel())->setId($userId))->toArray()` т.к. сортировка не работает `(new LinksFilter())->setToEntityType('leads')`, судя по всему нужно указать еще `setToEntityId`. #63
