### ISSUE TITLE
Фильтрация сделок по наименованию

### ISSUE THREAD

**Issue by makeroi** [amocrm/amocrm-api-php#258]
Для выполнения одной из задач необходима фильтрация сделок по вхождению строки в наименование. 
Фильтр представляет возможность только соотвествия полного, к сожалению это не очень подходит.
$filter = (new LeadsFilter())->setNames(['herms']);

Хотелось бы увидеть фильтр по вхождению, тем более есть фильтр query признан легаси.
Возможно добавить регулярные выражения, вроде:
$filter = (new LeadsFilter())->setNames(['\*herms\*']);

**Comment by bessudnov** [comment]
В данный момент для этой цели подойдет только query, по сути поисковый запрос, в ближайшем будущем в API точно не будет возможности подобной фильтрации

**Comment by bessudnov** [comment]
Пожелание перенес в вишлист по новому функционалу.

Issue тут закрываю
