### ISSUE TITLE
Unprocessable field type - tracking_data

### ISSUE THREAD

**Issue by webds** [amocrm/amocrm-api-php#259]
Ошибка при выполнение метода 
$id = int(29840051)   ИД сделки
array(1) {
  [0]=>
  string(8) "contacts"
}
>leads()->getOne($id, $with);

GET /api/v4/leads/29840051?with=contacts HTTP/1.1

"message": "Unprocessable field type - tracking_data",
    "exception": "AmoCRM\\Exceptions\\BadTypeException",
    "file": "/var/www/....../vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/CustomFieldsValues/Factories/CustomFieldValuesModelFactory.php",
    "line": 107,
    "trace": [

**Comment by bessudnov** [comment]
Вам необходимо обновить библиотеку до версии 0.4.х

**Comment by Maximryzhkov** [comment]
была старая библиотека, такая же ошибка возникала при обновлении сделки (все кейсы былы по обновлению).  обновил библиотеку, проблема осталась.

**Comment by webds** [comment]
> Вам необходимо обновить библиотеку до версии 0.4.х

!!! просто так она не обновляется.  
У кого ошибки, проверяйте composer.json свой
