### ISSUE TITLE
Экранирование пробелов при поиске

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#260]
При попытке установить сделкам фильтр query c значением, содержащим пробел происходит некорректное поведение.
Пробую так
```
$apiClient = AmoService::getInstance();
        $filter = (new LeadsFilter())->setPipelineIds([$pipelineId])->setLimit(250)->setQuery('Оман 400');
        $leads = $apiClient->leads()->get($filter);
```
        
Причем при прямом запросе в апи через браузер ошибка не воспроизводится. Пробовал экранировать пробел, но не помогло.
Подскажите, что не так?

**Comment by bessudnov** [comment]
В данный момент параметр query не совместим с другими фильтрами, если убрать setPipelineIds([$pipelineId]), то запрос пройдет корректно
