### ISSUE TITLE
Получение значка валюты (currency_symbol) из настроек (рубль)

### ISSUE THREAD

**Issue by xlingvox** [amocrm/amocrm-api-php#263]
Доброго дня, при получении из настроек значка валюты, приходят через раз (два, три, по разному) разные значения, если это рубль, то "руб", то значок "₽". Протестировал пару разных валют, вроде только с рублем так, не критично, но лучше чтобы приходило то что надо ))

p.s Попробовал еще Албанский лек, может возвращать как "lek", так и "L". С долларом и евро вроде все ок

**Comment by eugene-borovov** [comment]
Дублирует #251
