### ISSUE TITLE
Как удалить заказ ?

### ISSUE THREAD

**Issue by SergeyKhlopov** [amocrm/amocrm-api-php#264]
Здравствуйте, подскажите пожалуйста можно ли как то удалить заказ (сделку) ?

**Comment by eugene-borovov** [comment]
Через API удаление запрещено. см. #174

**Comment by SergeyKhlopov** [comment]
Понятно, спасибо

**Comment by vodnicearv** [comment]
https://github.com/amocrm/amocrm-api-php/issues/174
