### ISSUE TITLE
Можно ли при создании заказа указать его дату ?

### ISSUE THREAD

**Issue by SergeyKhlopov** [amocrm/amocrm-api-php#266]
Здравствуйте, подскажите пожалуйста, можно ли при создании заказа указать дату, что бы было не текущая дата у заказа, а к примеру вчерашняя ?

**Comment by viacheslav594** [comment]
@SergeyKhlopov  что вы имеете в виду? По вашему сообщению, к сожалению, ничего не понятно.

В терминологии амоцрм нет сущности "Заказ".

Если вы имеете в виду, можно ли создавать сделки задним числом? То да, можно. При создании можно установить дату создания.

```
$lead = (new LeadModel())
->setName('Мой чудесный заказ')
->setCreatedAt(time() - 86400);

$apiClient->leads->addOne($lead);
```

**Comment by SergeyKhlopov** [comment]
Спасибо, да, я имел ввиду задним числом =)
