### ISSUE TITLE
отложенное создание задачи

### ISSUE THREAD

**Issue by cy322666** [amocrm/amocrm-api-php#268]
**задача :** 

создать задачу через 3 минуты, со временем выполнения в течение часа

**документация :** 

created_at - Дата создания задачи, передается в Unix Timestamp. Не обязательный параметр                           

**код:** 

    $task = (new TaskModel())->setTaskTypeId(self::CUSTOM_TYPE_TASK)
              ->setText('Пришло сообщение от клиента')
              ->setCompleteTill(intval(Carbon::now()->addHour()->get('timestamp')))
              ->setEntityType(EntityTypesInterface::LEADS)
              ->setCreatedAt(intval(Carbon::now()->addMinutes(3)->get('timestamp')))
              ->setEntityId($lead->getId())
              ->setDuration(Carbon::SECONDS_PER_MINUTE * Carbon::MINUTES_PER_HOUR)
              ->setResponsibleUserId($lead->getResponsibleUserId());

      $tasksCollection = (new TasksCollection())->add($task);

      $task = $this->amoApi->tasks()->add($tasksCollection);
      
**передаваемый объект :** 

    AmoCRM\Models\TaskModel {#1218
      #id: null
      #responsibleUserId: 6580926
      #groupId: null
      #createdBy: null
      #updatedBy: null
      #createdAt: 1617120066 //тут все ок, текущее время + 3 минуты
      #updatedAt: null
      #accountId: null
      #duration: 3600
      #entityId: 12287782
      #entityType: "leads"
      #isCompleted: null
      #taskTypeId: 2157909
      #text: "Пришло сообщение от клиента"
      #result: null
      #completeTill: 1617123486
      #requestId: null
    }

**итог :** 

создается сразу. что то не так делаю или не работает?

**Comment by xlingvox** [comment]
@cy322666 Не знаю возможно ли передавать отложенные задачи, но если можно, могу предположить, что проблема может быть во временной зоне, т.к. время в unix нужно передавать со временной зоной как в настройках аккаунта. Такая проблема наблюдалась в доп. полях дата:время, если передавать без или неправильную временную зону, то время передается: время сервера +- время в amo

**Comment by viacheslav594** [comment]
Вам нужно указывать срок завершения равным **текущее время** + **три минуты** + **час**
А дюрейшн - **1 час**.

@cy322666
