### ISSUE TITLE
Отозван токен. Почему и что с этим делать?

### ISSUE THREAD

**Issue by Kordak** [amocrm/amocrm-api-php#269]
AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны (Token has been revoked) in /home/host1749169/vendor/amocrm/oauth2-amocrm/src/AmoCRMException.php:28 Stack trace: #0 /home/host1749169/vendor/amocrm/oauth2-amocrm/src/AmoCRM.php(163): AmoCRM\OAuth2\Client\Provider\AmoCRMException::errorResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /home/host1749169/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): AmoCRM\OAuth2\Client\Provider\AmoCRM->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #2 /home/host1749169/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #3 /home/host1749169/host1749169.hostland.pro/htdocs/www/test_amo/index.php(155): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #4 /home/host1749169/host1749169.hostland.pro/htdocs/www/cleanwl/public/form/back/salaryFormback.php(13): include('/home/host17491...') #5 /home/host1749169/host1749169.hostland.pro/htdocs/www/cleanwl/public/form/salaryForm.php(13): include('/home/host17491...') #6 {main}

**Comment by eugene-borovov** [comment]
Refresh токен долгоживущий, но одноразовый. Скорее всего у вас несколько инстансов работают от одного пользователя и при обновлении Access токена по Refresh токену, инстансы "воруют" друг у друга refresh токены. В общем кто первый встал, того и тапки.

Варианты решения:
* глобальное хранилище токенов для всех инстансов
* инстансы работают от имени разных пользователей.

**Comment by Kordak** [comment]
> Refresh токен долгоживущий, но одноразовый. Скорее всего у вас несколько инстансов работают от одного пользователя и при обновлении Access токена по Refresh токену, инстансы "воруют" друг у друга refresh токены. В общем кто первый встал, того и тапки.
> 
> Варианты решения:
> 
> * глобальное хранилище токенов для всех инстансов
> * инстансы работают от имени разных пользователей.

Где же взять информацию о том, как устроить это самое глобальное хранилище?

**Comment by eugene-borovov** [comment]
Место куда сохраняются токены и откуда читаются должно быть единым для всех инстансов вашего приложения, работающих из-под одного пользователя. Конкретная реализация на ваше усмотрение: сетевой диск, база данных или что-нибудь типа memcache.
