### ISSUE TITLE
Ошибка при добавлении DateCustomField

### ISSUE THREAD

**Issue by nkarpovich** [amocrm/amocrm-api-php#27]
Если в АМО тип кастомного поля - дата, то при добавлении занчения таким образом
```
$dateCustomFieldValuesModel = new DateCustomFieldValuesModel();
        $dateCustomFieldValuesModel->setFieldId($fieldId);
        $dateCustomFieldValuesModel->setValues(
            (new DateCustomFieldValueCollection())
                ->add((new DateCustomFieldValueModel())->setValue('2020-06-17'))
        );
        $customFieldsValuesCollection->add($dateCustomFieldValuesModel);
```
возвращается ошибка
`This value should be of type int`
Приходится добавлять через NumericCustomField, передавая timestamp

**Comment by YudovAlexei** [comment]
Вот так стоит дату добавлять.

```
<?php
$date = new DateTime("2020-06-17");
echo $date->getTimestamp(); // return (int) 1592377200
```

**Comment by bessudnov** [comment]
Сейчас необходимо передавать timestamp
В целом можно будет в будущем добавить поддержку DateTime, но пока что только timestamp

**Comment by nkarpovich** [comment]
> Вот так стоит дату добавлять.
> 
> ```
> <?php
> $date = new DateTime("2020-06-17");
> echo $date->getTimestamp(); // return (int) 1592377200
> ```

так можно добавлять, используя NumericCustomField. Если использовать DateCustomField, то неважно, как передавать -  /Models/CustomFieldsValues/ValueModels/DateCustomFieldValueModel.php:17 тут все равно преобразуется в timestamp

```
public function setValue($value): BaseCustomFieldValueModel
    {
        if (is_numeric($value)) {
            $this->value = $value;
        } else {
            $this->value = strtotime($value);
        }

        return $this;
    }
```

а дальше преобразуется в строку вида 'Y-m-d'. Поэтому, если посмотреть, какой json улетает в АМО, то там в таком виде дата:
```
 5 => 
      array (
        'field_id' => 298577,
        'field_code' => NULL,
        'values' => 
        array (
          0 => 
          array (
            'value' => '2020-06-23',
          ),
        ),
      ),

```

**Comment by nkarpovich** [comment]
> Сейчас необходимо передавать timestamp
> В целом можно будет в будущем добавить поддержку DateTime, но пока что только timestamp

Да это было бы здорово, но то о чем вы пишите, это уже другая фича - а я описывал проблему с DateCustomFieldValuesModel, по факту получается, что класс этот нерабочий (выше написал в комменте, судя по всему происходит конвертация временной метки в строку, а АМО ожидает на вход как раз метку, то есть число)

**Comment by bessudnov** [comment]
Всё, проверил, вижу проблему - в ближайшем релизе будет фикс
