### ISSUE TITLE
Поиск связанных с контактом лидов. Выдает ошибку.

### ISSUE THREAD

**Issue by dellirom** [amocrm/amocrm-api-php#271]
Пробую найти связанные с контактом с Lead-ыно в некоторых случаях выдает Exeption
Unprocessable field type - tracking_data
Cсылаясь на какое-то custom field

$contact ->id - есть в crm

$leads = $apiClient->leads()->get((new LeadsFilter())->setQuery($contact->id));

Это баг или возможно нужно указать какие-то параметры. Нигде не нашел возможного решения.

**Comment by eugene-borovov** [comment]
См.  #240 #243 #259

В общем нужно обновиться

**Comment by egorsmkv** [comment]
Backward compatibility на уровне, молодцы :+1:
