### ISSUE TITLE
Получить ID виджета, загруженного в текущую интеграцию/установленного у пользователя.

### ISSUE THREAD

**Issue by Skydescent** [amocrm/amocrm-api-php#272]
Здравствуйте!
В примерах есть получение коллекций всех виджетов ( $apiClient->widgets() ), или по коду, который есть только у публичных виджетов( $apiClient->widgets()->getOne('amo_asteriks'))
Мне нужно получить id приватного виджета загруженного в данную интеграцию или хотя бы коллекцию виджетов установленных у пользователя. Как это можно сделать?

**Comment by bessudnov** [comment]
Согласен, код интеграции тоже нужно бы вывести во вкладку Ключи и доступы в интерфейсе

Вообще виджет это дополнение интеграции (архив с JS кодом), если он загружен, то можно найти его, если в аккаунте в консоле браузера вызвать AMOCRM.widgets.list
Или кликнув на логотип интеграции -> скопировать url изображения. Полученная ссылка будет такого вида: https://XXX.amocrm.ru/upl/КОД_ВИДЖЕТА/current/widget/images/logo_main.png, из неё можно извлечь код виджета

**Comment by bessudnov** [comment]
В ближайшее время в последнюю версию (Весна 2021) будет отгружено исправление, в котором будет отображаться код виджета на вкладке Ключи и доступы, если загружен архив

**Comment by bessudnov** [comment]
Правки открыты на всех
