### ISSUE TITLE
Пример по работе с полем Мультисписок.

### ISSUE THREAD

**Issue by webds** [amocrm/amocrm-api-php#275]
Было бы хорошо, сделать все примеры по работе с полями.  

Или как минимум с полем Мультисписок.  

```
 $cfModel = new MultiselectCustomFieldValuesModel();
        $cfModel->setFieldId(FIELD_ID);
        $cfModel->setValues(
            (new MultiselectCustomFieldValueCollection())
                ->add((new MultiselectCustomFieldValueModel())->setValue(FIELD_VAL))
        );
```

Результат:
```
errors" => array:1 [
        0 => array:3 [
          "code" => "NotSupportedChoice"
          "path" => "custom_fields_values.3.values.0.value"
          "detail" => "The value you selected is not a valid choice."
        ]
        ]
```

Раньше же можно было отправлять ЗНАЧЕНИЕ поля.  
Сейчас только ID значения?  
Работает сейчас вот так

```
 $cfModel = new MultiselectCustomFieldValuesModel();
        $cfModel->setFieldId(FIELD_ID);
        $cfModel->setValues(
            (new MultiselectCustomFieldValueCollection())
               ->add((new MultiselectCustomFieldValueModel())->setEnumId(FIELD_V_ID))
        );
```

**Comment by viacheslav594** [comment]
Нет, сейчас отлично принимает значение. Но важно что бы оно полностью совладало, иначе - ошибка как у вас.
Проверьте пробелы, точки, строчные/прописные буквы, что все буквы в верной раскладке.

**Comment by webds** [comment]
> Нет, сейчас отлично принимает значение. Но важно что бы оно полностью совладало, иначе - ошибка как у вас.
> Проверьте пробелы, точки, строчные/прописные буквы, что все буквы в верной раскладке.

Проверял неоднократно, не работает.   Только если EnumId подставить . ->setValue(FIELD_VAL)  - не работает в поле Мультисписок.

**Comment by bessudnov** [comment]
Если подскажете ID аккаунта, в котором делается запрос, ID поля и значение, которое передаете, думаю смогу найти, где ошибка

Сейчас на вид ошибка, что переданное значение не заведено у передаваемого поля
