### ISSUE TITLE
Добавить возможность поддержки нестандартных типов задач

### ISSUE THREAD

**Issue by xlingvox** [amocrm/amocrm-api-php#277]
Хотелось бы видеть возможность добавления через api нестандартных типов задач, а не только "связаться" или "встреча". 
https://prnt.sc/11eytx8

**Comment by viacheslav594** [comment]
@xlingvox а в чем именно проблема? Насколько я понимаю, можно добавлять любые задачи, созаднные в аккаунте. Укажите айди задачи при ее создании.

Вот пример кода из интеграции

```
$tasksCollection = new TasksCollection();
        $task = new TaskModel();
        $task->setTaskTypeId($taskTypeId)
            ->setText($note)
            ->setCompleteTill(time() + ($duration * 60))
            ->setEntityType(EntityTypesInterface::LEADS)
            ->setEntityId($leadId)
            ->setResponsibleUserId($userId);
        $tasksCollection->add($task);

        try {
            $apiClient->tasks()->add($tasksCollection);
        } catch (AmoCRMApiException $e) {
            var_dump($e);
            die();
        }
```

**Comment by xlingvox** [comment]
@xlingvox да, но как получить этот список задач (как например список кастомных полей, тегов и т.п.), чтобы вывести для пользователей (чтобы они сами могли выбирать)?
p.s Вариант вручную переписать естественно отпадает :)

**Comment by viacheslav594** [comment]
https://www.amocrm.ru/developers/content/crm_platform/account-info

Вот тут.
В библиотеке не разу не использовал, под рукой нет, но подозреваю что-то вроде
 $apiClient->account()->getCurrent(['task_types']);

**Comment by xlingvox** [comment]
@viacheslav594 супер, действительно там все это есть, спасибо)
