### ISSUE TITLE
Можно ли сделку (lead) при создании отправлять в статус "неразобранное" ?

### ISSUE THREAD

**Issue by SergeyKhlopov** [amocrm/amocrm-api-php#280]
Здравствуйте, подскажите пожалуйста, я думал что когда создаю сделку могу просто сделать вот так:
```php
$lead->setStatusId(xxx); // Тут ID статуса "неразобранное"
```
И тогда сделка будет в статусе "неразобранное", но похоже это делается немного по другому, подскажите пожалуйста можно ли сделку прикрепить к статусу "неразобранное" и получается что бы и товары были в сделке и ещё сделка создаётся при оформлении заказа на сайте из корзины
заранее благодарю за ответ

**Comment by dura4kov** [comment]
через добавление неразобранного 
https://github.com/amocrm/amocrm-api-php/blob/master/examples/unsorted_actions.php#L58

**Comment by bessudnov** [comment]
Выше прислали пример, как можно добавить неразобранное, либо можно добавить сделку через комплексный метод
примеры тут - https://github.com/amocrm/amocrm-api-php/blob/master/examples/leads_complex_actions.php
Важно, при создании неразобранного, обязательно у сделки должна быть передана метаинформация
$lead->setMetadata(...)
