### ISSUE TITLE
Как поменять цены у товара внутри сделки?

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#282]
Товары прикрепляются к сделке, но у каждого товара может быть несколько цен: Розница, ОПТ 1, ОПТ 2, Дилерские...
для каждого типа цены в списке товаров выделено отдельное поле

как выбрать по какой цене считать товар в сделке?

![image](https://user-images.githubusercontent.com/14403446/115622671-d4c5ea80-a300-11eb-9e0a-170d8f44a4d0.png)

P.S. идеально было бы чтобы у менеджеров которые занимаются продажами, была возможность писать цену сразу внутри сделки
бывает что объемы в продажах большие, и делаются скидки...

**Comment by viacheslav594** [comment]
Ощущение, что это невозможно - разве что работа со своими собственными товарами, но если будет решение со стандартными, тегните меня

**Comment by vodnicearv** [comment]
даже возможность выбирать одну из цен было бы достаточно

![image](https://user-images.githubusercontent.com/14403446/116992950-78d76a80-acdf-11eb-823a-9857184e06dd.png)

**Comment by bessudnov** [comment]
API требуется небольшая доработка, чтобы могло принимать ID поля цена, в котором указана нужная цена
Думаю к середине мая отгрузим и выпустим обновление для библиотеки

**Comment by vodnicearv** [comment]
Отлично, будем ждать обновления

În vin., 7 mai 2021 la 02:11 Nikita ***@***.***> a scris:
