### ISSUE TITLE
Обновление токена

### ISSUE THREAD

**Issue by gergel0304** [amocrm/amocrm-api-php#289]
Использую get_token.php из папки examples для получения токена, все работает отлично, но через некоторое время (меньше суток) авторизация пропадает и появляется только при повторной ручной авторизации через форму. Я так понимаю, нужно как то автоматически обновить токен, подскажите, пожалуйста, как это сделать? 

**get_token.php** 
```
<?php

include_once __DIR__ . '/bootstrap.php';

session_start();

if (isset($_GET['referer'])) {
    $apiClient->setAccountBaseDomain($_GET['referer']);
}


if (!isset($_GET['code'])) {
    $state = bin2hex(random_bytes(16));
    $_SESSION['oauth2state'] = $state;
    if (isset($_GET['button'])) {
        echo $apiClient->getOAuthClient()->getOAuthButton(
            [
                'title' => 'Установить интеграцию',
                'compact' => true,
                'class_name' => 'className',
                'color' => 'default',
                'error_callback' => 'handleOauthError',
                'state' => $state,
            ]
        );
        die;
    } else {
        $authorizationUrl = $apiClient->getOAuthClient()->getAuthorizeUrl([
            'state' => $state,
            'mode' => 'post_message',
        ]);
        header('Location: ' . $authorizationUrl);
        die;
    }
} elseif (empty($_GET['state']) || empty($_SESSION['oauth2state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {
    unset($_SESSION['oauth2state']);
    exit('Invalid state');
}

/**
 * Ловим обратный код
 */
try {
    $accessToken = $apiClient->getOAuthClient()->getAccessTokenByCode($_GET['code']);

    if (!$accessToken->hasExpired()) {
        saveToken([
            'accessToken' => $accessToken->getToken(),
            'refreshToken' => $accessToken->getRefreshToken(),
            'expires' => $accessToken->getExpires(),
            'baseDomain' => $apiClient->getAccountBaseDomain(),
        ]);
    }
} catch (Exception $e) {
    die((string)$e);
}

$ownerDetails = $apiClient->getOAuthClient()->getResourceOwner($accessToken);

printf('Hello, %s!', $ownerDetails->getName());

```

и мой обработчик веб-хука (работает нормально после ручного получения через форму, но через какой то время перестает работать):
```
<?php

use AmoCRM\Collections\ContactsCollection;
use AmoCRM\Collections\CustomFieldsValuesCollection;
use AmoCRM\Collections\Leads\LeadsCollection;
use AmoCRM\Collections\LinksCollection;
use AmoCRM\Collections\NullTagsCollection;
use AmoCRM\Exceptions\AmoCRMApiException;
use AmoCRM\Filters\LeadsFilter;
use AmoCRM\Models\CompanyModel;
use AmoCRM\Models\ContactModel;
use AmoCRM\Models\CustomFieldsValues\TextCustomFieldValuesModel;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\NullCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\TextCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueModels\TextCustomFieldValueModel;
use AmoCRM\Models\LeadModel;
use League\OAuth2\Client\Token\AccessTokenInterface;
use AmoCRM\Helpers\EntityTypesInterface;
use AmoCRM\Collections\TasksCollection;
use AmoCRM\Models\TaskModel;

include_once __DIR__ . '/bootstrap.php';

$accessToken = getToken();

$apiClient->setAccessToken($accessToken)
    ->setAccountBaseDomain($accessToken->getValues()['baseDomain'])
    ->onAccessTokenRefresh(
        function (AccessTokenInterface $accessToken, string $baseDomain) {
            saveToken(
                [
                    'accessToken' => $accessToken->getToken(),
                    'refreshToken' => $accessToken->getRefreshToken(),
                    'expires' => $accessToken->getExpires(),
                    'baseDomain' => $baseDomain,
                ]
            );
        }
    );

$webhook_task = $_GET['task'];

$lead = $_REQUEST["leads"]["status"][0]["id"]; //  получаем ID сделки

$leadsService = $apiClient->leads();

$leadsCollection = $leadsService->getOne($lead);
$customFields = $leadsCollection->getCustomFieldsValues(); 

$responsible = $leadsCollection->getResponsibleUserId(); // получаем ID ответственного

if($webhook_task == "sklad") // этап КОНТРОЛЬ ДОСТАВКИ - МОСКВА (и СКЛАД) воронки ПРОДАЖИ
{
    if (!empty($customFields)) {
        $textField = $customFields->getBy('fieldId', 895577); // поле - СРОК ПОСТАВКИ
        $textFieldValueCollection = $textField->getValues();
    }

    $data = $textFieldValueCollection->toArray();
    $delivery_days = $data[0]["value"];
    
    $date = time() + 60 * 60 + 60 * 60 * 24 * $delivery_days;
    
    $task_text = "Проконтролировать поступление товара на склад";
    
    $task_type = 2192401; // КОНТРОЛЬ
}
elseif($webhook_task == "zayavka"){
    if (!empty($customFields)) {
        $textField = $customFields->getBy('fieldId', 895665); // поле - ПРИЕМ ЗАЯВОК
        $textFieldValueCollection = $textField->getValues();
    }

    $data = $textFieldValueCollection->toArray();
    $date = $data[0]["value"]; // прием заявок до этой даты 
    
    $date = $date - 60 * 60 * 24; // ставим срок выполнения - за один день
    
    $task_text = "Подать заявку на участие";
    
    $task_type = 2153584; // ПОДАЧА ЗАЯВКИ
}

//Создадим задачу
$tasksCollection = new TasksCollection();
$task = new TaskModel();

$task->setTaskTypeId($task_type) //тип задачи - Контроль
    ->setText($task_text)
    ->setCompleteTill($date)
    ->setEntityType(EntityTypesInterface::LEADS)
    ->setEntityId($lead)
    ->setResponsibleUserId($responsible);

$tasksCollection->add($task);

try {
    $tasksCollection = $apiClient->tasks()->add($tasksCollection);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}
```

**Comment by eugene-borovov** [comment]
Библиотека сама обновляет access токен по refresh токену в процессе работы. Время жизни refresh токена 30 дней. Почему у вас раз в сутки пропадает авторизация не ясно.

**Comment by viacheslav594** [comment]
Реферш токен живет действительно 30 суток, но аксесс токен - 24 часа.
Как вы видите при подключении вы дергаете функцию onAccessTokenRefresh, которая в случае необходимости обновления токена с помощью реферш токена получит новую связку аксесс токен-реферш токен (при этом старый реферш перестанет работать) и передаст его в лямбда-функцию. Далее вы эту связку сохраняете для дальнейшего использования с помощью функции saveToken(). Реализации этой функции у вас не увидел, возможно вы используете реализацию из примера и она сохраняет токен не туда, откуда вы его берете с помощью getToken().

Если у вас проблемы раз в сутки - точно проблема где то на этапе рефреша. Где именно (он не получается, он не сохраняется) не могу сказать.

Как я проверял работу реферш токена:
изменяем сохраненный работающий аксесс токен, если все ок при работе скрипта он должен замениться. если выпадает ошибка - проблема

**Comment by gergel0304** [comment]
@viacheslav594  да, я использую полностью пример, подозреваю, что вы правы. Как проконтролировать, куда идет сохранение токена? На это мне знаний не хватает(( Вы можете мне помочь, за вознаграждение? Если да, напишите, пожалуйста мне в телеграм: @gergel

**Comment by eugene-borovov** [comment]
> Далее вы эту связку сохраняете для дальнейшего использования с помощью функции saveToken(). Реализации этой функции у вас не увидел, возможно вы используете реализацию из примера и она сохраняет токен не туда, откуда вы его берете с помощью getToken().

Это явно один в один расширенный код из примеров. Так что сохранение токена должно быть в `examples/token_actions.php`. Если сутки токеном пользовались -- значит где-то его сохраняли. То есть проблема с refresh токеном. Он долго живущий, но одноразовый. 

@gergel0304 вы можете вместо вывода ошибок на экран писать их в файл лога? Я так понял у вас webhook и выводом ошибок на экран вы ничего не решите.

**Comment by gergel0304** [comment]
Да, выдает ошибку "Access token file not found" - да, я использую get_token.php из примера для получения токена, он не сохраняет токен? Как его тогда сохранить? В документации ни слова об этом. Очень хочу разобраться, готов заплатить за консультацию, @eugene-borovov вы мне сможете помочь? Я выше указывал телеграм, можем там списаться? Или оставьте ваши контакты.

**Comment by gergel0304** [comment]
> Как вы видите при подключении вы дергаете функцию onAccessTokenRefresh, которая в случае необходимости обновления токена с помощью реферш токена получит новую связку аксесс токен-реферш токен (при этом старый реферш перестанет работать) и передаст его в лямбда-функцию. Далее вы эту связку сохраняете для дальнейшего использования с помощью функции saveToken(). Реализации этой функции у вас не увидел, возможно вы используете реализацию из примера и она сохраняет токен не туда, откуда вы его берете с помощью getToken().

Файл **get_token.php** использует **bootstrap.php**:

`include_once __DIR__ . '/bootstrap.php';`

который в свою очередь состоит из:

```
<?php

use AmoCRM\Client\AmoCRMApiClient;
use Symfony\Component\Dotenv\Dotenv;

include_once __DIR__ . '/../vendor/autoload.php';

$dotenv = new Dotenv();
$dotenv->load(__DIR__ . '/.env.dist', __DIR__ . '/.env');

$clientId = $_ENV['CLIENT_ID'];
$clientSecret = $_ENV['CLIENT_SECRET'];
$redirectUri = $_ENV['CLIENT_REDIRECT_URI'];

$apiClient = new AmoCRMApiClient($clientId, $clientSecret, $redirectUri);

include_once __DIR__ . '/token_actions.php';
include_once __DIR__ . '/error_printer.php';
```

и тут как раз инклудится **token_actions.php** где есть **saveToken()**

```
<?php

use League\OAuth2\Client\Token\AccessToken;

define('TOKEN_FILE', DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'token_info.json');

/**
 * @param array $accessToken
 */
function saveToken($accessToken)
{
    if (
        isset($accessToken)
        && isset($accessToken['accessToken'])
        && isset($accessToken['refreshToken'])
        && isset($accessToken['expires'])
        && isset($accessToken['baseDomain'])
    ) {
        $data = [
            'accessToken' => $accessToken['accessToken'],
            'expires' => $accessToken['expires'],
            'refreshToken' => $accessToken['refreshToken'],
            'baseDomain' => $accessToken['baseDomain'],
        ];

        file_put_contents(TOKEN_FILE, json_encode($data));
    } else {
        exit('Invalid access token ' . var_export($accessToken, true));
    }
}

/**
 * @return AccessToken
 */
function getToken()
{
    if (!file_exists(TOKEN_FILE)) {
        exit('Access token file not found');
    }

    $accessToken = json_decode(file_get_contents(TOKEN_FILE), true);

    if (
        isset($accessToken)
        && isset($accessToken['accessToken'])
        && isset($accessToken['refreshToken'])
        && isset($accessToken['expires'])
        && isset($accessToken['baseDomain'])
    ) {
        return new AccessToken([
            'access_token' => $accessToken['accessToken'],
            'refresh_token' => $accessToken['refreshToken'],
            'expires' => $accessToken['expires'],
            'baseDomain' => $accessToken['baseDomain'],
        ]);
    } else {
        exit('Invalid access token ' . var_export($accessToken, true));
    }
}

```

**Comment by gergel0304** [comment]
`define('TOKEN_FILE', DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'token_info.json');`

Должен создаваться файл с токеном, правильно? У меня его нет

**Comment by eugene-borovov** [comment]
Да это путь до файла с токеном. В Linux будет `/tmp/token_info.json`, а вот в Windows будет `\tmp\token_info.json` (такого пути точно нет, да и `\t` может превратиться в символ табуляции).

Попробуйте выставить в значение:
`define('TOKEN_FILE', __DIR__ . DIRECTORY_SEPARATOR . 'token_info.json');` -- будет записан в текущую директорию
или 
`define('TOKEN_FILE', sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'token_info.json');` -- будет записан во временную директорию
или пропишите абсолютный путь до файла как вам удобнее.

После выполнения `get_token.php` по указанному пути должен быть `token_info.json`. Все примеры в библиотеке рабочие. Когда осваивал библиотеку просто добивался выполнения примера с нужной мне функциональностью, а потом адаптировал в приложение.

**Comment by gergel0304** [comment]
`define('TOKEN_FILE', __DIR__ . DIRECTORY_SEPARATOR . 'token_info.json');`

Проставил так, после ручной авторизации файл появился в директории, посмотрю, как будет вести себя вебхук завтра

**Comment by gergel0304** [comment]
еще вопрос: если вебхук используется несколькими пользователями, кто имеет доступ к воронке, их всех нужно авторизировать? или достаточно только администратора?

**Comment by gergel0304** [comment]
> `define('TOKEN_FILE', __DIR__ . DIRECTORY_SEPARATOR . 'token_info.json');`
> 
> Проставил так, после ручной авторизации файл появился в директории, посмотрю, как будет вести себя вебхук завтра

Работает! Похоже, проблема была в том, что файл не создавался изначально. Спасибо большое!

**Comment by eugene-borovov** [comment]
> еще вопрос: если вебхук используется несколькими пользователями, кто имеет доступ к воронке, их всех нужно авторизировать? или достаточно только администратора?

Авторизовывать нужно только пользователя, от имени которого будут совершаться действия в CRM. Вебхук авторизовывать не обязательно, так как это просто уведомление о событии в CRM. Если данных присылаемых с хуком хватает, то можно и без вызова CRM обойтись.

**Comment by gergel0304** [comment]
Спасибо!
