### ISSUE TITLE
Невозможно установить значение трек-поля `referer`

### ISSUE THREAD

**Issue by max-kut** [amocrm/amocrm-api-php#290]
При создании сделки с полем `referer` (создание с правильной структурой и идентификатором поля) прилетает 500 ошибка и сделка не создается
![изображение](https://user-images.githubusercontent.com/12911259/117054716-12743b80-ad23-11eb-9c51-5e59b52877ae.png)

**Comment by bessudnov** [comment]
Проблему решили, с конкретным аккаунтом проблема была
