### ISSUE TITLE
Подскажите алгоритм создания сделки с привязанным контактом(у контакта есть поле номер телефона)?

### ISSUE THREAD

**Issue by ArsenLen** [amocrm/amocrm-api-php#291]
Ребят, не могу понять, как сделать сделку с контактом, имя и номер которого я получаю из формы. Есть есть возможность, напишите код php.

**Comment by eugene-borovov** [comment]
Смотрите [пример](https://github.com/amocrm/amocrm-api-php/blob/8124ef4a530210f2e2dafee0d769f076f400d0f5/examples/leads_actions.php#L51)

**Comment by ArsenLen** [comment]
Все получилось! Пришлось городить большой объект.
