### ISSUE TITLE
Как добавить счета/покупки и юридические лица?

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#298]
Речь о возможностях которые появились в новой версий amoCRM.
Скорее всего это уже можно делать через API, но как это делать через библиотеку на php?

Будут-ли примеры?

P.S. вопрос касается вот этих сущностей
![image](https://user-images.githubusercontent.com/14403446/117583936-ade62180-b112-11eb-8958-dcc182786805.png)
![image](https://user-images.githubusercontent.com/14403446/117583958-c5bda580-b112-11eb-8663-588d114769bd.png)

**Comment by GrandWebmaster** [comment]
Пробовал добавить элемент к списку Счета/Покупки методами:
/api/v4/catalogs/{catalog_id}/elements
/api/v2/catalog_elements
ни один не прошел, код 400
 [id] => 0
 [code] => 400
 [message] => Error 285.
 [request_id] => 0
Сделал такой же запрос на добавление элемента для списка Товары - все прошло без проблем с тем же набором данных. Передавал только поле name
Выходит что эти методы нельзя применить к списку Счета/Покупки, либо у него есть некий набор полей обязательных для заполнения, о которых в документации ни слова?

**Comment by vodnicearv** [comment]
@GrandWebmaster выше @bessudnov сказал что в ближайшем обновление API будет поддерживаться работа с новыми функциями. На сколько знаю это будет на это неделе.

**Comment by bessudnov** [comment]
@GrandWebmaster ошибка, что написали, значит что не переданы все обязательные поля
В счетах обязательным для заполнения считает поле статус, которые по-сути является custom field

В библиотеку планирую завтра влить правки по счетам, документация на amocrm.ru/developers скорее всего в начале июня будет

**Comment by GrandWebmaster** [comment]
По коду ошибки 285 вроде так и есть. Опробовал передавать статус:
 [{"name":"Test","custom_fields":[{"id":616295,"values":[{"enum_id":908909}]}]}]
616295 - поле bill_status
Такая же ошибка

**Comment by GrandWebmaster** [comment]
UPD: удалось создать Счет с помощью старого метода апи v2 /api/v2/catalog_elements с передачей информации по Bill Status
Но не получается передать информацию по товарам. Информацию беру отсюда:
https://www.amocrm.ru/developers/content/crm_platform/custom-fields#items-example
Странно, что здесь нет product_id и bonus_points_per_purchase - эти поля есть при получении по апи информации о счете.
`{
          "id": 616303,
          "values": [
            {
              "value": {
                "sku": "34N4124",
                "description": "Описание товара",
                "unit_price": 10,
                "quantity": 2,
                "unit_type": "шт.",
                "discount": {
                  "type": "amount",
                  "value": 25
                },
                "vat_rate_id": 18,
                "external_uid": "uid"
              }
            }
          ]
        }`

Счет создается, но вместо товаров пустые ячейки, и ответ системы:
![изображение](https://user-images.githubusercontent.com/58393375/118102088-03efe900-b3e1-11eb-92be-59cadfd5136a.png)

**Comment by bessudnov** [comment]
Пример тела запроса, чтобы просто создать счет
```
POST /api/v4/catalogs/XXXX/elements
[{"name":"Счет #238","custom_fields_values":[{"field_code":"BILL_STATUS","values":[{"value":"Оплачен в аванс"}]}],"request_id":"0"}])
```

Пример запроса, чтобы создать счет с товарами
```
POST /api/v4/catalogs/XXXX/elements
[{"name":"Счет #238","custom_fields_values":[{"field_code":"BILL_STATUS","values":[{"value":"Оплачен в аванс"}]},{"field_code":"ITEMS","values":[{"value":{"sku":"Артикул товара","description":"Описание товара","unit_price":150,"quantity":10,"unit_type":"кг","discount":{"type":"amount","value":15.15},"vat_rate_id":null,"vat_rate_value":20,"external_uid":"XXX","product_id":null,"bonus_points_per_purchase":20}}]}],"request_id":"0"}]
```

Примеры для новой версии библиотеки
https://github.com/amocrm/amocrm-api-php/blob/bed15afb9465d0cf54736346ecba2e27c278ce2e/examples/invoices_actions.php

**Comment by GrandWebmaster** [comment]
Благодарю за примеры, с изменением field_id на field_code удалось передать товары в Счет
