### ISSUE TITLE
API методы платформы

### ISSUE THREAD

**Issue by lecbit** [amocrm/amocrm-api-php#299]
Почему некоторые запросы отбрасывает на прошлую страницу?
Например username.amocrm.ru/api/v4/leads/unsorted, username.amocrm.ru/api/v4/companies

**Comment by bessudnov** [comment]
Можно больше подробностей?

Что значит отбрасывают на прошлую страницу? Есть ли пример кода?

**Comment by bessudnov** [comment]
Похоже, что просто приходит http код ответа - 204
Сущностей не найдено

**Comment by lecbit** [comment]
Хм, действительно. Но почему нельзя оставить пользователя на той странице, куда он хотел попасть?

**Comment by bessudnov** [comment]
Это стандартное поведение браузера, на которое API не влияет
При получении 204, браузер возвращает но меняет контент уже загруженной страницы
