### ISSUE TITLE
Users->get приводит к RightModel::setStatusRights TypeError

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#3]
## Expected Behavior
Вызов метода get сервиса users возвращает коллекцию пользователей аккаунта

## Current Behavior
При попытке получения списка пользователей с помощью вызова метода get у экземпляра класса AmoCRM\EntitiesServices\Users происходит ошибка

> TypeError: Argument 1 passed to AmoCRM\Models\Rights\RightModel::setStatusRights() must be of the type array, null given, called in /.../amocrm/amocrm-api-library/src/AmoCRM/Models/Rights/RightModel.php on line 446 and defined in /.../amocrm/amocrm-api-library/src/AmoCRM/Models/Rights/RightModel.php:294
> Stack trace:
> 0 /.../amocrm/amocrm-api-library/src/AmoCRM/Models/Rights/RightModel.php(446): AmoCRM\Models\Rights\RightModel->setStatusRights(NULL)
> 1 /.../amocrm/amocrm-api-library/src/AmoCRM/Models/UserModel.php(76): AmoCRM\Models\Rights\RightModel::fromArray(Array)
> 2 /.../amocrm/amocrm-api-library/src/AmoCRM/Collections/BaseApiCollection.php(53): AmoCRM\Models\UserModel::fromArray(Array)
> 3 [internal function]: AmoCRM\Collections\BaseApiCollection::AmoCRM\Collections\{closure}(Array)
> 4 /.../amocrm/amocrm-api-library/src/AmoCRM/Collections/BaseApiCollection.php(50): array_map(Object(Closure), Array)
> 5 /.../amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(103): AmoCRM\Collections\BaseApiCollection::fromArray(Array)
> 6 /.../amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(89): AmoCRM\EntitiesServices\BaseEntity->createCollection(Array)
> 7 /...: AmoCRM\EntitiesServices\BaseEntity->get()

## Environment
PHP 7.3
amoCRM API Client 0.1.1
в аккаунте один пользователь - создатель\администратор аккаунта

## Possible sollution
В RightModel::fromArray  добавить проверку на !empty($rights['status_rights']) перед вызовом setStatusRights

**Comment by bessudnov** [comment]
Исправлено в релизе 0.2
