### ISSUE TITLE
Ошибка при получении пользователей с параметром with=role

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#304]
Использую вот такой код (под Laravel)
`return response()->success($apiClient->users()->get(null, ['role', 'group'])->toArray());`

Без аргумента role все ок

Получаю ошибку
<img width="1438" alt="Снимок экрана 2021-05-13 в 22 40 56" src="https://user-images.githubusercontent.com/72909976/118178167-4b579300-b43c-11eb-8cd0-48aeba3c39c5.png">

Подскажите, в чем дело?

**Comment by bessudnov** [comment]
Правки в master
В ближайшем релизе, который будет или завтра или в пн будет правка
