### ISSUE TITLE
Модели фильтров для пользователей и других сущнстей

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#305]
Столкнулся с тем, что модели фильтров реализованы только для основных энтити (LeadsFilter, ContactsFilter....). Для некоторых сущностей нет фильтров - например Users (есть и другие сущности, сейчас не припомню). Технически можно использовать LeadsFilter для пользователей (задача - увеличение лимита/офсета). Но это не верно с точки зрения архитектуры ООП. С другой стороны нельзя использовать и родителя этих фильтров - BaseEntityFilter - он абстрактный.

**Comment by bessudnov** [comment]
В ближайшем релизе добавим PagesFilter, который можно использовать для постранички в любом сервисе, даже в котором нет никаких фильтров
