### ISSUE TITLE
добавление нескольких тегов в сделку

### ISSUE THREAD

**Issue by Alfatyhin** [amocrm/amocrm-api-php#308]
При комплексном создании сделки добавляется только первый тег 

 $lead = new LeadModel();

        if (!empty($amoData['tags'])) {
            //Создадим тег
            $tagsCollection = new TagsCollection();

            foreach ($amoData['tags'] as $item) {
                if ($item) {
                    $tagModel = (new TagModel())->setName($item);
                    $tagsCollection = $tagsCollection->add($tagModel);
                }
            }
            $lead->setTags($tagsCollection);

        }

на выходе var_damp показывает 
object(AmoCRM\Collections\TagsCollection)#58 (3) {
  ["data":protected]=>
  array(3) {
    [0]=>
    object(AmoCRM\Models\TagModel)#59 (3) {
      ["id":protected]=>
      NULL
      ["name":protected]=>
      string(5) "Cache"
      ["requestId":protected]=>
      NULL
    }
    [1]=>
    object(AmoCRM\Models\TagModel)#60 (3) {
      ["id":protected]=>
      NULL
      ["name":protected]=>
      string(17) "В подарок"
      ["requestId":protected]=>
      NULL
    }
    [2]=>
    object(AmoCRM\Models\TagModel)#61 (3) {
      ["id":protected]=>
      NULL
      ["name":protected]=>
      string(25) "1x - Healthy sweet box #3"
      ["requestId":protected]=>
      NULL
    }
  }
  ["nextPageLink":"AmoCRM\Collections\TagsCollection":private]=>
  NULL
  ["prevPageLink":"AmoCRM\Collections\TagsCollection":private]=>
  NULL
}

но тег в амо только первый

**Comment by bessudnov** [comment]
Точно бага, записал в план работ на ближайшее время, думаю в начале-середине следующей недели будет исправление

**Comment by bessudnov** [comment]
Проблему решили, исправление отгружено
