### ISSUE TITLE
Фильтрация задач по типу

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#309]
Заметил баг, не работает фильтр по типу задачи.
Получаю задачи, указав тип (->setTaskTypeId(1))

Код:
```
$filter = (new TasksFilter())->setEntityType('leads')->setEntityIds($leadId)->setIsCompleted(false)->setTaskTypeId(1);
        $foundTasks = $taskService->get($filter);
        dd($foundTasks);
```

На выходе получаю то же самое, что и без ->setTaskTypeId(1).

<img width="1440" alt="Снимок экрана 2021-05-14 в 12 50 22" src="https://user-images.githubusercontent.com/72909976/118253759-f4d96b80-b4b2-11eb-9fa5-db3c874965f5.png">

Даже понятна ошибка - по документации (https://www.amocrm.ru/developers/content/crm_platform/tasks-api) фильтр по айди задачи выглядит как **filter[task_type]**, библиотека же подставляет **filter[task_type_id]** - видно на скрине dump&die

**Comment by bessudnov** [comment]
В ближайшем релизе будет правка, уже в мастере
