### ISSUE TITLE
setService() в ServiceMassageNote

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#311]
Подскажите, на что влияет параметр Service в ServiceMassageNote?

Использую вот такой код:

```
$note = (new ServiceMessageNote())
            ->setService('test')
            ->setText('Отправили проздравительную смс')
            ->setEntityId(23492969);
        $apiClient->notes(EntityTypesInterface::CONTACTS)->addOne($note);
```

Примечание выглядит так: (Указывается название виджета, а не то что я указал в setService).

<img width="891" alt="Снимок экрана 2021-05-15 в 18 51 22" src="https://user-images.githubusercontent.com/72909976/118370048-8c6fb480-b5ae-11eb-9068-95d40231cbb7.png">

Если он ни на что не влияет, почему тогда этот параметр обязателен? (Без него Response validation error)

**Comment by bessudnov** [comment]
Раньше service отображался на месте названия интеграции, в релизе Осень 2020 стали отображать название интеграции, которая добавляет примечание
Запишу задачку в бэклог

**Comment by viacheslav594** [comment]
Уточните, какая именно механика планируется? Вернуть отображение service, или удалить метод?

С моей стороны есть пожелание вернуть service, когда интеграция крупная, к примеру, это какой-то мастер-виджет, подключающий модули - намного удобнее видеть название конкретного модуля или механики (то есть service), нежели название виджета.

**Comment by bessudnov** [comment]
Тут точно сказать пока не могу, но я больше склоняюсь к вернуть отображение service

**Comment by bessudnov** [comment]
На днях будет правка отгружена, чтобы отображалось service в фиде карточки

**Comment by bessudnov** [comment]
Исправление открыто на всех пользователей
