### ISSUE TITLE
как привязать существующий лид к неразобранному ?

### ISSUE THREAD

**Issue by 4nndr01d** [amocrm/amocrm-api-php#312]
Пытаюсь привязать лид к неразобранному но в итоге получаю только ошибку с заголовком Only chats and mail.

**Comment by 4nndr01d** [comment]
так же если пробовать сделать запрос как это указано в api , то получаешь очень информативный ответ Invalid request data

**Comment by bessudnov** [comment]
А можете пример запроса предоставить?
Возможность привязки есть только у неразобранного типа чат и почта

**Comment by bessudnov** [comment]
Нет ответа более месяца. Issue будет закрыт. Откройте повторно, при необходимости.
