### ISSUE TITLE
Ошибка 400 при связи инвойса и лида

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#314]
Инвойс создаеться отлично, спасибо что добавили такую возможность в API!
Но как привязать его к сделке?

Пробую так:
```
$this->apiClient->leads()->link($lead, (new LinksCollection())->add($invoice));
```
но получаю ошибку `400 Invalid request`

**Comment by vodnicearv** [comment]
@bessudnov можете подсказать как делать связь между инвойсом и лидом?

**Comment by vodnicearv** [comment]
посмотрел как создаеться инвойс в web версии, и нашел там запрос который как раз делает связь, вот он:
![image](https://user-images.githubusercontent.com/14403446/118826265-02805e00-b8c4-11eb-97a7-bd94f8cb1327.png)

и попробовал вот такой вариант:

```
$link = new LinkModel();
$link->setToEntityId($invoice->getId());
$link->setToEntityType('catalog_elements');
$link->setEntityId($lead->getId());
$link->setEntityType('leads');
$link->setMetadata([
    'from_catalog_id' => (int) config('services.amocrm.pipeline_id'),
    'to_catalog_id' => (int) config('services.amocrm.fields.invoices_list_id'),
    'quantity' => 1,
    'price_id' => null,
]);
$this->apiClient->leads()->link($lead, (new LinksCollection())->add($link));
```
но получаю ответ 400
вот такой:
```
array:1 [
  0 => array:2 [
    "request_id" => "0"
    "errors" => array:2 [
      0 => array:3 [
        "code" => "FieldNotExpected"
        "path" => "metadata.from_catalog_id"
        "detail" => "This field was not expected."
      ]
      1 => array:3 [
        "code" => "FieldNotExpected"
        "path" => "metadata.to_catalog_id"
        "detail" => "This field was not expected."
      ]
    ]
  ]
]
```
и если убираю setMetaData то получаю просто 400 ошибку, без сообщений о валидации

**Comment by vodnicearv** [comment]
еще пробовал добавить в запросе поля from_catalog_id и to_catalog_id
https://github.com/global-fashion/amocrm-api-php/commit/ea9fdc07e151db4de86ff9c788cfc98f86585648

но, уже приходит такая ошибка:
```
array:1 [
  0 => array:2 [
    "request_id" => "0"
    "errors" => array:2 [
      0 => array:3 [
        "code" => "FieldNotExpected"
        "path" => "from_catalog_id"
        "detail" => "This field was not expected."
      ]
      1 => array:3 [
        "code" => "FieldNotExpected"
        "path" => "to_catalog_id"
        "detail" => "This field was not expected."
      ]
    ]
  ]
]
```

**Comment by bessudnov** [comment]
В выходные или в начале следующей недели проверю и точно скажу, что не так, скорее всего или API или библиотеку нужно будет подпилить немного)

**Comment by vodnicearv** [comment]
отлично, спасибо!)
буду ждать

**Comment by bessudnov** [comment]
Сейчас после создания в вернувшуюся модель $invoice не установлен ID списка.
Фикс завтра выпущу, пока можно задать ID списка принудительно перед линковкой:
$invoice->setCatalogId(XXX);

**Comment by vodnicearv** [comment]
связи работают, спасибо!
