### ISSUE TITLE
Некорректный запрос

### ISSUE THREAD

**Issue by Alfatyhin** [amocrm/amocrm-api-php#315]
Внезапно перестала работать интеграция. Сначала была ошибка 

` Uncaught BadMethodCallException: Required parameter not passed: "refresh_token"`

добавил его в массив для апи клиента (хотя до этого всё прекрасно работало)

Теперь другая ошибка Не корректный запрос. И я не могу понять что именно не так..

```
Fatal error:  Uncaught AmoCRM\Exceptions\AmoCRMoAuthApiException: {"hint":"Token has been revoked","title":"Некорректный запрос","type":"https://developers.amocrm.ru/v3/errors/OAuthProblemJson","status":401,"detail":"В запросе отсутствует ряд параметров или параметры невалидны"} in /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/OAuth/AmoCRMOAuth.php:148
Stack trace:
#0 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(117): AmoCRM\OAuth\AmoCRMOAuth->getAccessTokenByRefreshToken(Object(League\OAuth2\Client\Token\AccessToken))
#1 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(369): AmoCRM\Client\AmoCRMApiRequest->refreshAccessToken()
#2 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(420): AmoCRM\Client\AmoCRMApiRequest->get('https://takebre...', Array, Array, true)
#3 /var/www/u128 in /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/OAuth/AmoCRMOAuth.php on line 148
```

**Comment by eugene-borovov** [comment]
> Token has been revoked

- Протух refresh-токен (наиболее вероятно)
- Была отозвана интеграция для этого пользователя

**Comment by Alfatyhin** [comment]
да, сейчас заметил. Обновил вручную, теперь 

``
Fatal error:  Uncaught AmoCRM\Exceptions\AmoCRMoAuthApiException: Unauthorized in /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php:437
Stack trace:
#0 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(505): AmoCRM\Client\AmoCRMApiRequest->checkHttpStatus(Object(GuzzleHttp\Psr7\Response), Array)
#1 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(414): AmoCRM\Client\AmoCRMApiRequest->parseResponse(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(420): AmoCRM\Client\AmoCRMApiRequest->get('https://takebre...', Array, Array, true)
#3 /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(134): AmoCRM\Client\AmoCRMApiRequest->get('https://takebre...', Array)
#4 /var/www/u1288169/data/www/app/Model/Amo.php(609): AmoCRM\EntitiesServices\BaseEntity->ge in /var/www/u1288169/data/www/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php on line 437

```

**Comment by eugene-borovov** [comment]
Видимо неудачно обновили, так как ругается попытка обновить токен перед запросом API. 

Добейтесь выполнения [примера](https://github.com/amocrm/amocrm-api-php/blob/652e4cc43028b944668e677733ac3582cf4ed7b3/examples/get_token.php#L44) (код можно вставить напрямую из настройки интеграции). Я себе на базе этого примера консольную команду сделал для обновления токена.

**Comment by Alfatyhin** [comment]
Спасибо. Опять заработало )). Я сделал кнопку для запуска интеграции согласно документации. И обновление токена реализовал своё. Сравниваю Дату записи токена в файл + время жизни токена с текущей, отлично всё работало несколько месяцев ))
