### ISSUE TITLE
Смена статуса счёта

### ISSUE THREAD

**Issue by bbik52** [amocrm/amocrm-api-php#316]
Здравствуйте. Подскажите пожалуйста, как поменять статус у существующего счёта с "создан" на "оплачен"?

Не нашел информации по этому вопросу. В примерах только установка статуса для нового счёта.
Спасибо.

![image](https://user-images.githubusercontent.com/25558907/119006151-c965ed80-b998-11eb-8628-67e5291bf979.png)

**Comment by bbik52** [comment]
Нашел решение сам. 
Возможно кому то поможет пока нет информации в примерах и документации:

```php
$invoice_id = 123456; // id счёта

// получаем каталог счетов
$catalogsFilter = new CatalogsFilter();
$catalogsFilter->setType(EntityTypesInterface::INVOICES_CATALOG_TYPE_STRING);
$invoicesCatalog = $apiClient->catalogs()->get($catalogsFilter)->first();

// получаем объект самого счета
$invoice = $apiClient->catalogElements($invoicesCatalog->getId())->getOne($invoice_id);

// получаем уже существующую коллекцию полей счета для дальнейшего модифицирования
$invoiceCustomFieldsValues = $invoice->getCustomFieldsValues();

// задаем новый статус счёта
$statusCustomFieldValueModel = new SelectCustomFieldValuesModel();
$statusCustomFieldValueModel->setFieldCode(InvoicesCustomFieldsEnums::STATUS);
$statusCustomFieldValueModel->setValues(
	(new SelectCustomFieldValueCollection())
		->add((new BaseEnumCustomFieldValueModel())
		->setValue('Оплачен')) //Текст должен совпадать с одним из значений поля статус
);
$invoiceCustomFieldsValues->add($statusCustomFieldValueModel);

// обновим счёт (передаем уже мофицированный объект $invoice)
$apiClient->catalogElements($invoicesCatalog->getId())->updateOne($invoice);
```

**Comment by bbik52** [comment]
Еще было бы очень неплохо прописать варианты значений (Создан, Просмотрен, Оплачен частично, Оплачен) куда нибудь в константы

**Comment by vodnicearv** [comment]
@bbik52 в константы не вариант, их можно менять-же
![image](https://user-images.githubusercontent.com/14403446/119239523-53a58180-bb52-11eb-86bc-9481564160ee.png)

**Comment by bbik52** [comment]
@vodnicearv не знал что можно поменять название.
Тогда это проблема и апи еще сырое, потому что если передавать статус 'paid' из константы AmoCRM\Enum\InvoicesCustomFieldsEnums::BILL_STATUS_PAID - вылетает 400 ошибка (Response has validation errors)

@bessudnov Добрый день. Есть какое то универсальное решение на данный момент, как поменять статус счета в рамках тиражного решения? Когда в каждом аккаунте статусы могут называться по разному

**Comment by vodnicearv** [comment]
Полезно было бы иметь метод для получения списка статусов.

**Comment by bessudnov** [comment]
```
//Обновим статус счета, без изменения других полей
$invoiceForUpdate = (new CatalogElementModel())
    ->setId($newInvoice->getId())
    ->setCatalogId($invoicesCatalog->getId())
    ->setCustomFieldsValues(
        (new CustomFieldsValuesCollection())
            ->add(
                (new SelectCustomFieldValuesModel())
                    ->setFieldCode(InvoicesCustomFieldsEnums::STATUS)
                    ->setValues(
                        (new SelectCustomFieldValueCollection())
                            ->add((new SelectCustomFieldValueModel())->setValue('Оплачен')) //Текст должен совпадать с одним из значений поля статус
                    )
            )
    );

try {
    $updatedInvoice = $catalogElementsService->updateOne($invoiceForUpdate);
    echo 'ID обновленного счета - ' . $updatedInvoice->getId();
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

```


 Сегодня обновлю пример с этим примером и с получением значений поля статус

**Comment by bbik52** [comment]
@bessudnov Спасибо. Обратил внимание что в crm статус "создан" и "оплачен" можно переименовать, но невозможно удалить.
Было бы всё таки неплохо допилить апи что бы она понимала статус 'paid' и 'created' как это задано в константах InvoicesCustomFieldsEnums.
Тогда можно отмечать счёт оплаченным без дополнительных запросов к апи.

**Comment by bessudnov** [comment]
Есть в бэклоге задачка, чтобы у enum можно было задавать через API символьные коды и потом оперировать ими, но пока не дошли до этого руки

**Comment by bessudnov** [comment]
Обновил примеры
https://github.com/amocrm/amocrm-api-php/blob/1763a5c13ddb99f5bba3f6b7b0083c5ded6da43b/examples/invoices_actions.php

**Comment by bbik52** [comment]
> Есть в бэклоге задачка, чтобы у enum можно было задавать через API символьные коды и потом оперировать ими, но пока не дошли до этого руки

Доброго дня. Нет новостей по этой задаче? 
Т.к. делаю тиражное решение, весь процесс встал на этом моменте.

Думаю у коллег которые занимаются другими тиражными решениям по эквайрингам - те же проблемы.

**Comment by bbik52** [comment]
@bessudnov UPD
Всё еще актуальная проблема которая мешает выкатиться

**Comment by bessudnov** [comment]
Пока задача по enum не в работе
Сейчас пока лишь оперировать названиями или ID значений

**Comment by bbik52** [comment]
> Пока задача по enum не в работе
> Сейчас пока лишь оперировать названиями или ID значений

А как оперировать в рамках тиражного решения, когда может быть сотни установок и у всех по разному могут называться статусы?
Есть какие то методы для получения статусов?

**Comment by bessudnov** [comment]
Да, конечно
Статус это по-сути доп поле
https://XXX.amocrm.ru/api/v4/catalogs/{CATALOG_ID}/custom_fields

**Comment by bbik52** [comment]
> Да, конечно
> Статус это по-сути доп поле
> [https://XXX.amocrm.ru/api/v4/catalogs/{CATALOG_ID}/custom_fields](https://XXX.amocrm.ru/api/v4/catalogs/%7BCATALOG_ID%7D/custom_fields)

@bessudnov Никита, добрый день.
Получил поля, но там нет ничего кроме id, названия и сортировки.
Отсутствуют какие либо отличительные признаки (code хотя б) для статусов "Создан" и "Оплачен"
Учитывая что на сравнение названий опираться нельзя, т.к. оно может быть везде разным - единственное решение которое видится на данный момент - это делать дополнительную настройку в платежном виджете, где будет selectbox со списком статусов счетов, и на каждом конкретном портале будут выбирать какой статус устанавливать после оплаты.
И эту настройку нужно дополнительно еще хранить в бд на стороне бекенда, а это лишняя головная боль и усложнение юзабилити, вместо того что бы просто передать код поля 'paid'... =(

Плюс пока что непонятно что делать в каких то нетиповых ситуациях, когда например будет попытка установить значение того поля, которое было удалено после настройки виджета.

Выходит сейчас апи немного сырое. Может быть есть какие то более простые способы решить эту задачу для тиражного решения? Что-то универсальное, без костылей и лишних настроек... 

Или может рассмотрите возможность поднять приоритет и сроки по этой задаче?
Если не установка статуса через code, которую обсуждали выше, то хотя бы добавить поля code => created и code => paid для статусов в методе  получения кастомных полей каталога, что бы можно было как то идентифицировать эти поля вне зависимости от названия.

Это очень помогло бы избежать лишних костылей. Спасибо
![image](https://user-images.githubusercontent.com/25558907/121379363-a05bcb80-c94c-11eb-9797-0482578d54e1.png)

**Comment by bbik52** [comment]
@bessudnov потестил и обратил внимание что при смене порядка в настройках (в самой crm), меняется только sort.
"Создан" всегда остается первым элементом в массиве, а "Оплачен" всегда последним.

Правильно ли я нащупал решение, и могу ли я ориентироваться на то, что вне зависимости от порядка и количества статусов, статус "Оплачен" будет всегда последним элементом массива?
