### ISSUE TITLE
Можно тут прислать ошибки с web версии amoCRM?

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#319]
Можно отправить ошибки из web версии amoCRM тут в issues?
Просто с поддержкой иногда трудно общаться, они тяжело понимают в чем дело.

**Comment by vodnicearv** [comment]
![image](https://user-images.githubusercontent.com/14403446/119237723-ef30f500-bb46-11eb-8c3b-84ab5aed3468.png)
в счетах (invoices) которые добавлены через API, итоговая стоимость не считаеться, если менять что-то через web версию, только тогда появятся стоимсоть

**Comment by vodnicearv** [comment]
в вкладке товары, можно искать товары по артикулу (очень удобно)
![image](https://user-images.githubusercontent.com/14403446/119237770-43d47000-bb47-11eb-8cb9-90a496029a1c.png)

![image](https://user-images.githubusercontent.com/14403446/119237807-6d8d9700-bb47-11eb-9b1f-f9c934082ec9.png)

а в счетах, поиск товаров работает только по названию

было бы здорово чтобы поиск работал и по артикулу, и еще, чтобы при выборе одного товара из подсказок, чтобы поля в таблице заполнялись автоматически (артикул, название, цена)

**Comment by bessudnov** [comment]
> ![image](https://user-images.githubusercontent.com/14403446/119237723-ef30f500-bb46-11eb-8c3b-84ab5aed3468.png)
> в счетах (invoices) которые добавлены через API, итоговая стоимость не считаеться, если менять что-то через web версию, только тогда появятся стоимсоть

https://github.com/amocrm/amocrm-api-php/blob/652e4cc43028b944668e677733ac3582cf4ed7b3/examples/invoices_actions.php#L196

В данный момент это работает так

**Comment by bessudnov** [comment]
А вот баги по интерфейсу точно не стоит писать в Issue тут, такое нужно в ТП
То что не работает по артикулу поиск и не подставляются все значения - вообще выглядит как баг интерфейса, но такое только через поддержку можно передать

**Comment by viacheslav594** [comment]
@bessudnov к сожалению, есть проблема - поддержка действительно часто не понимает, переспрашивает по 6-8 раз (даже в техаккаунте) и тд. Никита, может быть есть возможность организации какого то места, где вы могли бы принимать баги по интерфейсу?

**Comment by bessudnov** [comment]
В данный момент это место только тех поддержка, но обязательно обратим внимание на ваш комментарий, если будут вносится изменения в процессы тех поддержки

**Comment by vodnicearv** [comment]
@bessudnov Никита добрый день
поиск товаров в счета и покупки не работает корректно

не ищет по артикулу и даже по названию ищет не всегда (хотя товары точно есть в списке Товаров)

**Comment by vodnicearv** [comment]
вроде говорили что это исправиться и добавили в виш-лист
но прошло уже несколько месяцев и ничего не было исправлено
