### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by lifors** [amocrm/amocrm-api-php#321]
Написано установить с помощью composer, но как проходит сама установка?

**Comment by bessudnov** [comment]
После того, как вы добавили пакет через композер, если раньше у вас не было зависимостей, которые затянуты через Composer, то нужно "заинклюдить" файл с зависимости в ваш скрипт/систему
include_once __DIR__ . '/vendor/autoload.php';

Дальше необходимо инициализировать библиотеку, как это сделать - есть в Readme
https://github.com/amocrm/amocrm-api-php#%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F
