### ISSUE TITLE
Как фильтровать лиды по кастомным полям ?

### ISSUE THREAD

**Issue by SupchickCode** [amocrm/amocrm-api-php#322]
Вопрос вот в чем, есть фильтры для сделок у этих фильтров есть метод setCustomFieldsValues который примет массив с данными. Как должны выглядить эти данные ?

Пример:
$filter = new LeadsFilter();
$fields = [];
$filter->setCustomFieldsValues($fields);

Какие данные должны быть в $fields, пример структуры массива.

**Comment by vodnicearv** [comment]
https://github.com/amocrm/amocrm-api-php/issues/313

**Comment by SupchickCode** [comment]
Блин, соррян и правда уже есть тред на эту тему )
