### ISSUE TITLE
Не устанавливается через composer на php 7.3

### ISSUE THREAD

**Issue by abik50000** [amocrm/amocrm-api-php#324]
Выводит ошибку:

Installation failed, reverting ./composer.json to its original content.
[ErrorException]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by eugene-borovov** [comment]
Обновите composer и попробуйте снова.
`composer self-update`

Если это не сработает, то переустановите composer. Судя по данным из интернета, это не проблема composer.

**Comment by abik50000** [comment]
[InvalidArgumentException]
Command "self-update" is not defined.

Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

**Comment by eugene-borovov** [comment]
Ой-вей! Ставьте композер [заново](https://getcomposer.org/doc/00-intro.md).

```bash
$ composer -V
Composer version 2.0.14 2021-05-21 17:03:37
```

**Comment by abik50000** [comment]
**composer require amocrm/amocrm-api-library**

Using version ^0.5.2 for amocrm/amocrm-api-library
./composer.json has been updated
Running composer update amocrm/amocrm-api-library
Loading composer repositories with package information
Updating dependencies
**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Root composer.json requires doctrine/dbal 2.6.*, found doctrine/dbal[v2.6.0, v2.6.1, v2.6.2, v2.6.3] but the package is fixed to 2.13.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Installation failed, reverting ./composer.json and ./composer.lock to their original content.**

**Comment by eugene-borovov** [comment]
У amocrm нет зависимости от `doctrine/dbal`

Решите проблему:

> Problem 1
> - Root composer.json requires doctrine/dbal 2.6.*, found doctrine/dbal[v2.6.0, v2.6.1, v2.6.2, v2.6.3] but the package is fixed to 2.13.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

У вас расхождение в версиях `doctrine/dbal` записанные в `composer.json` и `composer.lock`.

**Comment by abik50000** [comment]
Все заработало!
