### ISSUE TITLE
Валидация полей в API и на фронте

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#327]
Столкнулись с тем, что валидация полей сущностей различается в апи и фронте. Что заметили:
https://github.com/amocrm/amocrm-api-php/issues/85
https://github.com/amocrm/amocrm-api-php/issues/224

Обе проблемы известны уже достаточно давно и очень сильно наболели. К сожалению, движений по ним нет, понимаем вашим большим загрузом (но надеюсь, скоро удастся поправить). А сейчас из-за этого вместо обновления сделки

```
$lead = $apiCleint->leads()->getOne(0000);
//Какие-то манипуляции
$apiClient->leads()->updateOne($lead);
```

Приходится городить вот такую кашу, что убивает напрочь ООП подход

```
$brokenLead = $apiCleint->leads()->getOne(0000);
$lead = (new LeadModel())->setLeadId($brokenLead->getId());
//Какие-то манипуляции
$apiClient->leads()->updateOne($lead);
```

Можете на данный момент сориентировать по актуальным правилам валидизации для каждого типа полей (не считая озвученных в иссюдах) по апи и на фронте - ибо полагаю что не два поля могут иметь разную валидацию.

**Comment by bessudnov** [comment]
На самом деле очень надеюсь, что обе проблемы возьмем в работу в июне
Это, по сути, 2 задачи:
1) Валидация длины значений привести к общему виду с фронтом (тут будет в API расширение до значений фронта)
2) Научиться через API получать отформатированные даты, а не только timestamp и поддержать это изменение в библиотеке

Сейчас есть ограничения у следующих типов полей:
1) Юр. лицо - у строковых и числовых свойств длина не более 2000 символов
2) Адрес и смарт-адресс - 2000 символов
3) Текст - 256 символов
4) Текстовая область - 26000

Данный issue закрываю, так как есть 2 предыдущих и в рамках них и будут вести работы
