### ISSUE TITLE
Можно ли фильтровать по metadata в ChatsMetadata

### ISSUE THREAD

**Issue by quiet2** [amocrm/amocrm-api-php#328]
Требуется переименовывать unsorted сделки при ее создании (после первого сообщения в чат)
После отправки сообщения я у себя знаю sender.id (в BaseUnsortedModel он же metadata.to) и из ответа msgid, но при дампе всех unsorted я вижу там только metadata.origin.chat_id (BaseUnsortedModel)
Было бы хорошо отфильтровать по metadata, но в UnsortedFilter таких методов нет
Тогда можно ли по msgid узнать chat_id?

Можно сделать тупой перебор всех unsorted и поиск нужного metadata.to (но если сделок будет много, процесс будет тяжелым)

Сейчас выбираю так
`
$unsortedsService = $ApiClient->unsorted();
$f = new \AmoCRM\Filters\UnsortedFilter;
$f->setCategory(\AmoCRM\Models\Unsorted\BaseUnsortedModel::CATEGORY_CODE_CHATS);
$unsorted = $unsortedsService->get($f);
`

**Comment by bessudnov** [comment]
В данный момент такой возможности в API и в библиотеке нет
