### ISSUE TITLE
Обновление контактов по api v4 - ошибки 4xx

### ISSUE THREAD

**Issue by GrandWebmaster** [amocrm/amocrm-api-php#329]
Добрый день!
При выполнении запроса на обновление данных контактов через api v4 выдает 405 ошибку
Запрос вида:
api/v4/contacts/38781399
`[
  {
    "id": 38781399,
    "first_name": "Иван",
    "last_name": "Васильевич",
    "name": "Иван Васильевич",
    "updated_at": 1622036808,
    "custom_fields_values": [
      {
        "field_code": "PHONE",
        "values": [
          {
            "value": "+7 (910) 000-00-00",
            "enum_code": "WORK"
          }
        ]
      },
      {
        "field_code": "EMAIL",
        "values": [
          {
            "value": "test@test.ru",
            "enum_code": "WORK"
          }
        ]
      }
    ],
    "request_id": "0"
  }
]`
1) Если у custom_fields_values указать field_id вместо  field_code, то ругается на него. Хотя в примере в документации приводится field_id
https://www.amocrm.ru/developers/content/crm_platform/contacts-api#contacts-edit
2) Если в url запроса убрать идентификатор - 38781399, оставив api/v4/contacts , полагая, что переменной id в массиве достаточно, то на практике идет добавление нового контакта с этими данными

Я сравниваю свой массив с тем, что в примере, но не могу найти причин почему отправляемый мною запрос отдает 405. Надеюсь вы внесете ясность по 1 и 2 пункту, а также укажите, где я допускаю ошибку.

**Comment by bessudnov** [comment]
405 http код - method not allowed
Можете предоставить код, который делает запрос с ошибкой?

**Comment by GrandWebmaster** [comment]
Код могу предоставить, он не данной библиотеки. Но поддержка из амо остылает сюда за технич. вопросами. 
Если вкратце, то обращаюсь по curl к методу: *домен_в_амо*/api/v4/contacts/38781399 (контакт с таким id есть в crm)
Передаю post параметры, что указал выше. На выходе получаю 405. При этом я акцентирую внимание, что с field_id версия v4 не хочет работать, также было с сущностью Счета/Покупки - тоже требует field_code. Но тут и с  field_code не хочет отрабатывать запрос.

**Comment by MaximBobylev** [comment]
@GrandWebmaster добрый день! Если вы редактируете существующий контакт, необходимо использовать метод PATCH

Если вы уже используете метод PATCH, но всё равно получаете ошибку 405, приведите, пожалуйста, фрагмент кода, который отправляет запрос.
