### ISSUE TITLE
Bad Request (400) код 244 при совершении POST запроса на "/api/v4/leads"

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#33]
Начиная с 22.06.2020, при попытке добавить сделку получаю в качестве ответа ошибку Bad Request (400) с кодом 244. При работе с другими методами API или совершении GET запроса на "/api/v4/leads" проблем не наблюдается
```
'last_response' => '{"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Код ошибки 244. В случае повторного возникновения ошибки, обращайтесь в нашу техническую поддержку - support@amocrm.ru"}',
'last_response_code' => 400,
'last_request_id' => '8522c111dfbcacb99b9a2bc22ee07820'
```

**Comment by bessudnov** [comment]
Похоже, что вы делаете запрос из под пользователя, у которого нет прав на добавление сделок

**Comment by dura4kov** [comment]
Подумал, что проблема действительно в правах пользователей, но, как оказалось, запросы делались из-под администратора. Возможно, этот как-то связано с  тем, что аккаунт бесплатный? Правда, тестовый период закончился только сегодня, а проблеме с добавлением сделок уже 4ый день идет.

**Comment by bessudnov** [comment]
Может быть связано с 1) права ограничены 2) подписка закончилась

по вопросам именно API лучше обращаться в техническую поддержку через чат в аккаунте

**Comment by dura4kov** [comment]
благодарю
