### ISSUE TITLE
Все поля кроме id возвращаются как null

### ISSUE THREAD

**Issue by zerosones-dynamics** [amocrm/amocrm-api-php#330]
Приветствую! Подскажите пожалуйста. Почему при вызове метода `get` c аргументом `with`, поля контактов, все кроме `id` возвращаются как `null`.

        /* ... */

        $filter = new LeadsFilter;

        /* ... */

        foreach ($users as $user) {
            $filter->setQuery($user->hashed_id);

            try {
                $leads = $amoCRMApiClient->leads()->get($filter, [LeadModel::CONTACTS]);

                if ($leads->count() > 0) {
                    foreach ($leads->all() as $lead) {
                        $contacts = $lead->getContacts();

                        var_dump($contacts);
                    }
                }
            } catch (AmoCRMApiException $e) {

            }
        }

AmoCRM\Collections\ContactsCollection {#1307 ▼
    #data: array:1 [▼
        0 => AmoCRM\Models\ContactModel {#1311 ▼
            #id: 46394883
            #name: null
            #firstName: null
            #lastName: null
            #responsibleUserId: null
            #groupId: null
            #createdBy: null
            #updatedBy: null
            #createdAt: null
            #updatedAt: null
            #closestTaskAt: null
            #accountId: null
            #tags: null
            #customFieldsValues: null
            #isMain: true
            #company: null
            #leads: null
            #customers: null
            #catalogElementsLinks: null
            #socialProfiles: null
            #requestId: null
        }
  ]
  -nextPageLink: null
  -prevPageLink: null
}

**Comment by eugene-borovov** [comment]
Тоже задавался этим вопросом. Похоже API возвращает список идентификаторов. Возвращается коллекция моделей с заполненным ID, чтобы потом можно было сделать `syncOne`. Даже в примерах есть [рецепт](https://github.com/amocrm/amocrm-api-php/blob/ee41bc71fe3c6b322b5e01932efeb4674849203b/examples/leads_actions.php#L203).

**Comment by bessudnov** [comment]
Сейчас апи возвращает только ID связанных сущностей
Как отметил Евгений, есть метод syncOne, как раз для подобных случаев
Либо можно с помощью $ids = $collection->pluck('id'); получить все ID и дальше уже по ID сходить за коллекцией сущностей
