### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by koreginn** [amocrm/amocrm-api-php#331]
Problem 1
    - Root composer.json requires amocrm/amocrm-api-library ^0.5.2 -> satisfiable by amocrm/amocrm-api-library[0.5.2].
    - amocrm/amocrm-api-library 0.5.2 requires lcobucci/jwt ^3.4 || 4.* -> found lcobucci/jwt[3.4.0, ..., 3.4.x-dev, 4.0.0-alpha1, ..., 4.2.x-dev] but the package is fixed to 3.2.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by eugene-borovov** [comment]
Вы используете `lcobucci/jwt` напрямую с ограничением `^3.2.5` или аналогичным?

**Comment by bessudnov** [comment]
Нет ответа более месяца. Тикет закрывается. Откройте повторно, при необходимости.
