### ISSUE TITLE
Ограничение поля бюджет

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#332]
Насколько я помню, раньше такой проблемы не было, но сейчас появилась.
Поле бюджет перестало поддерживать дробные значения. Есть в сегменте РФ, копейки не сильно влияют на аналитику, но в сегменте белоруси это прямо проблема, так как белорусский рубль составляет почти 29 российских рублей, в случае округления аналитика очень сильно едет и мы потеряли уже второго потенциального клиента на амо из Беларуси.

Вопрос не по библиотеке, но как я понимаю, вы можете помочь, @bessudnov.
Поддержка разводит руками и говорит "такова логика работа". Но в данном случае она ломает интересы некоторых пользователей. С этим можно что-то сделать?

**Comment by bessudnov** [comment]
В данный момент поле бюджет не поддерживает дробные значения, как и не поддерживало ранее.
В вишлисте это пожелание уже есть.

Как вариант, можно создать доп поле, но тогда не будут корректно работать некоторые отчеты, потому что они считаются как раз по бюджету
