### ISSUE TITLE
Получить не все сделки а только их количество. Где метод count ?

### ISSUE THREAD

**Issue by falur** [amocrm/amocrm-api-php#335]
Как получить количество сделок по фильтру например. В апи и близко нет метода count бегать по пагинации и считать страницы такое себе занятие.

**Comment by bessudnov** [comment]
Да, проблема в технической реализации. Большой объем данных зачастую не дает возможность сделать быстрые подсчеты, поэтому в API такой возможности сейчас нет

**Comment by falur** [comment]
В любой БД, есть возможность выполнить запрос COUNT почему это сложно? Запросы эти отрабатывают быстро

**Comment by bessudnov** [comment]
> Запросы эти отрабатывают быстро

Не все, не всегда и не во всех бд
В том же мускуле count на таблицу, например 100 миллионов записей, работает больше 10 секунд в подавляющем большинстве случаев, не говоря уже о других решениях, где в сложных кейсах подсчет может исчисляться минутами, а то и десятками минут

Если аналитические базы, где подсчеты быстрые и на больших объемах, но с ними есть другие нюансы

**Comment by eugene-borovov** [comment]
@bessudnov 
Возможно ли использовать в этой библиотеке те же механизмы для подсчёта количества элементов коллекций, что и в интерфейсе AmoCRM? Насколько можно наблюдать фильтруются такие же объекты и выводятся количества результатов довольно быстро.

**Comment by falur** [comment]
> > Запросы эти отрабатывают быстро
> 
> Не все, не всегда и не во всех бд
> В том же мускуле count на таблицу, например 100 миллионов записей, работает больше 10 секунд в подавляющем большинстве случаев, не говоря уже о других решениях, где в сложных кейсах подсчет может исчисляться минутами, а то и десятками минут
> 
> Если аналитические базы, где подсчеты быстрые и на больших объемах, но с ними есть другие нюансы

Я так понимаю глобальная проблема в том что БД по факту одна поэтому работа идёт с большим количеством данных?

**Comment by bessudnov** [comment]
Если бы была одна БД, уже давно бы не работала система)

Больше подробностей рассказать не могу, к вашему сожалению
