### ISSUE TITLE
Дайте доступ по api к разделу аналитки

### ISSUE THREAD

**Issue by falur** [amocrm/amocrm-api-php#336]

**Comment by bessudnov** [comment]
Чтобы внесли в wish list нужно писать в поддержку через аккаунт и с большими подробностями.

**Comment by falur** [comment]
Речь шла о технической возможности. Что в CRM есть раздел аналитика, почему нет методов для работы с ней. Вед наверняка это где-то лежит в таблицах.

**Comment by bessudnov** [comment]
Публичных методов сейчас нет и в обозримом будущем не планируется, но вы можете написать в поддержку, они внесут в wish list, может быть планы изменятся.

Но вообще есть API списка событий, который позволяет достаточно большую часть данных получать и по ним строить отчеты
