### ISSUE TITLE
Хуки в формате v4

### ISSUE THREAD

**Issue by viacheslav594** [amocrm/amocrm-api-php#338]
Пробовал разбирать хуки и заметил что отличается их формат от ответов апи в4. Подскажите по поводу того, когда хуки начнут приходить в формате в4, а не таком какой сейчас?

Насколько я помню, тут говорили про то, что бы научить библиотеку разбирать хуки формата в2. Это есть в планах?

Так же уточните, планируется ли дальнейшая поддержка апи в2? То есть нет ограничений по поддержке или планируется отключение него?

**Comment by bessudnov** [comment]
https://github.com/amocrm/amocrm-api-php/issues/195

Этот Issue закрываю, так как дубль

Пока задача на хуки v4 в бэклоге

По поводу api/v2 - ограниченная поддержка осуществляется, так как у небольшой части методов общее ядро с api/v4, но развитие api/v2 точно не будет
Отключать пока не планируем, но баги по api/v2, если аналогичный метод api/v4 работает корректно, не планируем рассматривать
