### ISSUE TITLE
Данные для полей "Статистика"

### ISSUE THREAD

**Issue by borzakap** [amocrm/amocrm-api-php#342]
Я видел, что появились новые поля "Статистика", куда можно записывать различные utm-метки. Есть ли возможность через API вносить туда данные?

**Comment by mihalbl400** [comment]
Я не могу понять как получить все доступные поля для сделки, по этому id смотрел через html код страницы.
В целом у лида:
`->setCustomFieldsValues(
                (new CustomFieldsValuesCollection())
                    ->add(
                        (new \AmoCRM\Models\CustomFieldsValues\TrackingDataCustomFieldValuesModel())
                            ->setFieldCode('361543')
                            ->setValues(
                                (new \AmoCRM\Models\CustomFieldsValues\ValueCollections\TrackingDataCustomFieldValueCollection())
                                    ->add((new \AmoCRM\Models\CustomFieldsValues\ValueModels\TrackingDataCustomFieldValueModel())->setValue('test'))
                            )
                    )
            )`

**Comment by borzakap** [comment]
Вроди разобрался - добавляется поидее как обычное текстовое поле, только через свою модель.
остается только один вопрос, нужно указывать id поля (проверил, в разных аккаунтах они разные).
или можно все таки через setFieldCode - но опять, нигде не нашел какие там должны быть кода.... и есть ли вообще было бы классно все-таки через код

**Comment by viacheslav594** [comment]
> Я не могу понять как получить все доступные поля для сделки, по этому id смотрел через html код страницы.
> В целом у лида:
> `->setCustomFieldsValues( (new CustomFieldsValuesCollection()) ->add( (new \AmoCRM\Models\CustomFieldsValues\TrackingDataCustomFieldValuesModel()) ->setFieldCode('361543') ->setValues( (new \AmoCRM\Models\CustomFieldsValues\ValueCollections\TrackingDataCustomFieldValueCollection()) ->add((new \AmoCRM\Models\CustomFieldsValues\ValueModels\TrackingDataCustomFieldValueModel())->setValue('test')) ) ) )`

Вот метод апи
https://domain.amocrm.ru/api/v4/leads/custom_fields 

Так же есть в библиотеке функционал. Эти поля имеют уникальные айди, что позволяет писать в них как в обычные custom fields, так и code - сквозную кодировку, применимую ко всем аккаунтам.



> Вроди разобрался - добавляется поидее как обычное текстовое поле, только через свою модель.
> остается только один вопрос, нужно указывать id поля (проверил, в разных аккаунтах они разные).
> или можно все таки через setFieldCode - но опять, нигде не нашел какие там должны быть кода.... и есть ли вообще, было бы классно все-таки через код

Получи список кодов через метод выше (из браузера) или с помощью библиотеки.

**Comment by borzakap** [comment]
большое спасибо !!! :-)
