### ISSUE TITLE
Ошибка при вызове $usersService->get();

### ISSUE THREAD

**Issue by xlingvox** [amocrm/amocrm-api-php#343]
Делаю запрос через `$usersService->get();`, но он приводит к ошибке 
```
TypeError
Argument 1 passed to AmoCRM\Models\Rights\RightModel::completeRightsDependencies() must be of the type array, string given, called in \vendor\amocrm\amocrm-api-library\src\AmoCRM\Models\Rights\RightModel.php on line 358
```
Проверил, в \vendor\amocrm\amocrm-api-library\src\AmoCRM\Models\Rights\RightModel.php:358 передает не массив, а строковое значение (в данной ситуации "А" и все)

**Comment by tartakxg** [comment]
Та же проблема на одном из аккаунтов

**Comment by tartakxg** [comment]
Workaround
`$apiClient->getRequest()->get('/api/v4/users')`

**Comment by dura4kov** [comment]
Подобную проблему словил пару раз в случае добавления нового пользователя и последующей выдачи ему роли администратора. Для такого пользователя, похоже, устанавливаются catalog_rights, которые прилетают от апи в виде 

`
{
   "catalog_rights":[
      {
         "catalog_id":"add",
         "rights":"A"
      },
      {
         "catalog_id":"edit",
         "rights":"A"
      },
      {
         "catalog_id":"view",
         "rights":"A"
      },
      {
         "catalog_id":"delete",
         "rights":"A"
      },
      {
         "catalog_id":"export",
         "rights":"A"
      }
   ]
}
`
Соответственно в completeRightsDependencies передается строка, а не массив

**Comment by bessudnov** [comment]
Поставил тикет на разбор проблемы

**Comment by bessudnov** [comment]
Исправление отгружено на продакшен на прошлой неделе
Issue закрываю
