### ISSUE TITLE
Ошибки в документации

### ISSUE THREAD

**Issue by makeroi** [amocrm/amocrm-api-php#345]
Добрый день!
Подскажите, на сайте очень много сильно (и очень сильно) устаревшей документации.
Например, тут https://www.amocrm.ru/developers/content/digital_pipeline/integrations малая часть от возможных значений type и type_code.

А тут https://www.amocrm.ru/developers/content/integrations/structure указана структура виджета, от которой отказались год назад - с айди интеграции в манифесте.

Это очень сильно мешает процессу коммерческой разработки. Возможно ли что-то сделать с обновлением документации? Я, конечно мало представляю, как, но я готов оказать какую то помощь в этом, потому что это очень большая боль для разработчиков, когда, например мы воспроизводим все вебхуки для получения возможного списка события. Есть страницы с описанием старых методов, v2, без понимания, перенесены ли эти методы в v4.

Я видел в документации в качестве примеров приводятся интеграция "Простор СМС от компании Axelerator", я так же являюсь представителем интегратора, может быть как-то смогу помочь. Если есть какие-то варианты, напишите на почту v.rodionov@makeroi.ru.

**Comment by bessudnov** [comment]
Здравствуйте, насколько вижу, с вами уже связывались.
Также вижу ваши предложения по документации. Планируем в конце августа-начале сентября пройтись по ним и по всем пунктам дать ответ.
