### ISSUE TITLE
Получает лиды без контактов, хотя контакты есть. 

### ISSUE THREAD

**Issue by CiFrameVladislavB** [amocrm/amocrm-api-php#347]
Попробовал по примеру в файле leads_actions.php получить лиды вместе с контактами. Лиды получаю по фильтру.
```
$filter = new LeadsFilter();
$filter->setIds($lead_id);
 try {
        $leads = $apiClient->leads()->get($filter);
        foreach ($leads as $lead)
        {
            var_dump($lead);
           $leadContacts = $lead->getContacts();
            var_dump($leadContacts);
        }
    }
```
Дамп $lead показывает, что у лида поле contacts равно NULL, и $lead->getContacts() соответственно возвращает NULL, хотя в интерфейсе контакт показывает, я даже добавил ещё один, но не помогло. В чём может быть проблема?

**Comment by eugene-borovov** [comment]
Нужно указать тип связи, которую надо выбрать (см. [пример](https://github.com/amocrm/amocrm-api-php/blob/ee41bc71fe3c6b322b5e01932efeb4674849203b/examples/leads_actions.php#L124) ). В выборке будет связная сущность с заполненным полем ID. Для получения остальных полей вызывается `syncOne` (см. [пример](https://github.com/amocrm/amocrm-api-php/blob/ee41bc71fe3c6b322b5e01932efeb4674849203b/examples/leads_actions.php#L203) )

**Comment by CiFrameVladislavB** [comment]
Спасибо.
