### ISSUE TITLE
нужна помощь для настройки с Oauth2

### ISSUE THREAD

**Issue by Yusufjon** [amocrm/amocrm-api-php#350]
Я впервые подключаюсь к amocrm с помощью ouath2 и отправляю лиды. Я выполнил инструкции, но не смог найти, что такое $ apiClientFactory = new \ AmoCRM \ Client \ AmoCRMApiClientFactory ($ oAuthConfig, $ oAuthService);
$ apiClient = $ apiClientFactory-> make ();

Где мне его использовать? Когда я копирую и вставляю, параметры функции подчеркиваются красным цветом.

**Comment by crush-debug** [comment]
Как получить клиент, для формирования запросов к апи, ответил в другом запросе https://github.com/amocrm/amocrm-api-php/issues/351
Создание лида по апи, есть в [примерах](https://github.com/amocrm/amocrm-api-php/blob/ee41bc71fe3c6b322b5e01932efeb4674849203b/examples/leads_actions.php#L39)
Вообще в примерах есть достаточно много примеров использования данного api-клиента.
