### ISSUE TITLE
Значение поля не удаляеться через API

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#352]
У лида есть поле которое заполняется только через API (ссылка на заказ в МойСклад).
Вот код, который устанавливает значение:
```
(new TextCustomFieldValuesModel())
           ->setFieldId($field_id)
           ->setValues(
               (new TextCustomFieldValueCollection())
                   ->add(
                       (new TextCustomFieldValueModel())->setValue($value ? strval($value) : null)
                   )
           );
```

если значение есть в `$value`, то все ок, но если значение отсутствует, то в amoCRM ничего не меняется
даже если передать `''` то поведение такое-же (т.е. проблема не в `null`)

**Comment by makeroi** [comment]
Это нормальная механика. Обновляются только переданные значения. Для того, что бы очистить поле нужно передать null в него.

```
$lead; //Ваш исходный лид
$fieldIdToTruncate = 111;
        $leadToUpd = (new LeadModel)->setId($lead->getId())->setCustomFieldsValues(
            (new CustomFieldsValuesCollection())->add((new TextCustomFieldValuesModel())->setFieldId($fieldIdToTruncate)->setValues(
                    (new TextCustomFieldValueCollection())
                        ->add((new TextCustomFieldValueModel())
                            ->setValue(null)
                        )
                )));
        $apiClient->leads()->updateOne($leadToUpd);
```

**Comment by vodnicearv** [comment]
@makeroi не вижу ни какой разницы между моим кодом и вашим
`null` передаю конечно, но поле не очищается

кстати поле имеет отметку, что данные может получить только из API, может с этим связано

**Comment by makeroi** [comment]
А вы создаете новую модель для обновления или обновляете текущую? - по вашему коду это не видно
Возможно, если текущую, у вас в коллекции кстом филдс две сущности поля - одно заполненное, второе с нуллом

**Comment by vodnicearv** [comment]
Обновляю текущую, в коллекции есть только одно заполненное поле (дубликата
нет)
În mie., 28 iul. 2021 la 14:07 Rodionov Viacheslav ***@***.***>
a scris:

**Comment by makeroi** [comment]
Я имею в виду что в коллекции уже есть заполнное поле, а вы кладете туда поле с нуллом (в коде, который указан у вас сверху). (и получается в коллекции два поля с одинаковым айди. Можете попробовать обновлять пустую модель, как у меня?

Никак не могу воспроизвести вашу ситуацию

**Comment by vodnicearv** [comment]
@makeroi спасибо!
Действительно не передавалось значение `null` поэтому поле не очищалось.

был такой код:
```
$customFieldsValuesCollection = new CustomFieldsValuesCollection();
foreach (config('services.amocrm.fields.orders') AS $field => $field_id) {
    if (intval($field_id) AND isset($order->{$field})) {
        try {
            $customFieldsValuesCollection->add($this->addField(intval($field_id), $field, $order->{$field}));
        } catch (TypeError $typeError) {
            dd($typeError, $field_id, $field, $order->{$field});
        }
    }
}
$lead->setCustomFieldsValues($customFieldsValuesCollection);
```
и проблема была в том что если поле имеет `null` то `isset` возвращает `false`
