### ISSUE TITLE
При редактирование тегов у лида удаляются значения в чек-боксах

### ISSUE THREAD

**Issue by vodnicearv** [amocrm/amocrm-api-php#355]
При обычном редактирование и сохранение лида, все нормально.
Но при редактирование тегов, срабатывает автоматическое сохранение, и вот после автоматического сохранения веб-хук удаляет значения из полей типа чек-бокс.
 
То есть, например, в лиде есть 2 включеных чек-бокса _Детали_ и _Пришла оплата_, если мы добавим или удалим какой-то тег, то чек-боксы перейдут в состояние выключен, и эти-же данные отправляются в webhook.

Может кто-то еще тестировать в своих аккаунтах это поведение?

**Comment by bessudnov** [comment]
Можете добавить пример кода, который используете для работы с API, чтобы детальней могли разобрать и воспроизвести ситуацию?

**Comment by bessudnov** [comment]
Вопрос закрываю, так как нет ответа, если нужно будет - Issue можно открыть повторно

**Comment by vodnicearv** [comment]
ok, пока не успел заняться вопросом тестирования
но галочки еще слетают)

как проверю и найду причину - напишу тут

În lun., 6 sept. 2021 la 01:44, Nikita ***@***.***> a scris:
