### ISSUE TITLE
Выборка данных и баг с дублями сделок

### ISSUE THREAD

**Issue by webds** [amocrm/amocrm-api-php#357]
Не совсем касается прям API но вдруг кто знает как решить или дату когда будет решение.  
При определенном фильтре в  поиске, получаем сделки, при экспорте их в файл, видимо дубли сделок. К примеру она и та же сделка может быть по два три раза.  Интересно этот баг у  все или только у нашего  клиента.

**Comment by bessudnov** [comment]
Здравствуйте, с подобной проблемой нужно обращаться в техническую поддержку из аккаунта.

Issue закрываю, так как не связан с библиотекой.
