### ISSUE TITLE
Argument 1 passed to AmoCRM\Models\Rights\RightModel::completeRightsDependencies() must be of the type array, string given, called in /var/www/app/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/Rights/RightModel.php on line 357

### ISSUE THREAD

**Issue by tofers** [amocrm/amocrm-api-php#364]
Вызываю метод $apiClient->users()->get();

В итоге падает с ошибкой

foreach ($catalogRights as $catalogRight) {
            $result[] = [
                'catalog_id' => $catalogRight['catalog_id'] ?? null,
                'rights'     => $this->completeRightsDependencies(
                    $catalogRight['rights'],
                    EntityTypesInterface::CATALOG_RIGHTS       -------- в этой строке
                ),
            ];
        }
 
        $this->catalogRights = $result

**Comment by tofers** [comment]
"catalog_rights": [
                        {
                            "catalog_id": "add",
                            "rights": "A"
                        },
                        {
                            "catalog_id": "edit",
                            "rights": "A"
                        },
                        {
                            "catalog_id": "view",
                            "rights": "A"
                        },
                        {
                            "catalog_id": "delete",
                            "rights": "A"
                        },
                        {
                            "catalog_id": "export",
                            "rights": "A"
                        }
                    ],


Причина то что апи отдают вот такой массив

**Comment by bessudnov** [comment]
Дубль https://github.com/amocrm/amocrm-api-php/issues/343
Работы по исправлению будут вестись там, этот issue закрываю
