### ISSUE TITLE
Получение данных по гет параметру (Вопрос по авторизации)

### ISSUE THREAD

**Issue by MayFreym** [amocrm/amocrm-api-php#372]
Добрый день!

Задача следующая, сделать лендинг\КП данные для которого будут браться из специальных полей в сделке, клиенту будет отправлять ссылку с GET-параметром(например, site.com/?id=111)  где параметр это id сделки. 
Вопрос такой, есть ли какой то другой способ авторизации, потому что тот который в примере не подходит, т.к подразумевает авторизацию через кнопку или попап. 
Заранее спасибо!

**Comment by bessudnov** [comment]
Вопрос не очень про библиотеку. С таким скорее в Тех Поддержку.

Вообще авторизация через кнопку или попап нужна только для получения токена. Конечному пользователю не нужно производить никаких авторизаций в amoCRM, токен должен хранить ваш бек/база_данных и тд, а дальше в коде делать запрос с токеном в API
