### ISSUE TITLE
add для AttachmentNote

### ISSUE THREAD

**Issue by makeroi** [amocrm/amocrm-api-php#373]
При попытке добавить к сделке AttachmentNote получаю ошибку NotAvailableForActionException. Уточните, это нормальная механика?

**Comment by bessudnov** [comment]
Да, в данный момент нет возможность через API добавлять файлы с загруженными файлами

**Comment by makeroi** [comment]
А где можно изучить доступные методы для наследников Note? Потому что заметил проблему еще с наследниками NoParamNote?
