### ISSUE TITLE
Добавление нескольких Note к одной сделке с помощью add()

### ISSUE THREAD

**Issue by makeroi** [amocrm/amocrm-api-php#379]
Пробовал добавить несколько примечаний к одной сделке за раз, но потерпел поражение. Добавляется только одно.
Это нормальная механика? Иногда, когда интеграция сделала несколько действий хочется добавить несколько примечаний, но приходится использовать отдельные запросы.
```
$notes = (new NotesCollection())
            ->add((new CommonNote())
                ->setEntityId($lead->getId())
                ->setText("Создана копия сделки. Новая сделка {$this->getLeadLink($newLead)}"))
            ->add((new CommonNote())
                ->setEntityId($newLead->getId())
                ->setText($textToNewLead))
            ->add((new CommonNote())
                ->setEntityId($newLead->getId())
                ->setText($textToNewLead))
            ->add((new CommonNote())
                ->setEntityId($newLead->getId())
                ->setText($textToNewLead))
            ->add((new CommonNote())
                ->setEntityId($newLead->getId())
                ->setText($textToNewLead));
        $this->apiClient->notes('leads')->add($notes);
```

**Comment by makeroi** [comment]
UPD: Обнаружил проблему, она оказалась глубже - по факту примечания добавляются, но отображается только одно, если у примечаний дата создания совпадает

**Comment by bessudnov** [comment]
По проблеме, что не отображаются события с одной датой, правки сейчас в работе, думаю в ближайшее время будут отгружены.

Issue закрываю, так как не относится к библиотеке
