### ISSUE TITLE
Как найти сделку по статусу и воронке? api

### ISSUE THREAD

**Issue by IgorPlaysYT** [amocrm/amocrm-api-php#384]
? Я хочу взять сделки с определённой воронки и статуса пишу> example.amocrm.ru/api/v4/leads/filter[pipeline_id]=4643281?filter[status_id]=142 Выдаёт ошибку, что делать? {"title":"Not Found","type":"https://httpstatus.es/404","status":404,"detail":"Cannot GET

**Comment by makeroi** [comment]
Простите, откуда такой линк?
фильтры являются Get-параметрами, а у вас один вообще часть пути, а второй параметр

`https://example.amocrm.ru/api/v4/leads?filter[pipeline_id]=4643281&filter[status_id]=142`
