### ISSUE TITLE
Телефон пользователя амо?

### ISSUE THREAD

**Issue by max-kut** [amocrm/amocrm-api-php#39]
Ребята, куда дели телефон пользваотеля амо в api v4?

**Comment by bessudnov** [comment]
В данной версии API недоступен телефон пользователя из-за безопасности данных пользователя.

**Comment by max-kut** [comment]
В случае задачи отправки пользователю смс по каким-либо событиям внешней системы решение убрать поле из API на мой взгляд непродуманное.
Вопрос не возник бы, если бы старую документацию не убирали из паблика (за это отдельный минус в карму). Поддержка решений, написанных достаточно давно, является процессом, сопровождаемым обильным количеством матерной лексики

**Comment by bessudnov** [comment]
Документация к api/v2 будет скрыта позднее

Запишем в бэклог, чтобы апи возвращало телефон текущего юзера
