### ISSUE TITLE
При добавлении id, custom поля не создаются

### ISSUE THREAD

**Issue by Alex18595** [amocrm/amocrm-api-php#392]
При добавлении custom полей если не указывать id то все хорошо, но как только указываем id через ->setId то ошибок нет, но поле не создается

	use AmoCRM\Helpers\EntityTypesInterface;
	use AmoCRM\Collections\CustomFieldGroupsCollection;
	use AmoCRM\Exceptions\AmoCRMApiException;
	use AmoCRM\Models\CustomFieldGroupModel;
	use League\OAuth2\Client\Token\AccessTokenInterface;

	use AmoCRM\Collections\CustomFields\CustomFieldEnumsCollection;
	use AmoCRM\Collections\CustomFields\CustomFieldsCollection;
	use AmoCRM\Models\CustomFields\CustomFieldModel;
	use AmoCRM\Models\CustomFields\EnumModel;
	use AmoCRM\Models\CustomFields\SelectCustomFieldModel;
	use AmoCRM\Models\CustomFields\TextCustomFieldModel;
	use AmoCRM\Models\CustomFields\NumericCustomFieldModel;
	use AmoCRM\Models\CustomFields\DateCustomFieldModel;

	include_once __DIR__ . '/bootstrap.php';

	$accessToken = getToken();

	$apiClient->setAccessToken($accessToken)
		->setAccountBaseDomain($accessToken->getValues()['baseDomain'])
		->onAccessTokenRefresh(
			function (AccessTokenInterface $accessToken, string $baseDomain) {
				saveToken(
					[
						'accessToken' => $accessToken->getToken(),
						'refreshToken' => $accessToken->getRefreshToken(),
						'expires' => $accessToken->getExpires(),
						'baseDomain' => $baseDomain,
					]
				);
			}
		);

		//Сервис кастом полей для сделок

	$customFieldsService = $apiClient->customFields(EntityTypesInterface::LEADS);

	try {
		$result = $customFieldsService->get();
	} catch (AmoCRMApiException $e) {
		printError($e);
		die;
	}

	$customFieldsCollection = new CustomFieldsCollection();
		$cf = new NumericCustomFieldModel();
			$cf
				->setName('Сумма3')
				->setSort(2050)
				->setId(333);
			$customFieldsCollection->add($cf);	
		
		try {
			//Добавим поля в аккаунт
			$customFieldsCollection = $customFieldsService->add($customFieldsCollection);
		} catch (AmoCRMApiException $e) {
			printError($e);
			die;
		}

	die;

**Comment by eugene-borovov** [comment]
Так вы добавляете ТИПЫ кастомным полей в аккаунт, поэтому не удивительно, что CRM управляет назначением идентификаторов. Возможно вы хотели использовать кастомное поле, например, в сделке, тогда указание идентификатора поля является обязательным ([см. пример](https://github.com/amocrm/amocrm-api-php/blob/cc9a5f221929638979103420ab50f93a58a3627d/examples/leads_actions.php#L150))

**Comment by Alex18595** [comment]
А не подскажите, можно ли сделать чтобы нельзя было поменять воронку в зависимости от значения custom поля?

**Comment by Alex18595** [comment]
> Так вы добавляете ТИПЫ кастомным полей в аккаунт, поэтому не удивительно, что CRM управляет назначением идентификаторов. Возможно вы хотели использовать кастомное поле, например, в сделке, тогда указание идентификатора поля является обязательным ([см. пример](https://github.com/amocrm/amocrm-api-php/blob/cc9a5f221929638979103420ab50f93a58a3627d/examples/leads_actions.php#L150))
А не подскажите, можно ли сделать чтобы нельзя было поменять воронку в зависимости от значения custom поля?

**Comment by eugene-borovov** [comment]
Если имеется в виду интерфейс CRM, то я не знаю как сделать такое ограничение.
