### ISSUE TITLE
Как отслеживать событие изменения статуса сделки?

### ISSUE THREAD

**Issue by Alex18595** [amocrm/amocrm-api-php#396]
Если ли возможность отслеживать событие изменения статуса сделки? Или вообще запретить изменение статуса сделки? это делается с помощью  webhook?

**Comment by eugene-borovov** [comment]
да, это делается с помощью webhook.

**Comment by Alex18595** [comment]
А событие происходит получается уже после изменения статуса?

**Comment by Alex18595** [comment]
Т. е чтобы запретить изменения статуса мне надо откатить на предыдущий статус и как то удалить события изменения статуса в карточке сделки?

**Comment by eugene-borovov** [comment]
Видимо вы хотите триггеры на изменения воронки. Пример похожей задачи https://youtu.be/vnRJN_skhQY

**Comment by Alex18595** [comment]
В видео создается поле, и там можно выбрать чтоб оно было обязательным для несколько этапов. Получается в пробной версии такого функционала нет?

**Comment by Alex18595** [comment]
А можно при создании поля задать этот параметр: 

"required_statuses": [{
	"status_id": 41221,
	"pipeline_id": 3142
}],

И еще я вот получил список событий, можно ли удалить из него событие?
