### ISSUE TITLE
cURL error 28: Resolving timed out after 5513 milliseconds произошла такая ошибка, с чем может быть связано ?

### ISSUE THREAD

**Issue by SergeyKhlopov** [amocrm/amocrm-api-php#398]
Здравствуйте, подскажите пожалуйста.

Создаём сделку и контакт через API в CRM, но почему-то такая ошибка произошла при создании одного заказа:
`cURL error 28: Resolving timed out after 5513 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

```
AmoCRM\Exceptions\AmoCRMApiConnectExceptionException: cURL error 28: Resolving timed out after 5513 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /site/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php:169
Stack trace:
#0 /site/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(191): AmoCRM\Client\AmoCRMApiRequest->post('api/v4/leads', Array)
#1 /site/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(210): AmoCRM\EntitiesServices\BaseEntity->add(Object(AmoCRM\Collections\Leads\LeadsCollection))
#2 /site/app/Services/Crm/CrmLeadService.php(52): AmoCRM\EntitiesServices\BaseEntity->addOne(Object(AmoCRM\Models\LeadModel))
...
```

Сейчас заказы уже нормально создаются без ошибки, думаю может это на стороне amoCRM что-то не отвечало ?

Заранее благодарю за ответ.

**Comment by makeroi** [comment]
Сталкивался с таким. Тогда поддержка списала на техработы.

**Comment by SamoSargisyan** [comment]
связано с их апи:D в файле AmoCRMApiRequest на строке 34 указан таймаут 5 секунд, и используется дальше, например на 389 строке в этом же файле. Как увеличить таймаут - загадка

**Comment by SamoSargisyan** [comment]
да, слишком много телодвижений ради апдейта таймлимита)

**Comment by AvelPostol** [comment]
Проблема во внутренней архитектуре в БД amocrm, что нужно учитывать в построении запросов. Timeout не меняйте, получите косяк в отданных данных и гг. Особенно если данных много, не получаемых, а вообще(!). Короче, максимально используйте фильтры, по дате, order и т.д. если они есть и будет вам отдаваться за 2-3 секунды и рекурсивный вызов с того места, где timeout. НЕ ИСПОЛЬЗУЙТЕ ТУПО ПЕРЕБОР ПО PAGE
