### ISSUE TITLE
Ошибка при добавлении/обновлении значения доп. поля контакта типа Multitext

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#4]
## Current Behavior
Не удаётся добавить контакт с доп. полем типа multitex, не удается обновить значение доп. поля типа multitex (например, номер телефона контакта)

1. Если в MultitextCustomFieldValueModel указано значение поля enum, при вызове метода добавления\обновления контакта апи возвращает ошибку
`{"validation-errors":[{"request_id":"0","errors":[{"code":"FieldNotExpected","path":"custom_fields_values.0.values.0.enum","detail":"This field was not expected."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}`
2. Если у MultitextCustomFieldValueModel попытаться не выставлять/обнулить значение поля enum, во время вызова Contacts->add/Contacts->update при подготовке данных для отправки к API в результате MultitextCustomFieldValueModel->toArray возникает ошибка 
`TypeError: Return value of AmoCRM\Models\CustomFieldsValues\ValueModels\MultitextCustomFieldValueModel::getEnum() must be of the type string, null returned in /.../amocrm/amocrm-api-library/src/AmoCRM/Models/CustomFieldsValues/ValueModels/MultitextCustomFieldValueModel.php:22`
3. Если подправить тип поля enum со стринга на обнуляемый стринг, ошибки, описанной в пункте 2, удается избежать, однако в запросе на добавление/обновление контакта этот enum 
 все равно передается со значением null, что вновь приводит к ошибке из пункта 1
4. Если при сериализации убрать из запроса поле enum (оставить enum_id и value, как описано в документации в разделе "Редактирование контактов или компаний") - запрос выполняется без ошибки, только вот номер телефона не обновляется
5. Если при сериализации убрать из запроса поля enum и enum_id, оставив только value, запрос выполняется  без ошибок, телефон обновляется

## Environment
PHP 7.3
amoCRM API Client 0.1.1

**Comment by bessudnov** [comment]
Проверил, проблема в том, что API ждет свойство enum_code, а не enum.

В следующем релизе будет фикс. Ориентировочно сегодня-завтра.

**Comment by bessudnov** [comment]
Исправлено в релизе 0.2
