### ISSUE TITLE
Виджет телефонии

### ISSUE THREAD

**Issue by vitaliykyq** [amocrm/amocrm-api-php#418]
Здравствуйте. Нужна помощь в написании виджета телефонии для amoCRM (за оплату). Виджет максимально похожий на пример, но нужно написать отталкиваясь от обновлённой документации, после завершения, и внесения некоторых правок, можно занести его как официальный пример виджета для телефонии.

Почта: starandq.dev@gmail.com

**Comment by makeroi** [comment]
@vitaliykyq 
Написал на почту. Было бы удобно продолжить общение в телеграмм @led23
