### ISSUE TITLE
Требуется передать лида с сайта: к чему эти сложности?

### ISSUE THREAD

**Issue by DaemonHK** [amocrm/amocrm-api-php#426]
Стоит задача: при заполнении формы на сайте введенные данные необходимо отправить в AmoCRM. И тут начинается...

1. Создал интеграцию, получил clientId, secret, код авторизации, который протухает через 20 минут.
2. Читаем полдня документацию, в надежде получить ответы на вопрос как нам получить refresh_token, чтобы с помощью него получить access_token.
3. Понимаем, что судя по всему, упираемся в какие-то кнопки, где пользователь должен авторизоваться, но у нас же типа упрощенная схема, без всяких виджетов и прочего?
4. Лично я не понимаю, почему 2 библиотеки при установке через composer (amocrm-api-library и ouath2-amocrm) и с какой работать?

Поэтому, собственно вопросы:
1. Если код за 20 минут протух, а я не написал свой код, то мне новую интеграцию делать? Потому что refresh_token я уже не получу.
2. Если мне в рамках моего аккаунта требуется передать лида из формы на моем сайте в мой же аккаунт CRM, то зачем мне запрашивать какой-то доступ (у кого? у посетителя сайта? у администратора, аккаунт которого используется?), рисовать окна, кнопки и прочее, чтобы получить refresh_token?
3. Или мне сначала нарисовать кнопку для себя самого, чтобы пройти авторизацию и получить злосчастный токен? После разработки я это клиенту как объяснять буду?

**Comment by zerobig** [comment]
Кто-то задаётся теми же вопросами которыми когда-то задавался и я. Значит я не тупой...

> Если код за 20 минут протух, а я не написал свой код, то мне новую интеграцию делать? Потому что refresh_token я уже не получу.

Получите. Достаточно открыть настройки виджета и там код авторизации изменится. И пойдёт новый отсчёт 20 минут.

> Если мне в рамках моего аккаунта требуется передать лида из формы на моем сайте в мой же аккаунт CRM, то зачем мне запрашивать какой-то доступ (у кого? у посетителя сайта? у администратора, аккаунт которого используется?), рисовать окна, кнопки и прочее, чтобы получить refresh_token?

Это всё же многопользовательский тиражный продукт, рассчитанный на самые разные варианты использования. Так что доступы через OAuth и прочие "заморочки" считаю оправданными.

> Или мне сначала нарисовать кнопку для себя самого, чтобы пройти авторизацию и получить злосчастный токен? После разработки я это клиенту как объяснять буду?

Не надо ничего "рисовать". Достаточно получить clientId, secret, код авторизации. [Обменять их на access_token и refresh_token.](https://www.amocrm.ru/developers/content/oauth/step-by-step#%D0%9E%D0%B1%D0%BC%D0%B5%D0%BD-%D0%BA%D0%BE%D0%B4%D0%B0-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%BD%D0%B0-access-token-%D0%B8-refresh-token) И потом не забывать периодически обновлять access_token [до того как протухнет refresh_token](https://www.amocrm.ru/developers/content/oauth/step-by-step#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-access-token-%D0%BF%D0%BE-%D0%B5%D0%B3%D0%BE-%D0%B8%D1%81%D1%82%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B8). Иначе придётся опять начинать с кода авторизации.

**Comment by DaemonHK** [comment]
Я вроде разобрался с авторизацией и обменом токенами, но теперь встал вопрос, где взять ID полей в unsorted лидах. В документации сказано, что можно посмотреть при редактировании, но теперь там только создание/удаление/передвигание оставили, никаких ID в помине нет... Получение информации о текущем аккаунте с custom_fields возвращает голую инфу об аккаунте. То ли я тупой, то ли лыжи не едут...

**Comment by zerobig** [comment]
Id полей для unsorted точно такие же как и для обычных объектов.
[Посмотреть можно запросом](https://www.amocrm.ru/developers/content/crm_platform/custom-fields)

**Comment by DaemonHK** [comment]
Я все таки тупой... Я получал эти поля ранее, но utm_term и прочее мне ни о чем не говорит. Как мне в лида/неразобранное/входящую заявку передать имя, телефон, email и прочее?

**Comment by zerobig** [comment]
А в лидах телефона нет и не было. Разве что кто-то из особо талантливых клиентов не добавлял... Телефоны есть в контактах и компаниях. Соответственно:
GET /api/v4/contacts/custom_fields
GET /api/v4/companies/custom_fields

**Comment by DaemonHK** [comment]
Спасибо! Вроде разобрался. Но все эти интерфейсы, коллекции, модели, это нечто...

**Comment by gergel0304** [comment]
> Спасибо! Вроде разобрался. Но все эти интерфейсы, коллекции, модели, это нечто...

Добро пожаловать в API от amoCRM, где нет понятной документации, и нужно изрядно попотеть (я бы даже сказал по другому), чтобы хоть что-то понять :)))))
