### ISSUE TITLE
 Как получить последний созданный id company и contact ?

### ISSUE THREAD

**Issue by Sa1rus-php** [amocrm/amocrm-api-php#429]
Как это можно сделать ?

**Comment by eugene-borovov** [comment]
Поскольку API фильтров до сих пор необщедоступно, то я подобные вещи делал через события:
* Запрашиваем список событий типа [lead_added](https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#events-types) 
* Фильтруем события [filter[entity][]=lead&limit=1](https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#events-list) (события сортированы по убыванию времени)
* Из [value_after[0][lead][id]](https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#events-params) получаем ID последней сделки.
* По ID сделки загружаем контакты.

**Comment by DaemonHK** [comment]
Попробуйте что-то подобное:

```
$contactsService = $apiClient->contacts();
try {
    $contactsTryAdd = $contactsService->addOne($contact);
} catch (AmoCRMApiException $e) {
    $this->printError($e);
    die;
}

$contactID = $contactsTryAdd->getId();
$contact = $apiClient->contacts()->getOne($contactID);
```

**Comment by Sa1rus-php** [comment]
> Попробуйте что-то подобное:
> 
> ```
> $contactsService = $apiClient->contacts();
> try {
>     $contactsTryAdd = $contactsService->addOne($contact);
> } catch (AmoCRMApiException $e) {
>     $this->printError($e);
>     die;
> }
> 
> $contactID = $contactsTryAdd->getId();
> $contact = $apiClient->contacts()->getOne($contactID);
> ```
> 
> С компанией работать не приходилось, но думаю, ситуация такая же. То есть мы создаем контакт, затем добавляем его через сервис, а после получаем последний добавленный ID, с которым можно дальше работать. Вроде так.

Супер, спасибо
