### ISSUE TITLE
При заполнении нескольких дополнительных полей, не корректно добавляются значения 

### ISSUE THREAD

**Issue by dellirom** [amocrm/amocrm-api-php#43]
При заполнении дополнительных полей, в коллекцию leadCustomFieldsValues добавляется несколько сущностей дополнительных полей, но при этом все они равны последней сущности. (Значения и id  одинаковы)

$textCustomFieldValueModel = new TextCustomFieldValuesModel();
$leadCustomFieldsValues = new CustomFieldsValuesCollection();

$textCustomFieldValueModel->setFieldId('56309');
$textCustomFieldValueModel->setValues(
	(new TextCustomFieldValueCollection())
	->add((new TextCustomFieldValueModel())->setValue('132456'))
);
$leadCustomFieldsValues->add($textCustomFieldValueModel);

$textCustomFieldValueModel->setFieldId('58767');
$textCustomFieldValueModel->setValues(
	(new TextCustomFieldValueCollection())
	->add((new TextCustomFieldValueModel())->setValue('756'))
);
$leadCustomFieldsValues->add($textCustomFieldValueModel);

var_dump($leadCustomFieldsValues); die();

Ниже привожу var_dump созданной коллекции CustomField

object(AmoCRM\Collections\CustomFieldsValuesCollection)#141 (1) {
  ["data":protected]=>
  array(2) {
    [0]=>
    object(AmoCRM\Models\CustomFieldsValues\TextCustomFieldValuesModel)#144 (4) {
      ["fieldId":protected]=>
      int(58767)
      ["fieldCode":protected]=>
      NULL
      ["fieldName":protected]=>
      NULL
      ["values":protected]=>
      object(AmoCRM\Models\CustomFieldsValues\ValueCollections\TextCustomFieldValueCollection)#133 (1) {
        ["data":protected]=>
        array(1) {
          [0]=>
          object(AmoCRM\Models\CustomFieldsValues\ValueModels\TextCustomFieldValueModel)#134 (1) {
            ["value":protected]=>
            string(3) "756"
          }
        }
      }
    }
    [1]=>
    object(AmoCRM\Models\CustomFieldsValues\TextCustomFieldValuesModel)#144 (4) {
      ["fieldId":protected]=>
      int(58767)
      ["fieldCode":protected]=>
      NULL
      ["fieldName":protected]=>
      NULL
      ["values":protected]=>
      object(AmoCRM\Models\CustomFieldsValues\ValueCollections\TextCustomFieldValueCollection)#133 (1) {
        ["data":protected]=>
        array(1) {
          [0]=>
          object(AmoCRM\Models\CustomFieldsValues\ValueModels\TextCustomFieldValueModel)#134 (1) {
            ["value":protected]=>
            string(3) "756"
          }
        }
      }
    }
  }
}

Помогите решить данную проблему. Возможно это баг?

**Comment by Umarbatalov** [comment]
Это не баг.
Вы добавляете элементы в массив, которые ссылаются на один и тот же объект.
Вот показательный пример

```php
$a = new stdClass();

$a->value1 = 'example1';
$a->value2 = 'example2';

$b = [];

$b[] = $a;

$a->value1 = 'example3';
$a->value2 = 'example4';

$b[] = $a;

die(print_r($b));
```
Результат:

```php
Array
(
    [0] => stdClass Object
        (
            [value1] => example3
            [value2] => example4
        )

    [1] => stdClass Object
        (
            [value1] => example3
            [value2] => example4
        )

)
```

Если переделать ваш пример, он будет выглядеть так:

```php
$textCustomFieldValueModel = new TextCustomFieldValuesModel();
$textCustomFieldValueModel2 = new TextCustomFieldValuesModel();

$leadCustomFieldsValues = new CustomFieldsValuesCollection();

$textCustomFieldValueModel->setFieldId('56309');
$textCustomFieldValueModel->setValues(
    (new TextCustomFieldValueCollection())
        ->add((new TextCustomFieldValueModel())->setValue('132456'))
);
$leadCustomFieldsValues->add($textCustomFieldValueModel);

$textCustomFieldValueModel2->setFieldId('58767');
$textCustomFieldValueModel2->setValues(
    (new TextCustomFieldValueCollection())
        ->add((new TextCustomFieldValueModel())->setValue('756'))
);

$leadCustomFieldsValues->add($textCustomFieldValueModel2);

die(print_r($leadCustomFieldsValues->toArray()));
```

**Comment by dellirom** [comment]
Понял спасибо.
