### ISSUE TITLE
Ошибка запроса, а затем ошибка в получении токена

### ISSUE THREAD

**Issue by gergel0304** [amocrm/amocrm-api-php#434]
Рабочая интеграция стала давать сбой, сначала при запросе сделки стала вылетать ошибка:
```
Error: Response body is not json
Code: 403
Debug: array (
  'last_http_method' => 'GET',
  'last_method' => 'https://ibragimovaa.amocrm.ru/api/v4/leads/10614761',
  'last_body' => 
  array (
  ),
  'last_query_params' => 
  array (
  ),
  'last_response' => '


403 Forbidden

nginx



',
  'last_response_code' => NULL,
  'last_request_id' => NULL,
  'jquery_call' => '
$.ajax({
    url: "https://ibragimovaa.amocrm.ru/api/v4/leads/10614761",
    data: JSON.stringify([]),
    type: "GET",
    contentType: "application/json"
});',
  'curl_call' => 'curl "https://ibragimovaa.amocrm.ru/api/v4/leads/10614761" -X "GET" -d""',
  'timestamp' => 1643027224,
)
```

Затем при попытке переустановить интеграцию (удалил и снова добавил), стала вылетать ошибка:
```
AmoCRM\Exceptions\AmoCRMoAuthApiException: AmoCRM\OAuth2\Client\Provider\AmoCRMException: Error happen in /home/g/gergel/amocrm/public_html/vendor/amocrm/oauth2-amocrm/src/AmoCRMException.php:28 Stack trace: #0 /home/g/gergel/amocrm/public_html/vendor/amocrm/oauth2-amocrm/src/AmoCRM.php(163): AmoCRM\OAuth2\Client\Provider\AmoCRMException::errorResponse(Object(GuzzleHttp\Psr7\Response), '\r\n<...') #1 /home/g/gergel/amocrm/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): AmoCRM\OAuth2\Client\Provider\AmoCRM->checkResponse(Object(GuzzleHttp\Psr7\Response), '\r\n<...') #2 /home/g/gergel/amocrm/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #3 /home/g/gergel/amocrm/public_html/vendor/amocrm/amocrm-api-library/src/AmoCRM/OAuth/AmoCRMOAuth.php(133): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array) #4 /home/g/gergel/amocrm/public_html/amocrm/get_token.php(45): AmoCRM\OAuth\AmoCRMOAuth->getAccessTokenByCode('def502002ebab67...') #5 {main} in /home/g/gergel/amocrm/public_html/vendor/amocrm/amocrm-api-library/src/AmoCRM/OAuth/AmoCRMOAuth.php:136 Stack trace: #0 /home/g/gergel/amocrm/public_html/amocrm/get_token.php(45): AmoCRM\OAuth\AmoCRMOAuth->getAccessTokenByCode('def502002ebab67...') #1 {main}
```

при этом повторюсь, интеграция изначально работала, что могло произойти?

**Comment by eugene-borovov** [comment]
Вам как бы русским по-английски намекают: `403 Forbidden`
Проверьте пользователя, которым авторизуете интеграцию: может его отключили или понизили в правах, что он не может  чужие сделки читать.

**Comment by gergel0304** [comment]
Нет, ошибка была в .env.dist

**Comment by i4j5** [comment]
@gergel0304 Как решили проблему?

**Comment by PikalovAlexey** [comment]
Как решили проблему?

**Comment by TemaSM** [comment]
### **Для тех кто будет в будущем искать решение этой проблемы:**
Вероятнее всего в вашем случае amoCRM применил блокировку из-за превышения лимита отправки запросов к API.
Подробнее:
https://www.amocrm.ru/developers/content/api/recommendations

> Предусмотрены механизмы ограничения активности работы с API – **не более 7 запросов в секунду**.
> В случае подозрительной активности через API или сбоя интеграции, **доступ к API аккаунта может быть заблокирован**...
> ... при многократном нарушении ограничений, аккаунт блокируется **и на любой запрос в API будет возвращаться HTTP код 403**.

### **Как исправить?**
Вам нужно связаться с поддержкой через внутренний чат amoCRM и сообщить такие детали как:
1. IP адрес с которого делались запросы к API
2. Субдомен (аккаунт) amoCRM, который авторизовал интеграцию у себя в Амо, из под имени которого делались запросы, напр: `myaccount.amocrm.ru`
3. _(не обязательно)_ ID аккаунта (клиента), который авторизовал интеграцию у себя в Амо, из под имени которого делались запросы, напр: `12345678`: <details><summary>где его узнать в UI Амо</summary>![Image](https://github.com/user-attachments/assets/0cf8421c-8826-44d4-a4c0-f9ea7a193b8a)</details>
5. Сообщить что ловите ошибку 403 при обращениях к API

После чего Амо снимет ограничения и запросы будут корректно отрабатывать.
! Однако не рекомендуется этим злоупотреблять и лучше предусмотреть в коде рейт-лимитирование уходящих в сторону API запросов, во избежание повторных и перманентных блокировок от Амо.
