### ISSUE TITLE
Какие требования к сервису, который указывается в redirect_uri?

### ISSUE THREAD

**Issue by nlv** [amocrm/amocrm-api-php#452]
Подскажите пожалуйста.

Предполагаю получать данные из амоцрм со своего компа и уже приватно анализировать данные. "Публичной" интеграции мне не нужно. Но, как я понял, все равно придется указывать redirect_uri, который в моем случае особого смысла не имеет.

Вопрос, собственно вот в чем. Мне все равно придется использовать сервер с зарегистрированным доменом (еще и защищенный ssl-сертификатом)? 

Какие требования к ресурсу, который указывается в redirect_uri? Должен ли быть реализован реальный сервис, который что-то будет отвечать на запросы? 

Может, мне просто запускать скрипт по получению токенов надо запускать с хоста, который имеет  домен, указанный в redirect_uri?

**Comment by makeroi** [comment]
В вашем случае предлагаю указать любой хост (условно https://yandex.ru).
Главное, что бы он же был указан на вашем бэке и вы его использовали при авторизации по коду.

Вы можете скопировать из виджета авторотационный код (действующий 20 минут) и получить связку токенов со своего компьютера. В перспективе с помощью рефреш токена получать новый авторизационный токен и так существовать.

**Comment by nlv** [comment]
Благодарю за ответ! 

Пытался указать "любой" хост (не яндекс). Не получилось. Или не смог понять, как это сделать. Или, все же, моцрм требует, чтобы с этого хоста запрос на токены был осуществлен.

В итоге, настроил свой выделенный сервер со своим доменным именем. Его и указал в качестве redirect_url. С этого домена отправил запрос на токены. Все получилось.
