### ISSUE TITLE
В CustomFields сделки у поля типа Select выбрать одно из значений уже имеющихся в списке по enumId

### ISSUE THREAD

**Issue by rashn** [amocrm/amocrm-api-php#453]
Добрый день!
В CustomFields сделки у поля типа Select выбрать одно из значений уже имеющихся в списке по enumId

КОД:

	$selectCustomFieldValueModel = new SelectCustomFieldValuesModel();
	$selectCustomFieldValueModel->setFieldId(797641);
	$selectCustomFieldValueModel->setValues(
		(new SelectCustomFieldValueCollection())
		->add((new SelectCustomFieldValueModel())->setEnumId(564093))
	);
	$selectCustomFieldValueModel=$customFields->add($selectCustomFieldValueModel);
	
Создает еще одно поле с fieldId 797641 с заполненным enumID, но без value

При этом ранее заполненное поле остается

**Comment by rashn** [comment]
Отвечаю сам себе для будущих поколений ))) Нужно было обновить сделку и АМО обновит поле. Рабочий код:

$leadID=11111;
$fieldID=2222;
$newEnumID=3333;
$lead = $apiClient->leads()->getOne($leadID);
	$customFields = $lead->getCustomFieldsValues();
		$selectCustomFieldValueModel = new AmoCRM\Models\CustomFieldsValues\SelectCustomFieldValuesModel();
			$selectCustomFieldValueModel->setFieldId($fieldID);
			$selectCustomFieldValueModel->setValues(
				(new AmoCRM\Models\CustomFieldsValues\ValueCollections\SelectCustomFieldValueCollection())
					->add((new AmoCRM\Models\CustomFieldsValues\ValueModels\SelectCustomFieldValueModel())->setEnumId($newEnumID))
				);
	$customFields->add($selectCustomFieldValueModel);
$apiClient->leads()->updateOne($lead);

**Comment by makeroi** [comment]
@rashn закрывайте как решеное :)

**Comment by rashn** [comment]
Решение:

`function setStringValue(&$customFields, $varID, $value)
{
	if (!$value) return;
		$value=trim($value);
		
		$textField = (new TextCustomFieldValuesModel())->setFieldId($varID);
		$textFieldValueCollection = (new TextCustomFieldValueCollection());
		$customFields->add($textField);

		$textField->setValues(
			(new TextCustomFieldValueCollection())
				->add(
					(new TextCustomFieldValueModel())
						->setValue($value)
				)
		);
}
//////////

function setSelectValue(&$customFields, $varID, $value)
{
	if (!$value) return;
	$value=trim($value);
	$selectCustomFieldValueModel = new AmoCRM\Models\CustomFieldsValues\SelectCustomFieldValuesModel();
	$selectCustomFieldValueModel->setFieldId($varID);
	 $selectCustomFieldValueModel->setValues(
	 	(new AmoCRM\Models\CustomFieldsValues\ValueCollections\SelectCustomFieldValueCollection())
	// 		//->add((new AmoCRM\Models\CustomFieldsValues\ValueModels\SelectCustomFieldValueModel())->setEnumId(564093))
	 		->add((new AmoCRM\Models\CustomFieldsValues\ValueModels\SelectCustomFieldValueModel())->setValue($value))
	 	);
	$customFields->add($selectCustomFieldValueModel);
}

// вызов
		$leadsService = $apiClient->leads();
		$lead = $leadsService->getOne($_POST['lead-id']);
		$customFields = $lead->getCustomFieldsValues();
                
                setStringValue($customFields,797659,'текстовое значение');
                setSelectValue($customFields, 797641,'значение списка');

`
