### ISSUE TITLE
Как получить кастомные поля сущности по ID группы полей?

### ISSUE THREAD

**Issue by YudovAlexei** [amocrm/amocrm-api-php#47]
Пытаюсь получить список полей из группы (Основное) по ID группы, но поля как вижу не привязаны к группе (Основное, "default"). Вопрос как их получить через библиотеку?

Вот пример полученного поля, но "group_id" у него пустое, хоть amoCRM отображает его в группе "Основное"
```
[0]=>
    object(AmoCRM\Models\CustomFields\TextCustomFieldModel)#126 (15) {
      ["id":protected]=>
      int(40335)
      ["name":protected]=>
      string(18) "Должность"
      ["groupId":protected]=>
      NULL
      ["sort":protected]=>
      int(504)
      ["isApiOnly":protected]=>
      bool(false)
      ["isDeletable":protected]=>
      bool(false)
      ["isVisible":protected]=>
      NULL
      ["isRequired":protected]=>
      NULL
      ["catalogId":protected]=>
      NULL
```

**Comment by bessudnov** [comment]
Если у поля group_id null - значит поле состоит в группе основное
В группе основное содержатся поля, которые не привязаны к другим группам
