### ISSUE TITLE
bug: Остатки Illuminate\\support

### ISSUE THREAD

**Issue by RomanMazyrin** [amocrm/amocrm-api-php#470]
При запросе к API на получение кастомных полей вываливается ошибка, если в аккаунте есть поля вложенного списка. Это происходит из-за того, что в коде библиотеки до сих пор есть использование Illuminate/support, хотя в релизе 0.9.0 (18cd35c) эта библиотека была удалена.

Использование замечено в следующих файлах:

1. vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/CustomFields/ChainedLists.php
2. vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/CustomFields/ChainedList.php

Версия библиотеки 0.11.0

**Пример ошибки:**

```json
{
    "name": "PHP Fatal Error",
    "message": "Class 'Illuminate\\Support\\Collection' not found",
    "code": 1,
    "file": ".../vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/CustomFields/ChainedLists.php",
    "line": 19
}
```

**Comment by RomanMazyrin** [comment]
Что там насчет фикса? Просто клиенты не могут использовать некоторые интеграции, если у них в аккаунте есть поля связанных списков, так как при запросе к АПИ просто падает ошибка.

Уже 2 релиза вышло, а ошибка осталась((

**Comment by eugene-borovov** [comment]
Чтобы не падало добавьте в зависимости illuminate/support.

**Comment by pavelshulaev** [comment]
Апрель 2024, бага всё еще актуальна

**Comment by tweenpix** [comment]
> Апрель 2024, бага всё еще актуальна

В копилку причин, почему уходят с amocrm

**Comment by bessudnov** [comment]
Данная библиотека распространяется как Open Source решение, любой участник сообщества может предложить варианты изменений

**Comment by bessudnov** [comment]
поправили в релизе 1.8.0
