### ISSUE TITLE
Как долго живет "refresh_token" ?

### ISSUE THREAD

**Issue by SupchickCode** [amocrm/amocrm-api-php#475]
Здравствуйте, хотел узнать на счёт интеграций.

Как долго живет "refresh_token" ?

Есть вот такой раздел у вас в доке "https://www.amocrm.ru/developers/content/oauth/step-by-step#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-Access-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD-%D0%BF%D0%BE-%D0%BA%D0%BE%D0%B4%D1%83-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-bash"

Делаем curl запрос который вернет вот такой вот ответ 

```
{
    "token_type": "Bearer",
    "expires_in": 86400,
    "access_token": "ХХХХХХХХХХХХХХХХХХ",
    "refresh_token": "XXXXXXXXXXXXXXXXX"
}
```

И мне не понятно это два токена будут жить 24 часа или только access_token, а refresh_token посути вечный, но одноразовый ?

Может ли быть такая ситуация что я сделал запрос на авторизацию и получил токены сохранил их и некст запросом создал лид например. Проходит 24 часа и я снова хочу создать лид и делать запрос для получения нового access_token, но время жизни refresh_token закончилось и что теперь делать ?

**Comment by eugene-borovov** [comment]
По ссылке в доке написано, что refresh_token живёт 3 месяца. А также является глобально одноразовым, то есть если кто-то в другом клиенте уже использовал токен, то он сразу же устаревает. Это важно если у клиентов нет глобального хранилища токенов.
