### ISSUE TITLE
file_custom_field

### ISSUE THREAD

**Issue by Vahagn-99** [amocrm/amocrm-api-php#486]
здравствуйте уже несколько дней использую эту сдк и все отлично роботает, вот сегодня есть задача реализовать отправку изображение в амо,но в документации не разобрался, и здесь толком ничего не говорится, кто может помочь ?

**Comment by bessudnov** [comment]
добрый день, в данный момент поддержки файлов пока нет, но в ближайших обновлениях она появится, функционал уже реализован, как пройдет обкатку внутри наших сервисов, он появится и тут
