### ISSUE TITLE
php 8.1 library problem

### ISSUE THREAD

**Issue by sezerkaratas** [amocrm/amocrm-api-php#489]
Deprecated: Return type of AmoCRM\Collections\BaseApiCollection::offsetSet($offset, $value): AmoCRM\Collections\BaseApiCollection should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/mosstqsp/public_html/wp-content/plugins/amocrm-google/amocrm/vendor/amocrm/amocrm-api-library/src/AmoCRM/Collections/BaseApiCollection.php on line 113

Deprecated: Return type of AmoCRM\Collections\BaseApiCollection::offsetUnset($offset): AmoCRM\Collections\BaseApiCollection should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/mosstqsp/public_html/wp-content/plugins/amocrm-google/amocrm/vendor/amocrm/amocrm-api-library/src/AmoCRM/Collections/BaseApiCollection.php on line 184

Deprecated: Return type of AmoCRM\Collections\BaseApiCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/mosstqsp/public_html/wp-content/plugins/amocrm-google/amocrm/vendor/amocrm/amocrm-api-library/src/AmoCRM/Collections/BaseApiCollection.php on line 316

Can you help me ?

**Comment by pwsdotru** [comment]
This  deprecated issues already fixed in current version.

Just update your local version of library to last version.
