### ISSUE TITLE
В методах fromArray классов, унаследованных от NoteModel, игнорируется поле params

### ISSUE THREAD

**Issue by dura4kov** [amocrm/amocrm-api-php#5]
https://github.com/amocrm/amocrm-api-php/blob/46952a8682b54bf56e74a41bd82f38f66bd0ea26/src/AmoCRM/Models/NoteType/CallNote.php#L46-L79

При вызове метода fromArray объекта класса CallNote (и прочих, унаследованных от NoteModel) создается новый экземпляр этого класса, который возвращается без каких либо изменений, поскольку в методе осуществляется обновление полей текущего объекта, а не вновь созданного. Это приводит к тому, что при вызове EntityNotes->get() поля элементов коллекции, отвечающие за хранение "дополнительной информации" примечаний, передаваемой в поле params,  оказываются выставленными в  null.

**Comment by bessudnov** [comment]
Ага, бага, спасибо)
В ближайшем релизе захвачу фикс

**Comment by bessudnov** [comment]
Исправил проблема в релизе 0.2.1
