### ISSUE TITLE
Ошибка при пустом результате

### ISSUE THREAD

**Issue by eugene-borovov** [amocrm/amocrm-api-php#501]
Если метод возвращает пустой результат, то создаётся не пустая коллекция, а NULL. Это вызывает ошибку на PHP8, так как на NULL нельзя проверить наличие метода (TypeError)
https://github.com/amocrm/amocrm-api-php/blob/b6b01b46859f5f119595ec5d730c87185f6f0129/src/AmoCRM/EntitiesServices/BaseEntity.php#L107

**Comment by dnklhtbgn** [comment]
Поправили в версии 1.1.1
