### ISSUE TITLE
Как получить client_id и client_secret приватного виджета?

### ISSUE THREAD

**Issue by StarlightProg** [amocrm/amocrm-api-php#503]
Я понимаю, как получить authorization_code при помощи webhook, но не могу понять, где мне взять client_id и client_secret. При создании приватной интеграции без кода, в окошке настроек всё было указано, а в виджете предлагают в поля ввести логин, api ключ и аккаунт(может что-то из этого и есть id и secret виджета).
(виджет делаю не в amocrm, а в krommo, но разницы быть по сути не должно)

**Comment by eugene-borovov** [comment]
Если зайти в установленную интеграцию, то на вкладке "Ключи и доступы" (Keys and scopes)

- **ID интеграции** -- client_id (Integration ID)
- **Секретный ключ** -- client_secret (Secret Key)
- **Код авторизации (действителен 20 минут)** -- authorization_code для упрощённой авторизации. (Authorization code)
