### ISSUE TITLE
История сделок по воронке

### ISSUE THREAD

**Issue by AvelPostol** [amocrm/amocrm-api-php#505]
можно ли через api получить историю движения сделки по воронке?

**Comment by PoMaH4yK** [comment]
https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#events-types

**Comment by AvelPostol** [comment]
Нет, нельзя. Поддержка ответила такого метода пока еще нет. Но можно через события логировать самостоятельно через вебхук не тратя запросы API
