### ISSUE TITLE
Method 'calls' error: "path" => "request_id", "detail" => "This value should not be null."

### ISSUE THREAD

**Issue by Venckus** [amocrm/amocrm-api-php#51]
Thank you for making this beautiful library. I'm working on AmoCRM 'add calls' integration. Using your library as you shown in `examples/calls.php` got error `"path" => "request_id", "detail" => "This value should not be null."`. The solution I ended up looking at `CallModel()` and at `RequestIdTrait()` is to add one more method `->setRequestId('myId')` when creating `$call` object:
```
...
$call
    ->setPhone('+7912312321')
    ->setCallStatus(CallInterface::CALL_STATUS_SUCCESS_CONVERSATION)
    ->setCallResult('Разговор состоялся')
    ->setDuration(148)
    ->setUniq(Uuid::uuid4())
    ->setSource('integration name')
    ->setDirection(CallInterface::CALL_DIRECTION_IN)
    ->setLink('https://example.test/test.mp3')
    ->setRequestId('myId');
...
```

**Comment by bessudnov** [comment]
Thank you for feedback. Fix will be in next release (06.07.2020 or 07.07.2020)
