### ISSUE TITLE
Долгая загрузка лидов при добавлении фильтра

### ISSUE THREAD

**Issue by DimkaVIP** [amocrm/amocrm-api-php#510]
Обычное получение работает как нужно:
`$apiClient->leads()->get()`

Но когда добавляешь фильтр, загрузка начинает занимать очень много времени, около минуты, если не больше:
```
 $filter = new LeadsFilter();

$filter->setStatuses([
  ['status_id' => *******, 'pipeline_id' => *******]
]);

$ifiresLeads = $apiClient->leads()->get($filter, [LeadModel::CONTACTS]);
```
Иногда он заканчивается ошибкой "AmoCRMApiRequest.php line 455" "No content".

Как это исправить? Появилась ошибка буквально сегодня, раньше все работало без проблем. Код не менялся.

**Comment by eugene-borovov** [comment]
Это не ошибка. Просто с этим фильтром у вас нет сделок.
Я использую следующую обработку:
```php
try {
  запрос коллекции объектов
} catch (AmoCRMApiException $e) {
  if (in_array((int)($e->getLastRequestInfo()['last_response_code'] ?? 0), [204, 404], true)) {
    return пустая коллекция;
  }
  throw  $e;
}
```
