### ISSUE TITLE
Ошибка в файле /src/AmoCRM/EntitiesServices/BaseEntity.php в 107 строке в php 8.x

### ISSUE THREAD

**Issue by pavelshulaev** [amocrm/amocrm-api-php#512]
Если в /src/AmoCRM/EntitiesServices/BaseEntity.php в 105 строке $collection присваивается null (нет сущностей), то далее в 107 строке ловим ошибку:

`method_exists(): Argument #1 ($object_or_class) must ne type object|string, null given`

скрин https://skr.sh/sJxKe4o3Ubi

**Comment by eugene-borovov** [comment]
#501

**Comment by dnklhtbgn** [comment]
Поправили в версии 1.1.1
