### ISSUE TITLE
Получение сделок по компании

### ISSUE THREAD

**Issue by exxxt4zy** [amocrm/amocrm-api-php#547]
Напишите пожалуйста пример получения всех сделок по ID компании.

**Comment by makeroi** [comment]
$company = $apiClient()->companies()->getOne($id, EntityTypeInterface::CONTACTS);
$ids = $company->getContacts()?->pluck('id');
if($ids) {
$allContacts = $apiClient->contacts()->get((new ContactFilter())->setIds($ids));
}
