### ISSUE TITLE
Отсутствует реализация подключения с долгосрочными токенами

### ISSUE THREAD

**Issue by tihoho** [amocrm/amocrm-api-php#550]
Возможность была введена 12 февраля 2024.

Может кто пример показать как будет выглядеть обращение к api с долгосрочным токеном?

**Comment by NizamiKhan** [comment]
Тоже интересует когда введут возможность работы с долгосрочными токенами.

Я смог решить это, но реализация похоже больше на костыль из за того что для работы клиента нужен объект AccessToken, в конструкторе которого обязателен **expires**.
Пример кода:

`            $token = config('amocrm.api.token');
            $clientSecret = config('amocrm.api.secret_key');
            $clientId = config('amocrm.api.integration_id');
            $subDomain = config('amocrm.sub_domain');

            $accessToken = new AccessToken([
                'access_token' => $token,
                'expires' => Carbon::now()->addYears(5)->getTimestamp(),
            ]);
            $apiClient = new \AmoCRM\Client\AmoCRMApiClient($clientId, $clientSecret, null);
            $apiClient->setAccountBaseDomain(sprintf('%s.amocrm.ru', $subDomain));
            $apiClient->setAccessToken($accessToken);`

**Comment by bessudnov** [comment]
тут правда +- костыли придется делать, так как завязаны на внешнюю библиотеку для реализации токенов и тд

можно было бы отказаться и переписать, но не очень вижу смысла

небольшие улучшения и примеры добавим в следующем релизе библиотеки

**Comment by bessudnov** [comment]
добавлена поддержка
https://github.com/amocrm/amocrm-api-php?tab=readme-ov-file#%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%81-%D0%B4%D0%BE%D0%BB%D0%B3%D0%BE%D0%B6%D0%B8%D0%B2%D1%83%D1%89%D0%B8%D0%BC-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%BE%D0%BC

**Comment by alexio777** [comment]
> добавлена поддержка https://github.com/amocrm/amocrm-api-php?tab=readme-ov-file#%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%81-%D0%B4%D0%BE%D0%BB%D0%B3%D0%BE%D0%B6%D0%B8%D0%B2%D1%83%D1%89%D0%B8%D0%BC-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%BE%D0%BC

а если он уже создан? как использовать этот токен?

**Comment by eugene-borovov** [comment]
Всегда было интересно, почему не используется OAuth2 Client Credentials Grant. Ведь для серверного API самое то. Обменял client_id и client_secret на пару ключей и всё. И не нужно костылять с получением auth_code из профиля. Auth Code Grant используется для небезопасных клиентов, например, для кнопки в js. А на сервере это излишне.
