### ISSUE TITLE
Старая версия nesbot/carbon

### ISSUE THREAD

**Issue by Yoji** [amocrm/amocrm-api-php#553]
При попытке установить `composer require amocrm/amocrm-api-library` например в Laravel выдаёт ошибку:

>  - amocrm/amocrm-api-library[0.1, ..., 0.3.11] require guzzlehttp/guzzle 6.* -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but the package is fixed to 7.8.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command

При указании точной версии:
`composer require amocrm/amocrm-api-library:1.6`

Выдаёт ошибку:

> - amocrm/amocrm-api-library 1.6.0 requires nesbot/carbon ^2.52 -> found nesbot/carbon[2.52.0, ..., 2.72.3] but the package is fixed to 3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by inilim** [comment]
Поддерживаю, следует обновить

**Comment by bessudnov** [comment]
обновили в версии 1.7.0
