### ISSUE TITLE
Совместимость с php 7.3

### ISSUE THREAD

**Issue by RaynoldRipper** [amocrm/amocrm-api-php#557]
PHP Fatal error:  Uncaught AmoCRM\\Exceptions\\InvalidArgumentException: Error parsing given access token. Prev error: syntax error in

Ошибка возникает на старой версии php. В моем случае php 7.3. Возникает она по причине того, что у связанных классов с классом LongLivedAccessToken свойств указаны либо типы либо интерфейсы.

Например у класса - Lcobucci\JWT\Configuration указаны свойства:
    private Parser $parser;
    private Signer $signer;
    private Key $signingKey;
    private Key $verificationKey;
    private Validator $validator;

Из-за того что у свойств указаны в данном случае интерфейсы, из-за этого возникает ошибка совместимости со старыми версиями.

Удалив типы и интерфейсы со свойств я решил эту проблему

p.s. Разрабам на заметку.

**Comment by bessudnov** [comment]
Вообще библиотека работает и с новой и со старой версией JWT

По идее такое может быть, что композером прошлись на новой версии php, а дальше запускаете старой версией

Вы можете у себя зафиксировать версию JWT в вашем composer.json -  "lcobucci/jwt": "3.4.6" и проблем не должно быть


откройте заново issue, если проблема будет актуальна
