### ISSUE TITLE
Для getLinks не работает фильтр по типам сущностей

### ISSUE THREAD

**Issue by inouticu** [amocrm/amocrm-api-php#63]
Возвращает все связи, независимо от установленного фильтра. 
См. пример на скриншоте: https://prnt.sc/te4i01

**Comment by Umarbatalov** [comment]
Для фильтра также необходимо передать параметр `to_entity_id`

```php
$leads = $apiClient
    ->leads()
    ->getLinks(
        (new LeadModel())
            ->setId(12345),
        (new LinksFilter())
            ->setToEntityId(54321)
            ->setToEntityType('contacts')
    )
    ->toArray();

print_r($leads);
```
Но в библиотеке маленький [фикс](https://github.com/amocrm/amocrm-api-php/pull/64) нужен, чтоб фильтр заработал.

**Comment by bessudnov** [comment]
Фикс влил, в ближайшем релизе будет

**Comment by bessudnov** [comment]
Исправление доступно в релизе 0.3.3
