### ISSUE TITLE
Ошибка в модели \AmoCRM\Models\Unsorted\BaseUnsortedModel

### ISSUE THREAD

**Issue by rinashen** [amocrm/amocrm-api-php#67]
Запрос на добавление в Неразобранное формируется через метод toApi() модели \AmoCRM\Models\Unsorted\BaseUnsortedModel
В ней сущность заявки передаётся в параметре lead, хотя в документации API сказано, что сущность заявки передаётся в параметре leads.
В итоге при попытке отправить заявку через существующую модель, базирующуюся на BaseUnsortedModel заявка в Неразобранном создаётся, а вот сущность сделки - нет, из-за того, что отправляется в неверном параметре.

Если заменить в методе toApi() строку `$result[AmoCRMApiRequest::EMBEDDED]['lead'] = $this->getLead()->toApi($requestId);` на строку `$result[AmoCRMApiRequest::EMBEDDED]['leads'][] = $this->getLead()->toApi($requestId);` А так же в методе toArray() заменить `$result['lead']` на `$result['leads']`, то всё работает и добавляется корректно

**Comment by RomanMazyrin** [comment]
Мое почтение! Только я собрался написать про это, а уже 6 часов как есть issue) @bessudnov Ждем исправления =)

Немного добавлю от себя: я просто исправил строку 411 (метод toApi) на вот такую:

```
$result[AmoCRMApiRequest::EMBEDDED]['leads'] = [$this->getLead()->toApi($requestId)];
```

И тоже все корректно заработало. Но скорее всего метод toArray тоже надо поправить, как сказал @rinashen.
