### ISSUE TITLE
Получить контакт по кастом полю

### ISSUE THREAD

**Issue by podkot** [amocrm/amocrm-api-php#71]
Привет!

```php
$FIELD_ID = 12345; // int ID, не name
$FIELD_VAL = 67890;
$filter = (new ContactsFilter())->setCustomFieldsValues([ $FIELD_ID => $FIELD_VAL ]);
$apiClient->contacts()->get($filter); // возвращаются неотфильтрованные контакты
```

Подскажите плз, что я делаю не так?
В примерах не нашел фильтра по кастом полям.

Также в ридми написано "ContactsFilter — Доступен только на аккаунтах, которые подключены к тестированию функционала фильтрации по API" — это актуально? (В техническую поддержку также написал)

Upd: поддержка ответила, что фильтрация включается по запросу, запросил включение. Вопрос с тем, как правильно фильтровать по кастом полям, актуален.

**Comment by bessudnov** [comment]
Поддержка ответила верно, функционал фильтрации через API пока что включается только по запросу и одобрения.
Закрытая бета.
Постепенно начинаем давать доступ к функционалу большему и большему количеству аккаунтов.

**Comment by Arbuzzzi** [comment]
А как получить контакт по номеру телефона? Или сейчас это лучше делать с помощью getRequest?

**Comment by Umarbatalov** [comment]
@Arbuzzzi [issue#38](https://github.com/amocrm/amocrm-api-php/issues/38)

**Comment by evgenlucen** [comment]
> А как получить контакт по номеру телефона? Или сейчас это лучше делать с помощью getRequest?

Пока query не отключили и фильтры не работают можно get из BaseEntity дополнить.

\src\AmoCRM\EntitiesServices\BaseEntity

/**
     * Получение коллекции сущностей
     * @param null|BaseEntityFilter $filter
     * @param **null|array $with**
     * @param string|int $query
     *
     * @return BaseApiCollection|null
     * @throws AmoCRMApiException
     * @throws AmoCRMoAuthApiException
     */
    public function get(BaseEntityFilter $filter = null, **$with = null,$query = null**): ?BaseApiCollection
    {
        $queryParams = [];
        if ($filter instanceof BaseEntityFilter) {
            $queryParams = $filter->buildFilter();
        }
        $with = array_intersect($with, (static::ITEM_CLASS)::getAvailableWith());
        if (!empty($with)) {
            $queryParams['with'] = implode(',', $with);
        }
        **if (!empty($query)){
            $queryParams['query'] = $query;
        }**

        $response = $this->request->get($this->getMethod(), $queryParams);

        return $this->createCollection($response);
    }

**Comment by andreybolonin** [comment]
Подскажите, а куда написать, чтобы поддержка включила фильтрацию на аккаунте?

**Comment by nomelodic** [comment]
> Подскажите, а куда написать, чтобы поддержка включила фильтрацию на аккаунте?

В документации пишут:

> Партнеры amoCRM могут обратиться в техническую поддержку для подключения аккаунта к закрытому тестированию функционала. Заявки на подключение рассматриваются в индивидуальном порядке.

Вероятнее всего имеется ввиду поддержка в кабинете в амо http://joxi.ru/Vm6PjX1CjyWjkA

**Comment by andreybolonin** [comment]
@nomelodic да, вы правы, написали
Ждем включения уже месяц ))

**Comment by nomelodic** [comment]
> Ждем включения уже месяц ))

Мы тоже))

**Comment by RodionovSlsUp** [comment]
Ждем включения с августа. Раз в месяц пишу поддержки, говорят нет сроков, нет подключения. @bessudnov есть понимание, когда функционал выйдет из беты?

**Comment by bessudnov** [comment]
Когда выйдет из беты - пока нет сроков, а вот подключать аккаунты планируем продолжить на этой или следующей неделе

**Comment by s-anches** [comment]
То есть если у меня работает:
`
$filter = (new ContactsFilter())->setQuery('+79339990708');
$contact = $apiClient->contacts()->get($filter);
`
То значит у меня этот новый функционал подключен?

**Comment by RodionovSlsUp** [comment]
@bessudnov очень-очень ждем, неужели так много желающий, что пока не добрались? Может быть как то можно ускорить заявки от партнеров амоцрм? Ну 6 месяцев вообще ни о чем - мы же бесплатные тестировщики и багрепортеры:( 

@s-anches нет, setQuery доступен всем. В описании к библиотеке прописано, какие методы требуют допуска, а какие нет

**Comment by bessudnov** [comment]
@RodionovSlsUp подключили всех желающих пару недель назад, следующую пачку будем подключать думаю ближе к марту
