### ISSUE TITLE
Убрать лишнее  //

### ISSUE THREAD

**Issue by webds** [amocrm/amocrm-api-php#77]
Метод с примера: https://github.com/amocrm/amocrm-api-php/blob/master/examples/get_token.php

$ownerDetails = $apiClient->getOAuthClient()->getResourceOwner($accessToken);

Обращается к 3-ей версии API а еще не верный адрес https://xxxxxx.amocrm.ru//v3/user
(//v3/user) - api где то должно был быть по логике)

**Comment by bessudnov** [comment]
1) В данном запросе не должно быть API
2) Для данного метода обрабатывается кейс с //
3) Ничего страшного в обращении к третьей версии нет
4) Issue не относится к этой библиотеке, а относится к https://github.com/amocrm/amocrm-oauth-client
