### ISSUE TITLE
Вопрос на счет oAuth обновления токена по рефрешу

### ISSUE THREAD

**Issue by nkarpovich** [amocrm/amocrm-api-php#83]
Я использую упрощенную схему и auth_code беру сразу из админки АМО, у меня серверное приложение, которому нужен постоянный доступ. Используя рефреш-токен, обновляю AccessToken каждый раз перед запросом вот этим методом: 

AmoCRM/OAuth/AmoCRMOAuth.php строка 126 метод getAccessTokenByRefreshToken

Несколько запросов проходит нормально (в пределах одного дня, запросы делаю раз в час). В какой-то момент получаю ошибку 'Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны', хотя никакие параметры в моем приложении не изменяются. Соответственно, полученный AccessToken я каждый раз перезаписываю. 

Приходится перевыпускать ключ в админке.

Раньше я пробовал по expired проверять, если токен просрочился, запрашивать новый, но с этим проблемы тоже возникли - getAccessTokenByRefreshToken выдавал такую же ошибку.

**Comment by bigperson** [comment]
@nkarpovich Вам стоит явный ответ показать и обновлять AccessToken перед каждым запросом не лучшая идея.

**Comment by nkarpovich** [comment]
> @nkarpovich Вам стоит явный ответ показать и обновлять AccessToken перед каждым запросом не лучшая идея.

Согласен, но по истечению срока accessToken обновить токен по рефреш токену не выходит. Поэтому пошел таким путем.

**Comment by PoMaH4yK** [comment]
@nkarpovich Проверьте, одинаковые ли Redirect URL из интеграции в амо и у вас в коде.

**Comment by lmcsu** [comment]
1) Для упрощенной схемы авторизации Redirect URL не нужен, но его зачем-то оставили обязательным, при этом он должен присутствовать и точно совпадать с тем, что прописан в коде, иначе выбивает ошибку "Некорректный запрос". Я лично просто ссылку на Гугл туда прописываю.

2) Нет необходимости обновлять токен перед каждым запросом вручную. Это происходит автоматически в тот момент, когда время действия токена истечёт. При этом произойдёт вызов коллбека onAccessTokenRefresh, установив который, можно сохранить новые данные токена в базу/файл.

```
$apiClient = new AmoCRMApiClient($clientId, $clientSecret, $redirectUrl);
$apiClient->onAccessTokenRefresh(function ($accessToken) {
    $tokenData = [
        'accessToken' => $accessToken->getToken(),
        'refreshToken' => $accessToken->getRefreshToken(),
        'expires' => $accessToken->getExpires(),
        'baseDomain' => xxx_config('amo_domain'),
    ];
    file_put_contents('xxx', json_encode($tokenData));
});
```

**Comment by nkarpovich** [comment]
1. Да, я тоже туда левую ссылку прописываю
2. Ок спасибо, попробую через коллбек. Я понимаю, что каждый раз обновлять нет необходимости, до этого я перед каждым запросом делал проверку, просрочен ли токен. Но такой способ у меня почему-то выкидывал ошибки при попытке обновить токен по рефреш-токену.

**Comment by nkarpovich** [comment]
@lmcsu спасибо, работает пока стабильно.
