### ISSUE TITLE
DateCustomField невозможно передать отрицательный timestamp (дата <1970 года)

### ISSUE THREAD

**Issue by nkarpovich** [amocrm/amocrm-api-php#85]
Добрый день, а как передать отрицательные timestamp в custom date field? Amo ожидает на вход число больше 0, при попытке отправить отрицательное значение ругается.

**Comment by RomanMazyrin** [comment]
А для чего вам это нужно?

**Comment by nkarpovich** [comment]
Конкретно в моей задаче - мне нужно передавать дату рождения клиента.

**Comment by bessudnov** [comment]
В данный момент это большая недоработка.
Вероятно в будущем позволим для полей типа дата/время передавать как timestamp, как и форматированную дату

**Comment by dellert** [comment]
@bessudnov а когда предположительно исправится данный баг?

**Comment by RodionovSlsUp** [comment]
Создал тикет по подобной проблеме. Есть понимание по срокам решение?

**Comment by bessudnov** [comment]
> Создал тикет по подобной проблеме. Есть понимание по срокам решение?

а зачем тикет, если он уже есть?
По срокам подсказать не можем

**Comment by RodionovSlsUp** [comment]
Коллеги, пока нет сроков, очень критично, что не можем обработать часть сделок. Есть ли какое-нибудь, даже костыльное решение, которое позволяло бы работать с другими полями сделки?
Как то можно в методе лид апдейт, не трогать это поле, не стирая его при этом?

**Comment by eugene-borovov** [comment]
Чтобы обновить сделку не обязательно передавать все кастомные поля, только изменившиеся. Чтобы стереть поле, нужно явно передать пустое значение.

**Comment by viacheslav594** [comment]
@bessudnov добрый вечер! Мы можем рассчитывать на движение по этой задаче?

Взвыли уже из-за этой проблемы. Ладно, клиенты, которые использую прямо старые даты (как я понял на фронте минимальная дата 01.01.1000 года), попадаются редко (в основном магазины антиквариата), но вот даты рождения используют часто.

Мы уже придумали свою форму даты на основе текстового поля (была проблема раньше записи отрицательного числа в поле "Число", но сейчас не воспроизвелась), но это прямо очень большой костыль.

Я ни в коем случае, не хочу обесценивать вашу работу, но приведение лимитов АПИ в соответсвие фронту не звучит как что-то очень сложное, но эти правки очень бы облегчили жизнь комьюнити.

**Comment by bessudnov** [comment]
Хорошие новости для всех)
Задачка по поддержке значений полей до 1970 года в работе, сроков точных не назову, но думаю достаточно скоро будет поддержка.
