### ISSUE TITLE
Problem with get access to the users company 

### ISSUE THREAD

**Issue by YuriyEmpty** [amocrm/amocrm-api-php#86]
I need get company user by "responsible_user_id" what contains in the "ContactModel". Im trying to do this with a UsersService 
as shown in the example https://github.com/amocrm/amocrm-api-php/blob/99c57af1782de66c48022ee25ebe5ed7234b695c/examples/users_actions.php#L120
The problem is that I cannot do this if my account does not have administrator rights. How I can do that? 
Or get a company user by his ID without having administrator rights.

**Comment by bessudnov** [comment]
There is now way to get users without admin rights.
What data do you need from user? Now you can know user id of responsible user.
