### ISSUE TITLE
Ошибка при вызове метода getCurrent() у account

### ISSUE THREAD

**Issue by RomanMazyrin** [amocrm/amocrm-api-php#9]
Вот основной текст ошибки: 'Argument 1 passed to `AmoCRM\Models\AccountModel::setCreatedAt() must be an instance of Carbon\Carbon, integer given, called in...'`

Вот небольшой кусок stacktrace:

```
Stack trace:
#0 /Users/romanmazyrin/PhpstormProjects/mazdata/vendor/amocrm/amocrm-api-library/src/AmoCRM/Models/AccountModel.php(280): AmoCRM\Models\AccountModel->setCreatedAt(1550501841)
#1 /Users/romanmazyrin/PhpstormProjects/mazdata/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/Account.php(68): AmoCRM\Models\AccountModel::fromArray(Array)
#2 /Users/romanmazyrin/PhpstormProjects/mazdata/commands/HelloController.php(21): AmoCRM\EntitiesServices\Account->getCurrent(Array)
```

Проблема на лицо, то что передается в метод значение не того типа. Но проблема в том, что вчера работало нормально и не ругалось. Что за магия?

Ответ на запрос к серверу приходит нормальный, все ок.

Версия PHP 7.2.31, (cli)

**Comment by bessudnov** [comment]
Изначально хотели все даты в библиотеке сделать в виде объектов Carbon, но затем отказались от этой идеи, остался такой досадный артефакт

Фикс будет в ближайшем релизе
