### ISSUE TITLE
На многие запросы Error: Response body is not json

### ISSUE THREAD

**Issue by DELAKEY** [amocrm/amocrm-api-php#96]
При попытке добавить webhook или получить сделки выдает ошибку "Error: Response body is not json"

Полный текст ошибки
`Error: Response body is not  json

Code: 404
Debug: array (
  'last_http_method' => 'POST',
  'last_method' => 'https://www.amocrm.ru/api/v4/webhooks',
  'last_body' => 
  array (
    'destination' => 'https://example.com/',
    'settings' => 
    array (
      0 => 'add_lead',
    ),
  ),
  'last_query_params' => 
  array (
  ),
  'last_response' => '
\\далее html страница документации по вебхукам
',
  'last_response_code' => NULL,
  'last_request_id' => NULL,
  'jquery_call' => '
$.ajax({
    url: "https://www.amocrm.ru/api/v4/webhooks",
    data: JSON.stringify({"destination":"https:\\/\\/example.com\\/","settings":["add_lead"]}),
    type: "POST",
    contentType: "application/json"
});',
  'curl_call' => 'curl "https://www.amocrm.ru/api/v4/webhooks" -X "POST" -d"destination=https%3A%2F%2Fexample.com%2F&settings%5B0%5D=add_lead"',
  'timestamp' => 1596083362,
)
`
Php код который использую 
<?php

include_once("bootstrap.php");

use League\OAuth2\Client\Token\AccessToken;

use AmoCRM\Collections\ContactsCollection;
use AmoCRM\Collections\CustomFieldsValuesCollection;
use AmoCRM\Collections\Leads\LeadsCollection;
use AmoCRM\Collections\LinksCollection;
use AmoCRM\Collections\NullTagsCollection;
use AmoCRM\Exceptions\AmoCRMApiException;
use AmoCRM\Filters\LeadsFilter;
use AmoCRM\Models\CustomFieldsValues\TextCustomFieldValuesModel;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\NullCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueCollections\TextCustomFieldValueCollection;
use AmoCRM\Models\CustomFieldsValues\ValueModels\TextCustomFieldValueModel;
use AmoCRM\Models\LeadModel;
use League\OAuth2\Client\Token\AccessTokenInterface;

use AmoCRM\Models\WebhookModel;

$file_data = file_get_contents("amo.json");
$amo = json_decode($file_data,1);
$accessToken = new AccessToken([
            'access_token' => $amo['accessToken'],
            'refresh_token' => $amo['refreshToken'],
            'expires' => $amo['expires'],
            'baseDomain' => $amo['baseDomain'],
        ]);
//echo($accessToken);

$apiClient->setAccessToken($accessToken);

$ownerDetails = $apiClient->getOAuthClient()->getResourceOwner($accessToken);

printf('Hello, %s!', $ownerDetails->getName());

$webhook = new WebhookModel();
$webhook->setDestination('https://example.com/')
    ->setSettings([
        'add_lead'
    ]);

try {
    $webhook = $apiClient->webhooks()->subscribe($webhook);
} catch (AmoCRMApiException $e) {
    printError($e);
    die;
}

**Comment by bessudnov** [comment]
Похоже, что вы не установили домен для апи клиента и запросы делаете на промосайт, а не в аккаунт

**Comment by DELAKEY** [comment]
> Похоже, что вы не установили домен для апи клиента и запросы делаете на промосайт, а не в аккаунт

не устанавливал, а можно ткнуть где это нужно прописать или изменить настройки?
p.s. извиняюсь за невнимательность

**Comment by DELAKEY** [comment]
Пропустил setAccountBaseDomain
